### ISSUE TITLE
java.io.IOException: Invalid status code for access token tv response: 400

### ISSUE THREAD

**Issue by dc-developer-master** [lavalink-devs/Lavalink#1033]
## Description
When i attempted playing a track i got this error "java.io.IOException: Invalid status code for access token tv response: 400"

## To Reproduce
First load a track 
Second try to play track (it fails in here)

## Expected behavior
normally lavalink is supposed to play the track

## Version info
**Client used:** Magmastream/2.3.1

Output of `java -version`:
```
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Corretto-17.0.1.12.1 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.1.12.1 (build 17.0.1+12-LTS, mixed mode, sharing)
```

Lavalink Logs:
```
2024-04-04T18:36:29.661+03:00  INFO 23548 --- [main] lavalink.server.Launcher                 : Starting Launcher v4.0.4 using Java 17.0.1 with PID 23548 (C:\Users\Kerem Akman\Masa st \music-bot-v2\Lavalink.jar started by Kerem Akman in C:\Users\Kerem Akman\Masa st \music-bot-v2)
2024-04-04T18:36:29.668+03:00  INFO 23548 --- [main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2024-04-04T18:36:31.854+03:00  INFO 23548 --- [main] l.server.bootstrap.PluginManager         : Found plugin 'lavasrc-plugin' version 4.0.1
2024-04-04T18:36:32.047+03:00  INFO 23548 --- [main] l.server.bootstrap.PluginManager         : Loaded lavasrc-plugin-4.0.1.jar (123 classes)
2024-04-04T18:36:32.291+03:00  INFO 23548 --- [main] lavalink.server.Launcher                 : Started Launcher in 4.028 seconds (process running for 5.01)
2024-04-04T18:36:32.456+03:00  INFO 23548 --- [main] lavalink.server.Launcher                 : 

[32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[0m    =========================================[32m/_/_/_/[0m

	Version:        4.0.4
	Build time:     10.03.2024 17:32:10 UTC
	Branch          HEAD
	Commit:         bb5e126
	Commit time:    10.03.2024 17:29:08 UTC
	JVM:            17.0.1
	Lavaplayer      2.1.1

2024-04-04T18:36:32.482+03:00  INFO 23548 --- [main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2024-04-04T18:36:34.004+03:00  WARN 23548 --- [main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2024-04-04T18:36:34.060+03:00  INFO 23548 --- [main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2024-04-04T18:36:34.061+03:00  INFO 23548 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1569 ms
2024-04-04T18:36:34.247+03:00  INFO 23548 --- [main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Loading LavaSrc plugin...
2024-04-04T18:36:34.331+03:00  INFO 23548 --- [main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2024-04-04T18:36:34.694+03:00  INFO 23548 --- [main] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube master token (current is null).
2024-04-04T18:36:35.457+03:00  INFO 23548 --- [ForkJoinPool.commonPool-worker-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube master token succeeded, new token is 1//099-6...KOLUIbLnwjKZo.
2024-04-04T18:36:35.763+03:00  INFO 23548 --- [main] l.server.config.KoeConfiguration         : OS: WINDOWS, Arch: X86_64
2024-04-04T18:36:35.764+03:00  INFO 23548 --- [main] l.server.config.KoeConfiguration         : Enabling JDA-NAS
2024-04-04T18:36:35.780+03:00  INFO 23548 --- [main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2024-04-04T18:36:35.790+03:00  INFO 23548 --- [main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2024-04-04T18:36:35.839+03:00  WARN 23548 --- [main] l.server.config.SentryConfiguration      : Turning off sentry
2024-04-04T18:36:36.691+03:00  INFO 23548 --- [main] io.undertow                              : starting server: Undertow - 2.3.6.Final
2024-04-04T18:36:36.721+03:00  INFO 23548 --- [main] org.xnio                                 : XNIO version 3.8.8.Final
2024-04-04T18:36:36.747+03:00  INFO 23548 --- [main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.8.Final
2024-04-04T18:36:36.929+03:00  INFO 23548 --- [main] org.jboss.threads                        : JBoss Threads version 3.5.0.Final
2024-04-04T18:36:37.044+03:00  INFO 23548 --- [main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 1234 (http)
2024-04-04T18:36:37.057+03:00  INFO 23548 --- [main] lavalink.server.Launcher                 : Started Launcher in 4.75 seconds (process running for 9.776)
2024-04-04T18:36:37.059+03:00  INFO 23548 --- [main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2024-04-04T18:36:56.679+03:00  INFO 23548 --- [XNIO-1 task-2] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-04-04T18:36:56.680+03:00  INFO 23548 --- [XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-04-04T18:36:56.682+03:00  INFO 23548 --- [XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2024-04-04T18:36:56.721+03:00  INFO 23548 --- [XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:55191
2024-04-04T18:36:56.765+03:00  INFO 23548 --- [XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/websocket, client=127.0.0.1
2024-04-04T18:36:56.891+03:00  INFO 23548 --- [XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from Magmastream
2024-04-04T18:36:57.132+03:00  INFO 23548 --- [XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/8yqws07is8e4k9xk, client=127.0.0.1, payload={"resuming":true,"timeout":1000}
2024-04-04T18:37:28.791+03:00  INFO 23548 --- [XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:patlat"
2024-04-04T18:37:28.791+03:00  INFO 23548 --- [XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:patlat"
2024-04-04T18:37:28.923+03:00  INFO 23548 --- [XNIO-1 task-4] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/8yqws07is8e4k9xk/players/761947628765184032?noReplace=false, client=127.0.0.1, payload={"volume":100}
2024-04-04T18:37:29.542+03:00  INFO 23548 --- [XNIO-1 task-2] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: patlat
2024-04-04T18:37:29.542+03:00  INFO 23548 --- [XNIO-1 task-3] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: patlat
2024-04-04T18:37:29.587+03:00  INFO 23548 --- [XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3Apatlat, client=127.0.0.1
2024-04-04T18:37:29.587+03:00  INFO 23548 --- [XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch:patlat, client=127.0.0.1
2024-04-04T18:37:30.557+03:00  INFO 23548 --- [XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/8yqws07is8e4k9xk/players/761947628765184032?noReplace=false, client=127.0.0.1, payload={"voice":{"token":"f886b74349b003bb","endpoint":"frankfurt5720.discord.media:443","sessionId":"bd400e7fe57bd8d6cc03eee9036e53b7"}}
2024-04-04T18:37:31.427+03:00  INFO 23548 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube access token (current is null).
2024-04-04T18:37:31.428+03:00  INFO 23548 --- [XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/8yqws07is8e4k9xk/players/761947628765184032?noReplace=false, client=127.0.0.1, payload={"encodedTrack":"QAABDAMADkJsb2szIC0gUEFUTEFUAAVCbG9rMwAAAAAAAf+4AAswQXJFZ2twUmEzTQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PTBBckVna3BSYTNNAQCbaHR0cHM6Ly9pLnl0aW1nLmNvbS92aS8wQXJFZ2twUmEzTS9tYXhyZXNkZWZhdWx0LmpwZz9zcXA9LW9heW13RW1DSUFLRU5BRjhxdUtxUU1hOEFFQi1BSE9CWUFDMEFXS0Fnd0lBQkFCR0dFZ1lTaGhNQTg9JnJzPUFPbjRDTEFtN25tRjN3aWI1UmV1U2E5MDRvTHRwQWNTMncAAAd5b3V0dWJlAAAAAAAAAAA="}
2024-04-04T18:37:31.837+03:00 ERROR 23548 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube access token update failed.

java.io.IOException: Invalid status code for access token tv response: 400
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.requestAccessToken(YoutubeAccessTokenTracker.java:291) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchAccessToken(YoutubeAccessTokenTracker.java:224) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.updateAccessToken(YoutubeAccessTokenTracker.java:139) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.getAccessToken(YoutubeAccessTokenTracker.java:191) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeHttpContextFilter.onRequest(YoutubeHttpContextFilter.java:75) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequest(SettableHttpRequestFilter.java:41) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:70) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.fetchScript(DefaultYoutubeTrackDetailsLoader.java:282) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:202) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:83) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.1.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2024-04-04T18:37:32.458+03:00  INFO 23548 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube visitor id (current is null).
2024-04-04T18:37:32.603+03:00  INFO 23548 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube visitor id succeeded, new one is Cgs5...lNROFR...3D%3D, next update will be after 600 seconds.
2024-04-04T18:37:32.741+03:00  INFO 23548 --- [XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/8yqws07is8e4k9xk/players/761947628765184032?noReplace=false, client=127.0.0.1, payload={"encodedTrack":null}

```

**Comment by devoxin** [comment]
This appears to be an issue with the [upstream check-in service](https://github.com/walkyst/youtube-checkin) used for account authentication, so not really anything we can fix.

At some point I hope to have a new source manager released for YouTube which removes the need for this check-in service.
Unless the retrieval of account tokens is affecting your ability to play anything, I wouldn't worry too much.

I'll leave the issue open in the meanwhile for visibility

**Comment by Yusuf007R** [comment]
Any updates?, I'm also having this problem. I'm not able to play anything from youtube.

**Comment by devoxin** [comment]
Refer to the comment above yours. If there's any updates they will be posted here. Until then, assume there are none.

**Comment by topi314** [comment]
resolved in https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.5 & https://github.com/lavalink-devs/Lavalink/releases/tag/3.7.12

if you are still hitting this please open an issue [here](https://github.com/lavalink-devs/youtube-source/issues/new) from now on
