### ISSUE TITLE
Querying YT-Playlists returns java.lang.NullPointerException

### ISSUE THREAD

**Issue by pheeef** [lavalink-devs/Lavalink#1037]
## Description
Querying YT-Playlists return java.lang.NullPointerException

## To Reproduce
1. Request any Playlist from Youtube 

## Expected behavior
For the Querry to not throw a java.lang.NullPointerException

## Version info
Apr 08 21:17:10 lavalink001 java[72334]:         Version:        b726aa2b065a7402d41b0482572ee81fbeed2c64-SNAPSHOT
Apr 08 21:17:10 lavalink001 java[72334]:         Build time:     30.03.2024 06:14:43 UTC
Apr 08 21:17:10 lavalink001 java[72334]:         Branch          master
Apr 08 21:17:10 lavalink001 java[72334]:         Commit:         b726aa2
Apr 08 21:17:10 lavalink001 java[72334]:         Commit time:    26.03.2024 18:40:53 UTC
Apr 08 21:17:10 lavalink001 java[72334]:         JVM:            17.0.10
Apr 08 21:17:10 lavalink001 java[72334]:         Lavaplayer      c8a8d821ea5ae92d8e618d67c1a26bf22a9c1e16-SNAPSHOT

Output of `java -version`:
```
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Debian-1deb12u1, mixed mode, sharing)
```

Lavalink Logs:
```
Apr 08 21:18:04 lavalink001 java[72334]: 2024-04-08T21:18:04.194+02:00  INFO 72334 --- [  XNIO-1 task-7] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/c2j4n7qx6s532ksa/players/346147738477527042?noReplace=false, client=192.168.1.48, payload={"voice":{"token":"xxxxxx","endpoint":"frankfurt85.discord.media:443","sessionId":"xxxxxx"}}
Apr 08 21:18:04 lavalink001 java[72334]: 2024-04-08T21:18:04.201+02:00  INFO 72334 --- [  XNIO-1 task-7] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/playlist?list=PLjyPsQmZcDDGjI07zSWSoXUPc46-kWee0"
Apr 08 21:18:04 lavalink001 java[72334]: 2024-04-08T21:18:04.636+02:00  INFO 72334 --- [  XNIO-1 task-7] lavalink.server.player.AudioLoader       : Loaded playlist null
Apr 08 21:18:04 lavalink001 java[72334]: 2024-04-08T21:18:04.637+02:00  WARN 72334 --- [  XNIO-1 task-7] c.s.d.l.p.DefaultAudioPlayerManager      : Load result handler for https://www.youtube.com/playlist?list=PLjyPsQmZcDDGjI07zSWSoXUPc46-kWee0 threw an exception
Apr 08 21:18:04 lavalink001 java[72334]: java.lang.NullPointerException: this.name must not be null
Apr 08 21:18:04 lavalink001 java[72334]:         at lavalink.server.util.UtilKt.toPlaylistInfo(util.kt:79) ~[classes!/:b726aa2b065a7402d41b0482572ee81fbeed2c64-SNAPSHOT]
Apr 08 21:18:04 lavalink001 java[72334]:         at lavalink.server.player.AudioLoader.playlistLoaded(AudioLoader.kt:77) ~[classes!/:b726aa2b065a7402d41b0482572ee81fbeed2c64-SNAPSHOT]
Apr 08 21:18:04 lavalink001 java[72334]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:422) ~[lavaplayer-c8a8d821ea.jar!/:na]
Apr 08 21:18:04 lavalink001 java[72334]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394) ~[lavaplayer-c8a8d821ea.jar!/:na]
Apr 08 21:18:04 lavalink001 java[72334]:         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156) ~[lavaplayer-c8a8d821ea.jar!/:na]
Apr 08 21:18:04 lavalink001 java[72334]:         at com.sedmelluq.discord.lavaplayer.player.AudioPlayerManager.loadItemSync(AudioPlayerManager.java:91) ~[lavaplayer-c8a8d821ea.jar!/:na]
Apr 08 21:18:04 lavalink001 java[72334]:         at lavalink.server.player.AudioLoader.load(AudioLoader.kt:56) ~[classes!/:b726aa2b065a7402d41b0482572ee81fbeed2c64-SNAPSHOT]
Apr 08 21:18:04 lavalink001 java[72334]:         at lavalink.server.player.AudioLoaderRestHandler.loadTracks(AudioLoaderRestHandler.kt:56) ~[classes!/:b726aa2b065a7402d41b0482572ee81fbeed2c64-SNAPSHOT]
Apr 08 21:18:04 lavalink001 java[72334]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Apr 08 21:18:04 lavalink001 java[72334]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
Apr 08 21:18:04 lavalink001 java[72334]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Apr 08 21:18:04 lavalink001 java[72334]:         at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527) ~[jakarta.servlet-api-6.0.0.jar!/:6.0.0]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar!/:6.0.0]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:289) ~[spring-web-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at lavalink.server.io.ResponseHeaderFilter.doFilterInternal(ResponseHeaderFilter.kt:17) ~[classes!/:b726aa2b065a7402d41b0482572ee81fbeed2c64-SNAPSHOT]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.9.jar!/:6.0.9]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
Apr 08 21:18:04 lavalink001 java[72334]:         at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]

```

**Comment by devoxin** [comment]
I don't recognise that Lavaplayer commit hash.

Which jar are you using, and whose Lavaplayer fork?

**Comment by devoxin** [comment]
So after doing some digging, it appears that you're using a Lavalink jar built with this Lavaplayer commit https://github.com/lavalink-devs/lavaplayer/pull/85

This commit wasn't tested and is actually incompatible, as I mentioned in [this comment](https://github.com/lavalink-devs/lavaplayer/pull/85#issuecomment-2028025286)

Grab one of the built jars from GitHub actions as they're tested and confirmed working.
