### ISSUE TITLE
Problematic YouTube player script 

### ISSUE THREAD

**Issue by ghost** [lavalink-devs/Lavalink#1084]
## Description
2024-08-02T20:26:52.527+03:00 ERROR 19804 --- [Lavalink] [back-1-thread-1] d.l.y.cipher.SignatureCipherManager      : Problematic YouTube player script /s/player/d2e656ee/player_ias.vflset/tr_TR/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\TUNA\AppData\Local\Temp\lavaplayer-yt-player-script6338570762728432731.js
2024-08-02T20:26:53.707+03:00 ERROR 19804 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 5035Pnz4KHUNX6Hhk4A2H5

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.1.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[na:na]
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[lavaplayer-2.2.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[lavaplayer-2.2.1.jar!/:na]
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[na:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[na:na]

## Version info
**Client used:** 4.0.7

Output of `java -version`:
```
java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)
```

Lavalink Logs:
Version:        4.0.7
Build time:     08.07.2024 22:14:17 UTC
Branch          HEAD
Commit:         93102f8
Commit time:    08.07.2024 21:49:02 UTC
JVM:            22.0.1
Lavaplayer      2.2.1

**Comment by devoxin** [comment]
This is not applicable to this repository. Additionally, this appears to have already been fixed in `youtube-source` version `1.5.1`.
