### ISSUE TITLE
Error when extracting data EID

### ISSUE THREAD

**Issue by IsmailTosunTnyl** [lavalink-devs/Lavalink#1103]
## Description
Lava player throws an error when trying to play YouTube links. I found a similar issue in the older issues, but it seems to be resolved.
I am writing a bot for Discord. It suddenly stopped working even though I didn't make any changes to the code.
Same issue: https://github.com/lavalink-devs/Lavalink/issues/462 

## To Reproduce
1.Try to play a song on Youtube
2. See error

## Discord bot source codes
[Here](https://github.com/IsmailTosunTnyl/JDA-SpringBoot-Bot) is my source code. As I mentioned, it was working before. In case I broke something, I'm leaving it here. 

## Version info
**LavaPlayer version:** 1.3.77 
**Java version:** 20

Lavalink Logs:
```
2024-09-08T00:47:25.368+03:00 ERROR 26660 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of yJpJCZYTL74

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.77.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.77
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: JetBrains s.r.o.
  java.version: 17.0.10
  java.runtime.version: 17.0.10+1-b1087.23
  java.vm.version: 17.0.10+1-b1087.23
Caused by: java.lang.RuntimeException: Error when extracting data EID: 1428913a-fb9f-48a9-bef3-45f303172a97, mainJson <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:70) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:45) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.77.jar:na]
	... 4 common frames omitted
Caused by: java.lang.RuntimeException: Neither player nor playerResponse in result EID: 7f4c9443-f733-40c9-a65d-10efc2a95da1, json <redacted>
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackJsonData.fromMainResult(YoutubeTrackJsonData.java:53) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:80) ~[lavaplayer-1.3.77.jar:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59) ~[lavaplayer-1.3.77.jar:na]
	... 8 common frames omitted

Track ended, starting next track

```

**Comment by topi314** [comment]
1. This is the lavalink issue tracker, not lavaplayer 
2. Lavaplayer 1.3.77 is literally years old and not a version we published

**Comment by topi314** [comment]
Our maintained fork lives at https://github.com/lavalink-devs/lavaplayer

**Comment by IsmailTosunTnyl** [comment]
Oh okay, thanks for respond
