### ISSUE TITLE
Lavalink 3 is incompatbile with Java version <10

### ISSUE THREAD

**Issue by Emzi0767** [lavalink-devs/Lavalink#138]
When I attempt to run Lavalink using Java 9, I get the following:
```
P:\Mateusz\Developer\Discord\Lavalink>java -jar Lavalink.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: lavalink/server/Launcher has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 53.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
        at java.base/java.net.URLClassLoader.access$100(Unknown Source)
        at java.base/java.net.URLClassLoader$1.run(Unknown Source)
        at java.base/java.net.URLClassLoader$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

Here's my Java version:
```
P:\Mateusz\Developer\Discord\Lavalink>java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

Presumably this means that my Java version (9) is older than required (presumably 10).

Considering that large number of servers running Lavalink will not have anything above Java 8 (since a lot of stuff is based on Debian stable or oldstable, and these go up to Java 8, maybe 9 only), this effectively renders Lavalink 3 useless on most server machines.

**Comment by Emzi0767** [comment]
Nevermind, seems Oracle revised their support plans for all Java versions now.

Way to go...
