### ISSUE TITLE
Exception while sending stats

### ISSUE THREAD

**Issue by DQKev** [lavalink-devs/Lavalink#156]
Running default config.

```
2018-11-01 14:38:06.741 ERROR 16780 --- [pool-2-thread-1] lavalink.server.io.StatsTask             : Exception while sending stats

org.json.JSONException: JSON does not allow non-finite numbers.
        at org.json.JSONObject.testValidity(JSONObject.java:2214) ~[json-20180813.jar!/:na]
        at org.json.JSONObject.put(JSONObject.java:1813) ~[json-20180813.jar!/:na]
        at org.json.JSONObject.put(JSONObject.java:1720) ~[json-20180813.jar!/:na]
        at lavalink.server.io.StatsTask.sendStats(StatsTask.java:93) ~[classes!/:na]
        at lavalink.server.io.StatsTask.run(StatsTask.java:56) ~[classes!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:na]
        at java.base/java.lang.Thread.run(Unknown Source) [na:na]
```

**Comment by freyacodes** [comment]
Never seen this one before.

Some of the stats are based on info about your system, such as CPU usage. Maybe one of these values resulted in an incompatible value such as infinity or NaN. What OS are you running?

**Comment by DQKev** [comment]
Windows 10. But on my Linux Server seems to be gone.

**Comment by freyacodes** [comment]
Fixed in https://github.com/Frederikam/Lavalink/releases/tag/3.1.1.2
