### ISSUE TITLE
Exception while sending stats

### ISSUE THREAD

**Issue by ahmetatli** [lavalink-devs/Lavalink#157]
Default config*
```
2018-11-09 12:12:34.259 ERROR 1061 --- [ool-13-thread-1] oshi.util.ParseUtil                      : Number is too big for a long parsing string '1061 (java) S 1012 1061 1012 34817 1061 4202496 150030 10684 105 2 5748 295 2 6 20 0 195 0 1275 6169038848 132393 18446744073709551615 4194304 4197664 140720428812160 140720428794832 139998015491991 0 0 0 16800975 18446744073709551615 0 0 17 1 0 0 0 0 0 0 0 0 0 0 1061 7164 7164 7164' to long array
2018-11-09 12:12:34.267 ERROR 1061 --- [ool-13-thread-1] lavalink.server.io.StatsTask             : Exception while sending stats

org.json.JSONException: JSON does not allow non-finite numbers.
        at org.json.JSONObject.testValidity(JSONObject.java:2214) ~[json-20180813.jar!/:na]
        at org.json.JSONObject.put(JSONObject.java:1813) ~[json-20180813.jar!/:na]
        at org.json.JSONObject.put(JSONObject.java:1720) ~[json-20180813.jar!/:na]
        at lavalink.server.io.StatsTask.sendStats(StatsTask.java:93) ~[classes!/:na]
        at lavalink.server.io.StatsTask.run(StatsTask.java:56) ~[classes!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by freyacodes** [comment]
Duplicate of https://github.com/Frederikam/Lavalink/issues/156
