### ISSUE TITLE
Exception while handling websocket message

### ISSUE THREAD

**Issue by Tresmos** [lavalink-devs/Lavalink#165]
here is the full error
```
2019-01-17 01:43:02.705 ERROR 19316 --- [   XNIO-2 I/O-1] lavalink.server.io.SocketServer          : Exception while handling websocket message

java.io.EOFException: null
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202) ~[na:na]
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[na:na]
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.decodeTrack(DefaultAudioPlayerManager.java:271) ~[lavaplayer-1.3.10.jar!/:na]
        at lavalink.server.util.Util.toAudioTrack(Util.java:44) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandlers.play(WebSocketHandlers.kt:53) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessageSafe(SocketServer.kt:149) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessage(SocketServer.kt:129) ~[classes!/:na]
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:113) ~[spring-websocket-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42) ~[spring-websocket-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:84) ~[spring-websocket-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81) ~[spring-websocket-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
        at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:286) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:168) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:165) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:602) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:592) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.websockets.jsr.FrameHandler.invokeTextHandler(FrameHandler.java:266) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.websockets.jsr.FrameHandler.onFullTextMessage(FrameHandler.java:317) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.websockets.jsr.FrameHandler.onText(FrameHandler.java:182) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:948) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:929) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

```

**Comment by freyacodes** [comment]
It appears you sent bad track data. What did you send?

**Comment by Tresmos** [comment]
Sorry it was my bad, i fixed it. Thanks anyways

**Comment by Tresmos** [comment]
now i'm getting this error : org.json.JSONException: JSONObject["track"] not a string.

but i'm sure its a string: https://tresmos.is-inside.me/tUBGbkEB.png

**Comment by freyacodes** [comment]
That's not a string. All that in the screenshot is collectively an object.

This issue tracker is meant for reporting bugs. Please use our discord channel for general support.
