### ISSUE TITLE
1000 Webscket Closed issues

### ISSUE THREAD

**Issue by Diniboy1123** [lavalink-devs/Lavalink#192]
I use Lavalink in production and it worked fine but since the last updates, I often get:

 `Connection closed due to [1000 HEARTBEAT_TIMEOUT] . This could indicate an issue with the magma library or your usage of it. Please get in touch. https://github.com/napstr/Magma/issues`

```
    at space.npstr.magma.connections.AudioWebSocket.handleWebSocketClosed(AudioWebSocket.java:263)
    at space.npstr.magma.connections.AudioWebSocket.hookOnNext(AudioWebSocket.java:169)
    at space.npstr.magma.connections.AudioWebSocket.hookOnNext(AudioWebSocket.java:74)
    at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:158)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
```

Happens randomly when I try to play something. Bot joins and then immediately leaves. One or two more tries and the playback of the same song starts working fine. What can cause this?

**Comment by schnapster** [comment]
The title says 1006, the log says 1000 - which is it?

We've seen a few reports of these in the past days, not sure about the caused just yet. Do you have a reliable way to reproduce the issue? Does it still happen after restarting the LL node?

**Comment by Diniboy1123** [comment]
You are totally right, 1006 is a bit different. 😊  Should be ok now.

It happens a lot on my US nodes from different providers. Happens after complete server restart also. If needed I can provide a lavalink node access where I experience the issue at least once from 10 requests.

**Comment by schnapster** [comment]
This requires a bit more context to hunt down. Could you please enable trace logs and MDCs as described here: https://github.com/napstr/Magma#debugging and provide a full log file of such an incident?

**Comment by schnapster** [comment]
Closing due to inactivity.
