### ISSUE TITLE
Stats sending issues/Json issues on Mac

### ISSUE THREAD

**Issue by aikaterna** [lavalink-devs/Lavalink#206]
I realize that Mac may or may not be officially supported any more, but since my project is making Lavalink jars with every native we can build (Mac, 32-bit systems, ARM, etc) I am hoping there could be some work done to resolve this issue.

Using any recent version of Lavalink, master branch or the remove-oshi branch will cause a traceback when attempting to send stats. Everything works as expected, but we have a traceback in the console, so some users have gotten concerned about the errors spamming the log.

I have also reported this issue in #191 and didn't realize it was affecting all builds until today.

I have also tried using different versions of oshi with custom built jars based on build 796, with the same issue. Tried oshi 3.8.1, 3.13.0, and 3.13.2.

Lavalink version used: Have tried many, build numbers 808, 799, 796, 779 (remove-oshi branch), usually using 3.2.0.3 or 3.2.1 jars

Client used:
Red-Lavalink

```
2019-07-10 08:03:46.421 ERROR 31582 --- [pool-2-thread-1] lavalink.server.io.StatsTask             : Exception while sending stats

org.json.JSONException: JSON does not allow non-finite numbers.
	at org.json.JSONObject.testValidity(JSONObject.java:2214) ~[json-20180813.jar!/:na]
	at org.json.JSONObject.put(JSONObject.java:1813) ~[json-20180813.jar!/:na]
	at org.json.JSONObject.put(JSONObject.java:1720) ~[json-20180813.jar!/:na]
	at lavalink.server.io.StatsTask.sendStats(StatsTask.java:91) ~[classes!/:na]
	at lavalink.server.io.StatsTask.run(StatsTask.java:53) ~[classes!/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

**Comment by schnapster** [comment]
There are several JVMs that work fine with the oshi-free branch, see https://github.com/Frederikam/Lavalink/pull/191#issuecomment-498454100
Using one of those for development should be good enough. I personally don't think it makes sense to support the Mac (or Windows platform) for anything else then development.

**Comment by aikaterna** [comment]
Closing as this particular issue has been solved for a while. While there are still some very rare oshi-related issues still with stats, Intel Macs nor any other device I know of have this issue currently.
