### ISSUE TITLE
NoClassDefFoundError: io/undertow/servlet/core/DeploymentManagerImpl

### ISSUE THREAD

**Issue by Victor2106** [lavalink-devs/Lavalink#213]
## Description
At times, Lavalink may display this error, and stop my Discord bot.

## Version info
**Client used: 3.2.1**

Output of `java -jar Lavalink.jar --version`:
```
     /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        1033d3481c70d1552bd66cd0ed5a70b8b4909b62-SNAPSHOT
        Build:          808
        Build time:     19.06.2019 14:00:24 CEST
        Branch          master
        Commit:         1033d34
        Commit time:    19.06.2019 13:58:15 CEST
        JVM:            1.8.0_222
        Lavaplayer      1.3.17

```

Lavalink logs:
```
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: io/undertow/servlet/core/DeploymentManagerImpl$3
	at io.undertow.servlet.core.DeploymentManagerImpl.stop(DeploymentManagerImpl.java:589)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServer.stop(UndertowServletWebServer.java:306)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.stopAndReleaseWebServer(ServletWebServerApplicationContext.java:309)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onClose(ServletWebServerApplicationContext.java:171)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1023)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:937)
Caused by: java.lang.ClassNotFoundException: io.undertow.servlet.core.DeploymentManagerImpl$3
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

**Comment by freyacodes** [comment]
I don't know exactly why Spring Boot is trying to load that class, but I can see Lavalink is already shutting down. The exception itself is likely harmless.

[AbstractApplicationContext#doClose()](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/support/AbstractApplicationContext.html#onClose--)

You did not provide a log, only a stack trace.

**Comment by schnapster** [comment]
Fixed by https://github.com/Frederikam/Lavalink/commit/aa16e6b34d9de05aa303a6cdbea18a7fccacb09f
