### ISSUE TITLE
VoiceServerUpdateInterceptor throws NPE

### ISSUE THREAD

**Issue by schnapster** [lavalink-devs/Lavalink#22]
Link#getCurrentSocket() may return null resulting in this NPE in the VoiceServerUpdateInterceptor:

```
java.lang.NullPointerException: null
    at lavalink.client.io.VoiceServerUpdateInterceptor.handleInternally(VoiceServerUpdateInterceptor.java:63)
    at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
    at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:1001)
    at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:684)
    at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1052)
    at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
    at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
    at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
    at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
    at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
    at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
    at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by freyacodes** [comment]
https://sentry.davinci.sh/fredboat/fredboat/issues/5038/

**Comment by freyacodes** [comment]
I see the issue. Broken in https://github.com/Frederikam/Lavalink/pull/18 

Blame me.

**Comment by freyacodes** [comment]
And this is why you have JSR annotations
