### ISSUE TITLE
Something broke when playing the track.

### ISSUE THREAD

**Issue by corpnewt** [lavalink-devs/Lavalink#237]
## Description
When playing a youtube url directly, it fails immediately - when searching, it first loads a track, then fails.  Appears to be a change in the way youtube handles resolving links.

## Version info
**Client used:**

[My bot](https://github.com/corpnewt/CorpBot.py/blob/redis/Cogs/Music.py) is currently using [wavelink](https://github.com/PythonistaGuild/Wavelink) and runs via Rapptz's [discord.py](https://github.com/Rapptz/discord.py) on Windows 10 Pro 1903 and 1909.

Output of `java -jar Lavalink.jar --version`:
```
Version:        f2b8af5d342214f8f7090e6587886567fa9b59e9-SNAPSHOT
Build:          941
Build time:     17.11.2019 12:47:41 UTC
Branch          master
Commit:         f2b8af5
Commit time:    17.11.2019 12:45:56 UTC
JVM:            1.8.0_231
Lavaplayer      1.3.22
```

Logs:
```
2019-11-19 20:22:16.234  INFO 6972 --- [           main] lavalink.server.Launcher                 :

[32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[0m    =========================================[32m/_/_/_/[0m

        Version:        f2b8af5d342214f8f7090e6587886567fa9b59e9-SNAPSHOT
        Build:          941
        Build time:     17.11.2019 12:47:41 UTC
        Branch          master
        Commit:         f2b8af5
        Commit time:    17.11.2019 12:45:56 UTC
        JVM:            1.8.0_231
        Lavaplayer      1.3.22

2019-11-19 20:22:16.299  INFO 6972 --- [           main] lavalink.server.Launcher                 : Starting Launcher on Corp-WIN10 with PID 6972 (C:\Users\CorpNewt\Desktop\cb-redis\Lavalink\Lavalink.jar started by CorpNewt in C:\Users\CorpNewt\Desktop\cb-redis\Lavalink)
2019-11-19 20:22:16.299  INFO 6972 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2019-11-19 20:22:16.418  WARN 6972 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2019-11-19 20:22:17.290  WARN 6972 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2019-11-19 20:22:17.309  INFO 6972 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2019-11-19 20:22:17.309  INFO 6972 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 978 ms
2019-11-19 20:22:17.367  WARN 6972 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2019-11-19 20:22:17.372  INFO 6972 --- [           main] l.s.c.AudioSendFactoryConfiguration      : OS: Windows 10, Arch: amd64
2019-11-19 20:22:17.372  INFO 6972 --- [           main] l.s.c.AudioSendFactoryConfiguration      : JDA-NAS supported system detected. Enabled native audio sending.
2019-11-19 20:22:17.373  INFO 6972 --- [           main] l.s.c.AudioSendFactoryConfiguration      : Setting buffer to 400ms
2019-11-19 20:22:17.374  INFO 6972 --- [           main] l.s.c.AudioSendFactoryConfiguration      : Setting playlist load limit to 6
2019-11-19 20:22:18.031  INFO 6972 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2019-11-19 20:22:18.261  INFO 6972 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-11-19 20:22:18.468  INFO 6972 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2019-11-19 20:22:18.475  INFO 6972 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2019-11-19 20:22:18.535  INFO 6972 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2019-11-19 20:22:18.537  INFO 6972 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.622 seconds (JVM running for 3.0)
2019-11-19 20:22:49.579  INFO 6972 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-11-19 20:22:49.580  INFO 6972 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-11-19 20:22:49.585  INFO 6972 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2019-11-19 20:22:49.605  INFO 6972 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:57186
2019-11-19 20:22:49.661  INFO 6972 --- [  XNIO-1 task-1] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2019-11-19 20:22:49.719  INFO 6972 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:57186
2019-11-19 20:23:30.458  INFO 6972 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "330810953740582912", "sessionId": "1803d494c79efd59ec8e5bea7c851ffa", "event": {"token": "8b63849c5281b415", "guild_id": "330810953740582912", "endpoint": "us-central82.discord.media:80"}}
2019-11-19 20:23:32.719  INFO 6972 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2019-11-19 20:23:33.800  INFO 6972 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: something
2019-11-19 20:23:33.824  INFO 6972 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "330810953740582912"}
2019-11-19 20:23:33.829  INFO 6972 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op": "volume", "guildId": "330810953740582912", "volume": 50.0}
2019-11-19 20:23:33.967  INFO 6972 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "330810953740582912", "track": "QAAAfAIAF1RoZSBCZWF0bGVzIC0gU29tZXRoaW5nAAtUaGUgQmVhdGxlcwAAAAAAAt5gAAtVZWxEcloxYUZlWQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVVlbERyWjFhRmVZAAd5b3V0dWJlAAAAAAAAAAA=", "noReplace": false}
2019-11-19 20:23:34.301 ERROR 6972 --- [back-5-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of UelDrZ1aFeY

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) [lavaplayer-1.3.22.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_231]
Caused by: java.io.IOException: Invalid status code for video info response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.determineFailureReason(YoutubeAudioSourceManager.java:401) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:390) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.getTrackInfo(YoutubeAudioTrack.java:118) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:96) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:63) ~[lavaplayer-1.3.22.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90) ~[lavaplayer-1.3.22.jar!/:na]
        ... 4 common frames omitted

2019-11-19 20:23:34.314  INFO 6972 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "330810953740582912"}
2019-11-19 20:23:34.452  INFO 6972 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "330810953740582912"}
```

Please let me know if you need any other info.

-CorpNewt

---

I tested a direct audio file upload as well as a soundcloud link - and I get the same response between two different machines.  The individual files load/download on both machines though.  I'm wondering if there's something odd on my end, but I'm not sure how to debug it.

-CorpNewt

**Comment by knight-ryu12** [comment]
429- Too many requests.
You maybe hit with YT's ratelimit.

**Comment by corpnewt** [comment]
Without sounding too ignorant - do I just not make any youtube requests for awhile and hope for the best?

Also - I'm able to watch all the same videos in a web browser on the same machine where Lavalink is running without issue.  Worth noting that mp3's or otherwise that are linked directly (uploaded to discord, then the direct url passed) fail to work with the same error.

I appreciate the response - and hopefully this is something fixable, whether on my side, or otherwise.  

Thank you,

-CorpNewt

**Comment by corpnewt** [comment]
It appears that the issue was related to rate limiting.  Disabling my music commands for 1-2 days seems to have fixed it for the time being.

I do wonder if [this commit](https://github.com/sedmelluq/lavaplayer/commit/e7aabb79e750df4b9d279d3a6c4cec0b803eb5ea) and newer of lavaplayer would be helpful in preventing similar issues?  I'm not terribly familiar with java, but by the name, it sounds like it may be implementing some workaround for rate limiting.

As my issue appears to not be a direct bug with Lavalink, I'll close it though.

Thanks again,

-CorpNewt
