### ISSUE TITLE
SoundCloud sets "This url does not appear to be a playable track."

### ISSUE THREAD

**Issue by xenorio** [lavalink-devs/Lavalink#243]
## Description
Whenever i'm trying to play any SoundCloud set, i'm getting "This url does not appear to be a playable track." in console. It has worked before, so this can't be faulty code. Example URL that isn't working: https://soundcloud.com/uriyle8cb7jg/sets/nightvale

## Version info
**Client used:** discord.js-lavalink

Output of `java -jar Lavalink.jar --version`:
```
Version:        80834a401900e59e61639c3a452934910f3f279d-SNAPSHOT
        Build:          831
        Build time:     31.07.2019 13:28:26 CEST
        Branch          master
        Commit:         80834a4
        Commit time:    31.07.2019 13:26:40 CEST
        JVM:            11.0.4
        Lavaplayer      1.3.19

```

## Log
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This url does not appear to be a playable track.
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadPageConfigJson(SoundCloudAudioSourceManager.java:327) ~[lavaplayer-1.3.19.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromSet(SoundCloudAudioSourceManager.java:356) ~[lavaplayer-1.3.19.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsPlaylist(SoundCloudAudioSourceManager.java:281) ~[lavaplayer-1.3.19.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:122) ~[lavaplayer-1.3.19.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.19.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.19.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.19.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```

**Comment by freyacodes** [comment]
Sorry for the late reply. This is a Lavaplayer issue.

Please see https://github.com/sedmelluq/lavaplayer
