### ISSUE TITLE
Won't Play

### ISSUE THREAD

**Issue by GavynStanley** [lavalink-devs/Lavalink#245]
## Description
Whenever i try to play music i get the following error:
`Command raised an exception: AttributeError: 'NoneType' object has no attribute 'node'`

## Version info
**Client used: Ubuntu 19.04**

Output of `java -jar Lavalink.jar --version`:
```

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        3.2.1.1
        Build:          828
        Build time:     31.07.2019 11:02:24 CEST
        Branch          master
        Commit:         d9c9aa0
        Commit time:    31.07.2019 10:59:59 CEST
        JVM:            11.0.5
        Lavaplayer      1.3.19

```

```
2019-12-22 22:52:43.240  INFO 1715 --- [main] lavalink.server.Launcher                 : 

[32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[0m    =========================================[32m/_/_/_/[0m

	Version:        3.2.1.1
	Build:          828
	Build time:     31.07.2019 11:02:24 CEST
	Branch          master
	Commit:         d9c9aa0
	Commit time:    31.07.2019 10:59:59 CEST
	JVM:            11.0.5
	Lavaplayer      1.3.19

2019-12-22 22:52:43.449  INFO 1715 --- [main] o.s.boot.SpringApplication               : [32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[39m    =========================================[32m/_/_/_/

[32m    :: Lavalink    :: [39m      
[32m    :: Spring Boot :: [39m       (v2.0.4.RELEASE)


2019-12-22 22:52:43.784  INFO 1715 --- [main] lavalink.server.Launcher                 : Starting Launcher with PID 1715 (/root/Lavalink-3.3/LavalinkServer/Lavalink.jar started by root in /root/Lavalink-3.3/LavalinkServer)
2019-12-22 22:52:43.786  INFO 1715 --- [main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2019-12-22 22:52:43.940  INFO 1715 --- [main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@27c6e487: startup date [Sun Dec 22 22:52:43 UTC 2019]; root of context hierarchy
2019-12-22 22:52:44.019  WARN 1715 --- [background-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2019-12-22 22:52:46.794  INFO 1715 --- [main] org.xnio                                 : XNIO version 3.3.8.Final
2019-12-22 22:52:46.830  INFO 1715 --- [main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2019-12-22 22:52:47.011  WARN 1715 --- [main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2019-12-22 22:52:47.012  WARN 1715 --- [main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2019-12-22 22:52:47.051  INFO 1715 --- [main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2019-12-22 22:52:47.052  INFO 1715 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3112 ms
2019-12-22 22:52:47.208  INFO 1715 --- [main] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2019-12-22 22:52:47.222  INFO 1715 --- [main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2019-12-22 22:52:47.224  INFO 1715 --- [main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2019-12-22 22:52:47.227  INFO 1715 --- [main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2019-12-22 22:52:47.227  INFO 1715 --- [main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2019-12-22 22:52:47.228  INFO 1715 --- [main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'responseHeaderFilter' to: [/*]
2019-12-22 22:52:47.359  WARN 1715 --- [main] l.server.config.SentryConfiguration      : Turning off sentry
2019-12-22 22:52:47.380  INFO 1715 --- [main] l.s.c.AudioSendFactoryConfiguration      : OS: Linux, Arch: amd64
2019-12-22 22:52:47.381  INFO 1715 --- [main] l.s.c.AudioSendFactoryConfiguration      : JDA-NAS supported system detected. Enabled native audio sending.
2019-12-22 22:52:47.382  INFO 1715 --- [main] l.s.c.AudioSendFactoryConfiguration      : Setting buffer to 400ms
2019-12-22 22:52:47.382  INFO 1715 --- [main] l.s.c.AudioSendFactoryConfiguration      : Setting playlist load limit to 6
2019-12-22 22:52:48.496  INFO 1715 --- [main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2019-12-22 22:52:48.753  INFO 1715 --- [main] o.s.w.s.s.s.WebSocketHandlerMapping      : Root mapping to handler of type [class org.springframework.web.socket.server.support.WebSocketHttpRequestHandler]
2019-12-22 22:52:49.266  INFO 1715 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-22 22:52:49.871  INFO 1715 --- [main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@27c6e487: startup date [Sun Dec 22 22:52:43 UTC 2019]; root of context hierarchy
2019-12-22 22:52:50.094  INFO 1715 --- [main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/loadtracks],methods=[GET],produces=[application/json]}" onto public java.util.concurrent.CompletionStage<org.springframework.http.ResponseEntity<java.lang.String>> lavalink.server.player.AudioLoaderRestHandler.getLoadTracks(javax.servlet.http.HttpServletRequest,java.lang.String)
2019-12-22 22:52:50.098  INFO 1715 --- [main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/decodetrack],methods=[GET],produces=[application/json]}" onto public org.springframework.http.ResponseEntity<java.lang.String> lavalink.server.player.AudioLoaderRestHandler.getDecodeTrack(javax.servlet.http.HttpServletRequest,java.lang.String) throws java.io.IOException
2019-12-22 22:52:50.099  INFO 1715 --- [main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/decodetracks],methods=[POST],consumes=[application/json],produces=[application/json]}" onto public org.springframework.http.ResponseEntity<java.lang.String> lavalink.server.player.AudioLoaderRestHandler.postDecodeTracks(javax.servlet.http.HttpServletRequest,java.lang.String) throws java.io.IOException
2019-12-22 22:52:50.101  INFO 1715 --- [main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/version],methods=[GET]}" onto public java.lang.String lavalink.server.info.InfoRestHandler.version()
2019-12-22 22:52:50.108  INFO 1715 --- [main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2019-12-22 22:52:50.109  INFO 1715 --- [main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2019-12-22 22:52:50.168  INFO 1715 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-22 22:52:50.170  INFO 1715 --- [main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2019-12-22 22:52:50.589  INFO 1715 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2019-12-22 22:52:50.603  INFO 1715 --- [main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147483647
2019-12-22 22:52:50.753  INFO 1715 --- [main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 6666 (http) with context path ''
2019-12-22 22:52:50.768  INFO 1715 --- [main] lavalink.server.Launcher                 : Started Launcher in 8.876 seconds (JVM running for 10.177)
2019-12-22 22:52:55.171  INFO 1715 --- [XNIO-2 task-1] io.undertow.servlet                      : Initializing Spring FrameworkServlet 'dispatcherServlet'
2019-12-22 22:52:55.173  INFO 1715 --- [XNIO-2 task-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2019-12-22 22:52:55.204  INFO 1715 --- [XNIO-2 task-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 31 ms
2019-12-22 22:52:55.239  INFO 1715 --- [XNIO-2 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:60362
2019-12-22 22:52:55.337  INFO 1715 --- [XNIO-2 task-1] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2019-12-22 22:52:55.487  INFO 1715 --- [XNIO-2 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:60362
2019-12-22 22:53:32.094  INFO 1715 --- [XNIO-2 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:60362 -- CloseStatus[code=1006, reason=]
2019-12-22 22:53:32.111  INFO 1715 --- [XNIO-2 I/O-1] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2019-12-22 22:53:32.120  INFO 1715 --- [XNIO-2 I/O-1] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring disabled.
2019-12-22 22:53:33.906  INFO 1715 --- [XNIO-2 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:60390
2019-12-22 22:53:33.918  INFO 1715 --- [XNIO-2 task-2] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2019-12-22 22:53:33.928  INFO 1715 --- [XNIO-2 task-2] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:60390
2019-12-22 22:53:33.968  INFO 1715 --- [XNIO-2 I/O-1] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "default-node", "timeout": 60}
2019-12-22 22:57:04.179  INFO 1715 --- [Thread-1] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@27c6e487: startup date [Sun Dec 22 22:52:43 UTC 2019]; root of context hierarchy
2019-12-22 22:57:04.195  INFO 1715 --- [Thread-1] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2019-12-22 22:57:04.199  INFO 1715 --- [Thread-1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2019-12-22 22:57:04.205  INFO 1715 --- [Thread-1] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring disabled.
2019-12-22 22:57:04.215  INFO 1715 --- [Thread-1] io.undertow.servlet                      : Destroying Spring FrameworkServlet 'dispatcherServlet'
2019-12-22 22:57:04.237 ERROR 1715 --- [XNIO-2 I/O-1] org.xnio.listener                        : XNIO001007: A channel event listener threw an exception

java.util.concurrent.RejectedExecutionException: XNIO007007: Thread is terminating
	at org.xnio.nio.WorkerThread.execute(WorkerThread.java:590) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:396) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
	at io.undertow.websockets.jsr.UndertowSession$3.handleEvent(UndertowSession.java:388) ~[undertow-websockets-jsr-1.4.25.Final.jar!/:1.4.25.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1061) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:975) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.terminated(WriteReadyHandler.java:70) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.writeTerminated(NioSocketConduit.java:234) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.terminateWrites(NioSocketConduit.java:223) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.truncateWrites(NioSocketConduit.java:228) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.conduits.IdleTimeoutConduit.truncateWrites(IdleTimeoutConduit.java:387) ~[undertow-core-2.0.14.Final.jar!/:2.0.14.Final]
	at org.xnio.conduits.ConduitStreamSinkChannel.close(ConduitStreamSinkChannel.java:186) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.IoUtils.safeClose(IoUtils.java:134) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.forceTermination(WriteReadyHandler.java:57) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.forceTermination(NioSocketConduit.java:107) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:494) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

```

**Comment by freyacodes** [comment]
This is not a Lavalink error. Contact the maintainers of whatever library you are using. 

Note: Ubuntu is a Linux distro, not a Lavalink client.
