### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by Driics** [lavalink-devs/Lavalink#249]
## Description

When starting Lavalink displays an error in the console and everything ends

## Version info
**Client used:**

Output of `java -jar Lavalink.jar --version`:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at lavalink.server.Launcher.getVersionInfo(Launcher.kt:50)
        at lavalink.server.Launcher.main(Launcher.kt:108)
```

Startup Log:
```
2020-01-27 13:23:27.235  WARN 5288 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-01-27 13:23:27.282 ERROR 5288 --- [           main] lavalink.server.Launcher                 : Application failed

java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_241]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_241]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[Lavalink.jar:na]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_241]
        at lavalink.server.Launcher.getVersionInfo(Launcher.kt:50) [classes!/:na]
        at lavalink.server.Launcher.getVersionInfo$default(Launcher.kt:49) [classes!/:na]
        at lavalink.server.Launcher$main$1.onApplicationEvent(Launcher.kt:118) ~[classes!/:na]
        at lavalink.server.Launcher$main$1.onApplicationEvent(Launcher.kt:43) ~[classes!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at lavalink.server.Launcher.main(Launcher.kt:127) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [Lavalink.jar:na]

2020-01-27 13:23:27.292 ERROR 5288 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_241]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_241]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[Lavalink.jar:na]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_241]
        at lavalink.server.Launcher.getVersionInfo(Launcher.kt:50) [classes!/:na]
        at lavalink.server.Launcher.getVersionInfo$default(Launcher.kt:49) [classes!/:na]
        at lavalink.server.Launcher$main$1.onApplicationEvent(Launcher.kt:118) ~[classes!/:na]
        at lavalink.server.Launcher$main$1.onApplicationEvent(Launcher.kt:43) ~[classes!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at lavalink.server.Launcher.main(Launcher.kt:127) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [Lavalink.jar:na]

```

**Comment by schnapster** [comment]
You are running and old Java version. [Lavalink v3.3 requires at least Java 11.](https://github.com/Frederikam/Lavalink/releases/tag/3.3)
