### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by nayvcake** [lavalink-devs/Lavalink#266]
## Description
When trying to play a song or playlist on the bot it gives this error

## Version info
**Client used:**

Output of `java -jar Lavalink.jar --3.3.1`:
Java: 
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode, sharing)
```
 java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1585915716860/libudpqueue.so: /tmp/lava-jni-natives/1585915716860/libudpqueue.so: failed to map segment from shared object: Operation not permitted
0|lavalink  |   at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[na:na]
0|lavalink  |   at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[na:na]
0|lavalink  |   at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[na:na]
0|lavalink  |   at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[na:na]
0|lavalink  |   at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) ~[na:na]
0|lavalink  |   at java.base/java.lang.Runtime.load0(Runtime.java:767) ~[na:na]
0|lavalink  |   at java.base/java.lang.System.load(System.java:1834) ~[na:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77) ~[lavaplayer-common-1.0.6.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManagerLibrary.getInstance(UdpQueueManagerLibrary.java:13) ~[udp-queue-1.0.8.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManager.<init>(UdpQueueManager.java:27) ~[udp-queue-1.0.8.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.initialiseQueueManager(NativeAudioSendFactory.java:40) ~[jda-nas-1.1.0.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.addInstance(NativeAudioSendFactory.java:69) ~[jda-nas-1.1.0.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendSystem.start(NativeAudioSendSystem.java:23) ~[jda-nas-1.1.0.jar!/:na]
0|lavalink  |   at com.github.shredder121.asyncaudio.jda.AsyncAudioSendSystemWrapper.start(AsyncAudioSendSystemWrapper.java:37) ~[jda-async-packetprovider-1.3.2-MINN.jar!/:na]
0|lavalink  |   at space.npstr.magma.impl.connections.AudioConnection.startSendSystemIfReady(AudioConnection.java:320) ~[impl-0.12.5.jar!/:na]
0|lavalink  |   at space.npstr.magma.impl.connections.AudioConnection.hookOnNext(AudioConnection.java:211) ~[impl-0.12.5.jar!/:na]
0|lavalink  |   at space.npstr.magma.impl.connections.AudioConnection.hookOnNext(AudioConnection.java:61) ~[impl-0.12.5.jar!/:na]
0|lavalink  |   at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:158) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|lavalink  |   at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|lavalink  |   at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|lavalink  |   at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|lavalink  |   at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|lavalink  |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
0|lavalink  |   at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
0|lavalink  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
0|lavalink  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
0|lavalink  |   at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
0|lavalink  | 2020-04-03 09:09:26.096  WARN 6693 --- [         japp-3] lavalink.server.player.EventEmitter      : Tomorrowland - United Through Music got stuck!Threshold surpassed: 10000
0|lavalink  | 2020-04-03 09:09:32.572 ERROR 6693 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of hE_apx2B0uQ
0|lavalink  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
0|lavalink  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
0|lavalink  |   at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
0|lavalink  | Caused by: java.lang.RuntimeException: java.net.UnknownHostException: r6---sn-n4v7sn76.googlevideo.com: Name or service not known
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:57) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   ... 4 common frames omitted
0|lavalink  | Caused by: java.net.UnknownHostException: r6---sn-n4v7sn76.googlevideo.com: Name or service not known
0|lavalink  |   at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
0|lavalink  |   at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[na:na]
0|lavalink  |   at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[na:na]
0|lavalink  |   at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[na:na]
0|lavalink  |   at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[na:na]
0|lavalink  |   at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[na:na]
0|lavalink  |   at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[na:na]
0|lavalink  |   at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.resolveAddresses(ExtendedConnectionOperator.java:138) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connect(ExtendedConnectionOperator.java:69) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar!/:4.5.10]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:113) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-1.3.38.jar!/:na]
0|lavalink  |   ... 9 common frames omitted
```

What can this be ?

**Comment by freyacodes** [comment]
Looks like a permission problem with your `/tmp` directory. You could track down the problem, or you can use a different directory like so:

`java -jar -Djava.io.tmpdir="./tmp" Lavalink.jar`

PS: You're meant to do literally `--version` not `--3.3.1`.

**Comment by nayvcake** [comment]
```

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-04-03 10:11:49.935 ERROR 13846 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to ./tmp
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at lavalink.server.Launcher.main(Launcher.kt:127) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[Lavalink.jar:na]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to ./tmp
        at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:180) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getCanonicalDocumentRoot(UndertowServletWebServerFactory.java:395) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getDocumentRootResourceManager(UndertowServletWebServerFactory.java:360) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createDeploymentManager(UndertowServletWebServerFactory.java:271) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:213) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        ... 14 common frames omitted
Caused by: java.io.IOException: No such file or directory
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:na]
        at java.base/java.io.File.createTempFile(File.java:2092) ~[na:na]
        at java.base/java.io.File.createTempFile(File.java:2138) ~[na:na]
        at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:172) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        ... 20 common frames omitted
```

Another error, When running  **`java -jar -Djava.io.tmpdir="./tmp" Lavalink.jar`**

**Comment by nayvcake** [comment]
Ok, I managed to resolve this issue, now there's another error
 What can this be ? `Failed to discover external udp address`

**Comment by freyacodes** [comment]
Check your firewall settings

**Comment by nayvcake** [comment]
Only problem is .. half of the system is on the WHM panel I don't know much about it

**Comment by nayvcake** [comment]
Problem resolved, thank you
