### ISSUE TITLE
YouTube: Connection timed out

### ISSUE THREAD

**Issue by Axiol** [lavalink-devs/Lavalink#274]
## Description
Sometimes when I try to play something though a Red bot, there's a bit of time out and then I get an error where the bot returns this

```
Lavalink API returned an unsupported response, Please report it.Query: http://localhost:2333/loadtracks?identifier=https%3A//www.youtube.com/watch%3Fv%3DyzC4hFK5P3g{'timestamp': '2020-04-18T21:34:55.691+0000', 'status': 503, 'error': 'Service Unavailable', 'message': 'Service Unavailable', 'path': '/loadtracks', 'query': 'https://www.youtube.com/watch?v=yzC4hFK5P3g', 'encodedquery': 'http://localhost:2333/loadtracks?identifier=https%3A//www.youtube.com/watch%3Fv%3DyzC4hFK5P3g', 'loadType': <LoadType.LOAD_FAILED: 'LOAD_FAILED'>}Query: http://localhost:2333/loadtracks?identifier=https%3A//www.youtube.com/watch%3Fv%3DyzC4hFK5P3g{'timestamp': '2020-04-18T21:40:43.726+0000', 'status': 503, 'error': 'Service Unavailable', 'message': 'Service Unavailable', 'path': '/loadtracks', 'query': 'https://www.youtube.com/watch?v=yzC4hFK5P3g', 'encodedquery': 'http://localhost:2333/loadtracks?identifier=https%3A//www.youtube.com/watch%3Fv%3DyzC4hFK5P3g', 'loadType': <LoadType.LOAD_FAILED: 'LOAD_FAILED'>}
```

## Version info
**Client used:**

Output of `java -jar Lavalink.jar --version`:
```
Version:        e270ec688cbad900d9de292a9e615f15c48a9a82-SNAPSHOT
Build:          986
Build time:     23.03.2020 20:28:53 UTC
Branch          BullyJava11
Commit:         e270ec6
Commit time:    23.03.2020 19:56:15 UTC
JVM:            13.0.2
Lavaplayer      1.3.38
```

```
2020-04-18 23:23:04.246  INFO 82 --- [main] lavalink.server.Launcher                 : Starting Launcher on 8cdd9ea71b96 with PID 82 (/data/cogs/Audio/Lavalink.jar started by docker in /data/cogs/Audio)
2020-04-18 23:23:04.252  INFO 82 --- [main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2020-04-18 23:23:05.327  WARN 82 --- [background-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-04-18 23:23:14.400  WARN 82 --- [main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2020-04-18 23:23:14.602  INFO 82 --- [main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2020-04-18 23:23:14.603  INFO 82 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 9978 ms
2020-04-18 23:23:17.873  WARN 82 --- [main] l.server.config.SentryConfiguration      : Turning off sentry
2020-04-18 23:23:17.899  INFO 82 --- [main] l.s.c.AudioSendFactoryConfiguration      : OS: Linux, Arch: arm
2020-04-18 23:23:17.900  WARN 82 --- [main] l.s.c.AudioSendFactoryConfiguration      : This system and architecture appears to not support native audio sending! GC pauses may cause your bot to stutter during playback.
2020-04-18 23:23:19.974  INFO 82 --- [main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2020-04-18 23:23:22.944  INFO 82 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-04-18 23:23:25.942  INFO 82 --- [main] org.xnio                                 : XNIO version 3.3.8.Final
2020-04-18 23:23:26.000  INFO 82 --- [main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2020-04-18 23:23:26.350  INFO 82 --- [main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2020-04-18 23:23:26.377  INFO 82 --- [main] lavalink.server.Launcher                 : Started Launcher in 26.469 seconds (JVM running for 30.917)
2020-04-18 23:23:26.695  INFO 82 --- [XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-04-18 23:23:26.698  INFO 82 --- [XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-04-18 23:23:26.754  INFO 82 --- [XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 54 ms
2020-04-18 23:23:26.910  INFO 82 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:51882
2020-04-18 23:23:26.910  INFO 82 --- [XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:51880
2020-04-18 23:23:28.030  INFO 82 --- [XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:51882
2020-04-18 23:23:28.032  INFO 82 --- [XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:51880
2020-04-18 23:25:19.976  WARN 82 --- [lava-daemon-pool-manager-3-thread-1] c.s.d.l.tools.GarbageCollectionMonitor   : Suspicious GC results for the last 2 minutes: [Bucket 0 = 18] [Bucket 20 = 1] [Bucket 50 = 0] [Bucket 200 = 1] [Bucket 500 = 0] [Bucket 2000 = 0]
2020-04-18 23:29:00.456  INFO 82 --- [XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-04-18 23:29:00.617  INFO 82 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "701105975498637364", "sessionId": "a79efcecb749a2f8207b8b8d5b4ce3fb", "event": {"token": "bbdfd78161bb6317", "guild_id": "701105975498637364", "endpoint": "eu-west599.discord.media:80"}}
2020-04-18 23:29:01.287  INFO 82 --- [parallel-2] com.jcabi.manifests.Manifests            : 65 attributes loaded from 81 stream(s) in 423ms, 65 saved, 1177 ignored: ["Archiver-Version", "Automatic-Module-Name", "Bnd-LastModified", "Build-Jdk", "Build-Jdk-Spec", "Built-By", "Bundle-Activator", "Bundle-Description", "Bundle-DocURL", "Bundle-License", "Bundle-ManifestVersion", "Bundle-Name", "Bundle-RequiredExecutionEnvironment", "Bundle-SymbolicName", "Bundle-Vendor", "Bundle-Version", "Created-By", "Export-Package", "Extension-Name", "Implementation-Build", "Implementation-Build-Date", "Implementation-Title", "Implementation-URL", "Implementation-Vendor", "Implementation-Vendor-Id", "Implementation-Version", "Import-Package", "Include-Resource", "JCabi-Build", "JCabi-Date", "JCabi-Version", "Jar-Name", "Jar-Version", "Java-Vendor", "Java-Version", "Kotlin-Runtime-Component", "Kotlin-Version", "Log4jReleaseKey", "Log4jReleaseManager", "Log4jReleaseVersion", "Magma-Version", "Main-Class", "Manifest-Version", "Multi-Release", "Originally-Created-By", "Os-Arch", "Os-Name", "Os-Version", "Private-Package", "Provide-Capability", "Require-Capability", "Scm-Connection", "Scm-Revision", "Scm-Url", "Specification-Title", "Specification-Vendor", "Specification-Version", "Spring-Boot-Classes", "Spring-Boot-Lib", "Spring-Boot-Version", "Start-Class", "Tool", "X-Compile-Source-JDK", "X-Compile-Target-JDK", "url"]
2020-04-18 23:29:05.143  INFO 82 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track 【Rainych】 SAY SO - Doja Cat | Japanese Version (cover)
2020-04-18 23:29:05.289  INFO 82 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "701105975498637364", "track": "QAAAnwIAOuOAkFJhaW55Y2jjgJEgU0FZIFNPIC0gRG9qYSBDYXQgfCBKYXBhbmVzZSBWZXJzaW9uIChjb3ZlcikAC1JhaW55Y2ggUmFuAAAAAAAD79AAC0VzWmJXQXFVOHhZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9RXNaYldBcVU4eFkAB3lvdXR1YmUAAAAAAAAAAA=="}
2020-04-18 23:31:14.689  INFO 82 --- [XNIO-1 task-5] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-04-18 23:31:15.735  INFO 82 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track 【Rainych】AGAIN - Fullmetal Achemist : Brotherhood OP 1 (cover)
2020-04-18 23:31:36.125  INFO 82 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "701105975498637364", "track": "QAAApwIAQuOAkFJhaW55Y2jjgJFBR0FJTiAtIEZ1bGxtZXRhbCBBY2hlbWlzdCA6IEJyb3RoZXJob29kIE9QIDEgKGNvdmVyKQALUmFpbnljaCBSYW4AAAAAAAPr6AALNTlmb1I1S1VFS1kAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj01OWZvUjVLVUVLWQAHeW91dHViZQAAAAAAAAAA"}
2020-04-18 23:33:11.747  INFO 82 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "pause", "guildId": "701105975498637364", "pause": true}
2020-04-18 23:33:40.056  INFO 82 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "pause", "guildId": "701105975498637364", "pause": false}
2020-04-18 23:34:25.617  INFO 82 --- [XNIO-1 task-7] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-04-18 23:34:55.670  WARN 82 --- [XNIO-1 task-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.context.request.async.AsyncRequestTimeoutException]
2020-04-18 23:36:21.137  INFO 82 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "701105975498637364"}
2020-04-18 23:40:13.696  INFO 82 --- [XNIO-1 task-10] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-04-18 23:40:43.721  WARN 82 --- [XNIO-1 task-12] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.context.request.async.AsyncRequestTimeoutException]
2020-04-18 23:50:38.912 ERROR 82 --- [lava-daemon-pool-info-loader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item https://www.youtube.com/watch?v=yzC4hFK5P3g

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:220) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:232) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:228) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:96) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:61) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:133) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.38.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: Connection timed out
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:28) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:208) ~[lavaplayer-1.3.38.jar!/:na]
        ... 14 common frames omitted
Caused by: javax.net.ssl.SSLException: Connection timed out
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1652) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038) ~[na:na]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar!/:4.5.10]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:35) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:26) ~[lavaplayer-1.3.38.jar!/:na]
        ... 15 common frames omitted
        Suppressed: java.net.SocketException: Broken pipe
                at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:421) ~[na:na]
                at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:441) ~[na:na]
                at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:825) ~[na:na]
                at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1007) ~[na:na]
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:82) ~[na:na]
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:355) ~[na:na]
                ... 38 common frames omitted
Caused by: java.net.SocketException: Connection timed out
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:326) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802) ~[na:na]
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:937) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:450) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1409) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1022) ~[na:na]
        ... 34 common frames omitted

2020-04-18 23:50:38.919 ERROR 82 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:220) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:232) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:228) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:96) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:61) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:133) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.38.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: Connection timed out
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:28) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:208) ~[lavaplayer-1.3.38.jar!/:na]
        ... 14 common frames omitted
Caused by: javax.net.ssl.SSLException: Connection timed out
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[na:na]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1652) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038) ~[na:na]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[httpcore-4.4.12.jar!/:4.4.12]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar!/:4.5.10]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:35) ~[lavaplayer-1.3.38.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:26) ~[lavaplayer-1.3.38.jar!/:na]
        ... 15 common frames omitted
        Suppressed: java.net.SocketException: Broken pipe
                at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:421) ~[na:na]
                at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:441) ~[na:na]
                at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:825) ~[na:na]
                at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1007) ~[na:na]
                at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:82) ~[na:na]
                at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:355) ~[na:na]
                ... 38 common frames omitted
Caused by: java.net.SocketException: Connection timed out
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:326) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802) ~[na:na]
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:937) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:450) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1409) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1022) ~[na:na]
        ... 34 common frames omitted

2020-04-18 23:50:39.904  INFO 82 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track きゃりーぱみゅぱみゅ - PONPONPON , Kyary Pamyu Pamyu - PONPONPON
```

**Comment by cloudrac3r** [comment]
I also have this "timed out" issue. Lavalink will only connect to YouTube's video servers if they respond within 3000 milliseconds, but sometimes YouTube takes longer to respond, causing this error.

**Comment by freyacodes** [comment]
Please try setting the timeout to a higher value with #276
