### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by ImBoing** [lavalink-devs/Lavalink#277]
I get this error when I run the bot 
```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:6789
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on WebSocket instance at:
    at ClientRequest.<anonymous> (/Users/PL/Desktop/Music/node_modules/ws/lib/websocket.js:555:15)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6789
}
```

**Comment by freyacodes** [comment]
Lavalink (or anything at all) is not running at `127.0.0.1:6789`.

This is likely a configuration problem on your end. Use our discord channel if you want general troubleshooting advice.
