### ISSUE TITLE
Required library at /natives/linux-arm/libudpqueue.so was not found

### ISSUE THREAD

**Issue by TurtleIdiot** [lavalink-devs/Lavalink#279]
I started using lavalink to add music functionality to my bot. On my test environment (Windows 10 64 bit) lavalink ran correctly and played the music back. However, when i move it onto my production environment (Linux ARM 32 bit) Lavalink starts normally and can do search queries. When I try to play music, it throws this error:
`Required library at /natives/linux-arm/libudpqueue.so was not found`
I have tried to make this path on my production environment and it still didn't work. I think I would have to edit the .jar file

I am running OpenJDK 13

Output of `java -jar Lavalink.jar --version`:
```
Version:        3.3.1
Build:          997
Build time:     25.03.2020 12:30:43 UTC
Branch          master
Commit:         29f68ba
Commit time:    25.03.2020 12:28:48 UTC
JVM:            13.0.2
Lavaplayer      1.3.38
```

logs:
```
java.lang.UnsatisfiedLinkError: Required library at /natives/linux-arm/libudpqueue.so was not found
0|startll  |    at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary(NativeLibLoader.java:93) ~[lavaplayer-common-1.0.6.jar!/:na]
0|startll  |    at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77) ~[lavaplayer-common-1.0.6.jar!/:na]
0|startll  |    at com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManagerLibrary.getInstance(UdpQueueManagerLibrary.java:13) ~[udp-queue-1.0.8.jar!/:na]
0|startll  |    at com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManager.<init>(UdpQueueManager.java:27) ~[udp-queue-1.0.8.jar!/:na]
0|startll  |    at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.initialiseQueueManager(NativeAudioSendFactory.java:40) ~[jda-nas-1.1.0.jar!/:na]
0|startll  |    at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.addInstance(NativeAudioSendFactory.java:69) ~[jda-nas-1.1.0.jar!/:na]
0|startll  |    at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendSystem.start(NativeAudioSendSystem.java:23) ~[jda-nas-1.1.0.jar!/:na]
0|startll  |    at com.github.shredder121.asyncaudio.jda.AsyncAudioSendSystemWrapper.start(AsyncAudioSendSystemWrapper.java:37) ~[jda-async-packetprovider-1.3.2-MINN.jar!/:na]
0|startll  |    at space.npstr.magma.impl.connections.AudioConnection.startSendSystemIfReady(AudioConnection.java:320) ~[impl-0.12.5.jar!/:na]
0|startll  |    at space.npstr.magma.impl.connections.AudioConnection.handleSendHandlerUpdate(AudioConnection.java:237) ~[impl-0.12.5.jar!/:na]
0|startll  |    at space.npstr.magma.impl.connections.AudioConnection.hookOnNext(AudioConnection.java:222) ~[impl-0.12.5.jar!/:na]
0|startll  |    at space.npstr.magma.impl.connections.AudioConnection.hookOnNext(AudioConnection.java:61) ~[impl-0.12.5.jar!/:na]
0|startll  |    at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:158) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|startll  |    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|startll  |    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|startll  |    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|startll  |    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
0|startll  |    at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
0|startll  |    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
0|startll  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
0|startll  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
0|startll  |    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by freyacodes** [comment]
As mentioned in the requirements in the readme, support for ARM is best-effort.

Performance on ARM is very bad anyways. I'd recommend getting a regular 64-bit Linux server.

**Comment by topi314** [comment]
with [`v3.5.0`](https://github.com/freyacodes/Lavalink/releases/tag/3.5) lavalink added official support for arm
If this issue persists feel free to reopen the issue
