### ISSUE TITLE
AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by t4zzlerdeveloper** [lavalink-devs/Lavalink#293]
## Description 
This error prevents Lavalink from even launching! I have tried different Java versions and it still does not work. I would be very grateful if you could help me fixing this issue.

## Version info
**Client used: Java 13, Lavalink 3.3.1**

Output of `java -version`:
```
2020-05-14 18:09:35.801  WARN 11016 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-05-14 18:09:35.819 ERROR 11016 --- [           main] lavalink.server.Launcher                 : Application failed

java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_241]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_241]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[Lavalink.jar:na]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_241]
        at lavalink.server.Launcher.getVersionInfo(Launcher.kt:50) [classes!/:na]
        at lavalink.server.Launcher.getVersionInfo$default(Launcher.kt:49) [classes!/:na]
        at lavalink.server.Launcher$main$1.onApplicationEvent(Launcher.kt:118) ~[classes!/:na]
        at lavalink.server.Launcher$main$1.onApplicationEvent(Launcher.kt:43) ~[classes!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at lavalink.server.Launcher.main(Launcher.kt:127) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [Lavalink.jar:na]

2020-05-14 18:09:35.821 ERROR 11016 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_241]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[na:1.8.0_241]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_241]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[Lavalink.jar:na]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_241]
        at lavalink.server.Launcher.getVersionInfo(Launcher.kt:50) [classes!/:na]
        at lavalink.server.Launcher.getVersionInfo$default(Launcher.kt:49) [classes!/:na]
        at lavalink.server.Launcher$main$1.onApplicationEvent(Launcher.kt:118) ~[classes!/:na]
        at lavalink.server.Launcher$main$1.onApplicationEvent(Launcher.kt:43) ~[classes!/:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:305) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at lavalink.server.Launcher.main(Launcher.kt:127) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [Lavalink.jar:na]
```

**Comment by nikammerlaan** [comment]
You're attempting to run Lavalink with Java 8. Lavalink requires Java 11 as a minimum.

**Comment by t4zzlerdeveloper** [comment]
Turns out that I had mutiple versions of Java instaled and for some reason Lavalink was running with Java 8, I removed everything and instaled Java 14 and it works! Thank you!
