### ISSUE TITLE
Twitch Default Support Appears Broken

### ISSUE THREAD

**Issue by Ryu945** [lavalink-devs/Lavalink#298]
## Description
I am setting this up in my Discord bot for this first time but after talking with someone familiar with the software and doing some research, it appears that the default Twitch support doesn't work.  It will no longer play audio from a Twitch source and it says the search failed.  I have audio working on other sources I have tested.  I believe the problem may lie with a recent API change of Twitch involving tokens.  I read there was an API change in April.

From looking through code, I believe the problem may be bypassed by using your own token instead of the default token.  I'm still looking into which token I need to get from Twitch and how to get one.

## Version info
eris-lavalink
https://github.com/briantanner/eris-lavalink

Output of `java -version`:
```
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

ERROR 5099 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:35) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.38.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

Version:        8e7316ba9ea85a6cd2562e35cf9e16d6c0241f70-SNAPSHOT
Build:          1051
Build time:     18.05.2020 13:06:43 UTC
Branch          master
Commit:         8e7316b
Commit time:    18.05.2020 13:01:10 UTC
JVM:            11.0.7
Lavaplayer      1.3.38

**Comment by OtterBoops** [comment]
The dev branch should have lavaplayer's fix for Twitch support. Try that.

**Comment by zspri** [comment]
I'm having this issue on `123eb9405903b39630b707f495492ed98b8ea63e-SNAPSHOT` still. Looks like it's a bug with Lavaplayer.

Someone made a fix for it (https://github.com/sedmelluq/lavaplayer/pull/488) but the PR hasn't been pushed yet.

**Comment by topi314** [comment]
this seems to have been fixed with a lavaplayer update
