### ISSUE TITLE
Erroring out on attempt to play song.

### ISSUE THREAD

**Issue by ZandercraftGames** [lavalink-devs/Lavalink#302]
## Description
Lavalink will not play songs. It connects, queues the song, then leaves after throwing the error below. It was working yesterday. No reboots. No changes to the code of the server or client. 
Literally just stopped working spontaneously. The issue even still occurs after a full rebuild of the Docker container. It is on the master branch.

## Version info
**Client used:** Custom (using superagent)

The output of `java -version`:
```
OpenJDK version "13.0.2" 2020-01-14
OpenJDK Runtime Environment Zulu13.29+9-CA (build 13.0.2+6-MTS)
OpenJDK 64-Bit Server VM Zulu13.29+9-CA (build 13.0.2+6-MTS, mixed mode, sharing)
```

```
2020-05-29 01:59:17.979  INFO 1 --- [  XNIO-1 task-4] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-05-29 01:59:19.402  INFO 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: walk thru fire
2020-05-29 01:59:19.572  INFO 1 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"play","guildId":"413897297626267648","track":"QAAAlAIAMVZpY2V0b25lIC0gV2FsayBUaHJ1IEZpcmUgKEx5cmljcykgZnQuIE1lcm9uIFJ5YW4ACVdhdmVNdXNpYwAAAAAAAvm4AAtrUmF1cHRkeF9JcwABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PWtSYXVwdGR4X0lzAAd5b3V0dWJlAAAAAAAAAAA="}
2020-05-29 01:59:20.951 ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of kRauptdx_Is
2020-05-29T01:59:20.951500920Z 
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.38.jar!/:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null
at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.38.jar!/:na]
... 4 common frames omitted
```

**Comment by OtterBoops** [comment]
Try the dev branch/container

**Comment by EvieePy** [comment]
Same issue here. Nothing changed but nothing is working, I'll test out the development branch.

`Java 13.0.3`
`Lavalink 3.3.1 997`

**Comment by EvieePy** [comment]
Issue resolved with [Build 1006](https://ci.fredboat.com/viewLog.html?buildId=8107&buildTypeId=Lavalink_Build&tab=artifacts&branch_Lavalink=refs%2Fpull%2F301%2Fhead)

**Comment by ZandercraftGames** [comment]
@EvieePy Is that on the dev or master branch?

**Comment by MapleOrbit** [comment]
> @EvieePy Is that on the dev or master branch?

It is on the master branch..

**Comment by freyacodes** [comment]
Closing this as it appears to be fixed in latest versions
