### ISSUE TITLE
Keep repeating 'Somthing broke while playing

### ISSUE THREAD

**Issue by thrace19** [lavalink-devs/Lavalink#304]
## Description
From few days when I try to play songs from youtube or play from some radio stations it keeps repeating 'something broke while playing

## Version info
**Client used:** Lavacord

Output of `java -version`:
```
13
```
2020-06-01T03:14:34.119244+00:00 heroku[router]: at=info method=GET path="/loadtracks?identifier=ytsearch%3A+bozhe+moi" host=lavahost-in.herokuapp.com request_id=38013269-01d7-43ff-a68b-3aa26b864f7c fwd="34.201.5.10" dyno=web.1 connect=1ms service=1989ms status=200 bytes=15722 protocol=http
2020-06-01T03:14:35.417529+00:00 app[web.1]: 2020-06-01 03:14:35.416 ERROR 33 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of XADLmujg4_Y
2020-06-01T03:14:35.417538+00:00 app[web.1]: 
2020-06-01T03:14:35.417539+00:00 app[web.1]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
2020-06-01T03:14:35.417540+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
2020-06-01T03:14:35.417543+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.38.jar!/:na]
2020-06-01T03:14:35.417544+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.38.jar!/:na]
2020-06-01T03:14:35.417544+00:00 app[web.1]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
2020-06-01T03:14:35.417545+00:00 app[web.1]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
2020-06-01T03:14:35.417546+00:00 app[web.1]: 	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
2020-06-01T03:14:35.417546+00:00 app[web.1]: Caused by: java.lang.NullPointerException: null
2020-06-01T03:14:35.417547+00:00 app[web.1]: 	at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
2020-06-01T03:14:35.417547+00:00 app[web.1]: 	at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
2020-06-01T03:14:35.417548+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.38.jar!/:na]
2020-06-01T03:14:35.417549+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.38.jar!/:na]
2020-06-01T03:14:35.417549+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.38.jar!/:na]
2020-06-01T03:14:35.417550+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.38.jar!/:na]
2020-06-01T03:14:35.417550+00:00 app[web.1]: 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.38.jar!/:na]
2020-06-01T03:14:35.417551+00:00 app[web.1]: 	... 4 common frames omitted
2020-06-01T03:14:35.417551+00:00 app[web.1]: 
2020-06-01T03:14:35.422787+00:00 app[web.1]: 2020-06-01 03:14:35.422  INFO 33 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"488288043841880074"}

**Comment by freyacodes** [comment]
That track is a [music video](https://www.youtube.com/watch?v=XADLmujg4_Y), not a livestream or radio.

I believe you are using an outdated version of Lavalink. This issue should already be fixed. If you disagree, please post your full logs.
