### ISSUE TITLE
Something broke while playing the track.

### ISSUE THREAD

**Issue by infiniwave** [lavalink-devs/Lavalink#312]
## Description
The console outputs "Something broke while playing the track." and doesn't play the video.

I am running Java 13 on a Docker container. What is wrong?

## Version info
**Client used:** erela.js

Output of `java -version`:
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```

```2020-06-15 18:25:12.056 ERROR 34 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor : Error in playback of X1DRDcGlSsE
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.38.jar!/:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null
at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.38.jar!/:na]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.38.jar!/:na]
... 4 common frames omitted```

**Comment by OtterBoops** [comment]
Update your Lavalink.

**Comment by infiniwave** [comment]
@OtterBoops It is at the latest version already.

**Comment by Horstexplorer** [comment]
>  ~[lavaplayer-1.3.38.jar!/:na]
Its not, ll currently uses 1.3.49 within the master branch. It should be already available on ci - not sure how it looks for the docker container. Maybe u have to compile it ur own.

**Comment by OtterBoops** [comment]
>Maybe u have to compile it ur own.

He has to pull the docker image.

**Comment by infiniwave** [comment]
Hmm okay.

**Comment by shfancy** [comment]
This way I was able to solve my exactly same problem. Do you know what the cause is?

**Comment by OtterBoops** [comment]
> This way I was able to solve my exactly same problem. Do you know what the cause is?

What do you mean?

**Comment by HoloKi** [comment]
I Have the same issue:
```
2020-06-17 09:50:39.200 ERROR 15120 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of OPGtpO1g_jk

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.38.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null
	at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.38.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[lavaplayer-1.3.38.jar!/:na]
	... 4 common frames omitted

2020-06-17 09:50:39.205  INFO 15120 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "383386139333230592"}
2020-06-17 09:50:39.358  INFO 15120 --- [parallel-4] s.n.m.impl.connections.AudioWebSocket    : Websocket to wss://eu-central1374.discord.media/?v=4 closed with code 4014 and reason Disconnected.
2020-06-17 09:50:39.361  INFO 15120 --- [parallel-4] s.n.m.impl.connections.AudioWebSocket    : Closing
```

**Comment by duncte123** [comment]
Update lavalink

**Comment by HoloKi** [comment]
> Update lavalink

is lavalink 1.3.38 the last?

**Comment by duncte123** [comment]
Lavaplayer * and no, we're on version 1.3.49

Download the latest here https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1

**Comment by shfancy** [comment]
> What do you mean?

Do you know what has changed during this update?

**Comment by OtterBoops** [comment]
https://github.com/sedmelluq/lavaplayer has changelogs and commits.

**Comment by freyacodes** [comment]
There are too many threads like this where we are just asking people to update. Closing this.

Please use our Discord channel for further discussion.
