### ISSUE TITLE
Locally stored Opus file fails to decode

### ISSUE THREAD

**Issue by TheEssem** [lavalink-devs/Lavalink#318]
## Description
Whenever I try to play an Opus file stored locally (e.g. by queuing it via the URL `http://localhost:2333/loadtracks?identifier=assets/audio/explosion.opus`), it fails to decode with the error below. This does not happen with other formats like FLAC and MP3.

I am using the Docker container with this command to run Lavalink: `docker run --rm --network host -v /opt/Lavalink/application.yml:/opt/Lavalink/application.yml -v /mnt/CA60D24E60D2413D/Files/esmBot-rewrite/assets:/opt/Lavalink/assets fredboat/lavalink:dev`

## Version info
**Client used:** 
LavaCord/Eris 1.1.9

Output of `java -version` (obtained using `docker exec`):
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment Zulu13.29+9-CA (build 13.0.2+6-MTS)
OpenJDK 64-Bit Server VM Zulu13.29+9-CA (build 13.0.2+6-MTS, mixed mode, sharing)
```

Logs:
```
2020-06-27 00:26:54.385  INFO 1 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "./assets/audio/explosion.opus"
2020-06-27 00:26:54.400  INFO 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Unknown title
2020-06-27 00:26:54.545  INFO 1 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"sessionId":"39adbe62a97d105534e0b27274212861","event":{"token":"9f9ec0aadc2857d4","guild_id":"433408970955423765","endpoint":"us-south638.discord.media:80"},"op":"voiceUpdate","guildId":"433408970955423765"}
2020-06-27 00:26:54.614  INFO 1 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"track":"QAAAfAIADVVua25vd24gdGl0bGUADlVua25vd24gYXJ0aXN0f/////////8AHS4vYXNzZXRzL2F1ZGlvL2V4cGxvc2lvbi5vcHVzAQEAHS4vYXNzZXRzL2F1ZGlvL2V4cGxvc2lvbi5vcHVzAAVsb2NhbAADb2dnAAAAAAAAAAA=","op":"play","guildId":"433408970955423765"}
2020-06-27 00:26:54.645  INFO 1 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$542/0x00000008010ee840@108d0a85
2020-06-27 00:26:54.646  INFO 1 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2020-06-27 00:26:54.677  INFO 1 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: successfully loaded.
2020-06-27 00:26:54.681 ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of ./assets/audio/explosion.opus

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:294) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.process(OggAudioTrack.java:39) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioTrack.process(LocalAudioTrack.java:46) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.50.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.IllegalStateException: Failed to create a decoder instance with sample rate 44100 and channel count 2
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:25) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.ogg.opus.OggOpusTrackHandler.provideFrames(OggOpusTrackHandler.java:51) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.processTrackLoop(OggAudioTrack.java:58) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.lambda$process$0(OggAudioTrack.java:41) ~[lavaplayer-1.3.50.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276) ~[lavaplayer-1.3.50.jar!/:na]
	... 8 common frames omitted
```

**Comment by freyacodes** [comment]
This looks like a lavaplayer problem rather than a Lavalink problem

For good measure, could you try running `ffprobe` on the file?

**Comment by TheEssem** [comment]
Sure thing:
```
ffprobe version n4.2.3 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[ogg @ 0x5581c27cdac0] 655 bytes of comment header remain
Input #0, ogg, from 'explosion.opus':
  Duration: 00:00:14.54, start: 0.000000, bitrate: 91 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      ENCODER         : opusenc from opus-tools 0.1.10
      ENCODER_OPTIONS : --bitrate 128
```

**Comment by TheEssem** [comment]
Another note: Opus streams work just fine when encoded as mkv/webm instead of ogg.

**Comment by freyacodes** [comment]
Could be that lavaplayer doesn't support ogg.

Anyways, it is pretty clear that this is a Lavaplayer issue. If you want further discussion, please open an issue there.
