### ISSUE TITLE
Failed to load native library due to an exception

### ISSUE THREAD

**Issue by VozdyxDev** [lavalink-devs/Lavalink#337]
## Description

This works on my Windows 10 PC but does not work on my VPS Ubuntu 18.04
This does not work for all tracks.

## Version info
**Client used:** 

Output of `java -version`:
```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)

```

## Lavalink log
```
➜  java13 -jar node.jar
2020-08-11 22:15:20.639  INFO 1634 --- [           main] lavalink.server.Launche                                                                                        r                 :

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        3.3.1.1
        Build:          1075
        Build time:     13.07.2020 09:09:23 UTC
        Branch          master
        Commit:         f6a1a2a
        Commit time:    13.07.2020 09:04:37 UTC
        JVM:            13
        Lavaplayer      1.3.50

2020-08-11 22:15:20.822  INFO 1634 --- [           main] lavalink.server.Launche                                                                                        r                 : Starting Launcher on p553279.vps with PID 1634 (/home/vozdyx                                                                                        /music/lavalink/node.jar started by vozdyx in /home/vozdyx/music/lavalink)
2020-08-11 22:15:20.823  INFO 1634 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2020-08-11 22:15:21.138  WARN 1634 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-08-11 22:15:22.326  WARN 1634 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2020-08-11 22:15:22.354  INFO 1634 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2020-08-11 22:15:22.354  INFO 1634 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1448 ms
2020-08-11 22:15:22.481  INFO 1634 --- [           main] l.server.metrics.PrometheusMetrics       : Prometheus metrics set up
2020-08-11 22:15:22.874  WARN 1634 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2020-08-11 22:15:22.887  INFO 1634 --- [           main] l.s.c.AudioSendFactoryConfiguration      : OS: Linux, Arch: amd64
2020-08-11 22:15:22.887  INFO 1634 --- [           main] l.s.c.AudioSendFactoryConfiguration      : JDA-NAS supported system detected. Enabled native audio sending.
2020-08-11 22:15:22.887  INFO 1634 --- [           main] l.s.c.AudioSendFactoryConfiguration      : Setting buffer to 400ms
2020-08-11 22:15:22.887  INFO 1634 --- [           main] l.s.c.AudioSendFactoryConfiguration      : Setting playlist load limit to 6
2020-08-11 22:15:23.325  INFO 1634 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2020-08-11 22:15:23.749  INFO 1634 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-08-11 22:15:24.068  INFO 1634 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2020-08-11 22:15:24.079  INFO 1634 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (jar:file:/home/vozdyx/music/lavalink/node.jar!/BOOT-INF/lib/xnio-nio-3.3.8.Final.jar!/) to constructor sun.nio.ch.EPollSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-08-11 22:15:24.145  INFO 1634 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2020-08-11 22:15:24.149  INFO 1634 --- [           main] lavalink.server.Launcher                 : Started Launcher in 4.269 seconds (JVM running for 4.89)
2020-08-11 22:16:15.635  INFO 1634 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-08-11 22:16:15.636  INFO 1634 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-08-11 22:16:15.646  INFO 1634 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
2020-08-11 22:16:15.676  INFO 1634 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:36996
2020-08-11 22:16:15.814  INFO 1634 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:36996
2020-08-11 22:16:28.867  INFO 1634 --- [   XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op": "volume", "guildId": "735307885730594936", "volume": 10}
2020-08-11 22:16:28.882  INFO 1634 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-08-11 22:16:29.269  INFO 1634 --- [   XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "735307885730594936", "sessionId": "959ad102d2f327e1bd8d4085dcb91483", "event": {"token": "b376e55a6e1bae2f", "guild_id": "735307885730594936", "endpoint": "russia872.discord.media:80"}}
2020-08-11 22:16:29.336  INFO 1634 --- [     parallel-2] com.jcabi.manifests.Manifests            : 73 attributes loaded from 84 stream(s) in 41ms, 73 saved, 1240 ignored: ["Ant-Version", "Archiver-Version", "Automatic-Module-Name", "Bnd-LastModified", "Build-Jdk", "Build-Jdk-Spec", "Build-Time", "Built-By", "Bundle-ActivationPolicy", "Bundle-Activator", "Bundle-Category", "Bundle-Description", "Bundle-DocURL", "Bundle-License", "Bundle-ManifestVersion", "Bundle-Name", "Bundle-NativeCode", "Bundle-RequiredExecutionEnvironment", "Bundle-SymbolicName", "Bundle-Vendor", "Bundle-Version", "Copyright", "Created-By", "Export-Package", "Extension-Name", "Git-Revision", "Implementation-Build", "Implementation-Build-Date", "Implementation-Title", "Implementation-URL", "Implementation-Vendor", "Implementation-Vendor-Id", "Implementation-Version", "Import-Package", "Include-Resource", "JCabi-Build", "JCabi-Date", "JCabi-Version", "Jar-Name", "Jar-Version", "Java-Vendor", "Java-Version", "Kotlin-Runtime-Component", "Kotlin-Version", "Log4jReleaseKey", "Log4jReleaseManager", "Log4jReleaseVersion", "Magma-Version", "Main-Class", "Manifest-Version", "Multi-Release", "Originally-Created-By", "Os-Arch", "Os-Name", "Os-Version", "Private-Package", "Provide-Capability", "Require-Bundle", "Require-Capability", "Scm-Connection", "Scm-Revision", "Scm-Url", "Specification-Title", "Specification-Vendor", "Specification-Version", "Spring-Boot-Classes", "Spring-Boot-Lib", "Spring-Boot-Version", "Start-Class", "Tool", "X-Compile-Source-JDK", "X-Compile-Target-JDK", "url"]
2020-08-11 22:16:29.873  INFO 1634 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: die young ke$ha
2020-08-11 22:16:30.285  INFO 1634 --- [   XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "735307885730594936", "track": "QAAAgQIAIktlJGhhIC0gRGllIFlvdW5nIChPZmZpY2lhbCBWaWRlbykABWtlc2hhAAAAAAADQAgAC05PdWJ6SENVdDQ4AAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9Tk91YnpIQ1V0NDgAB3lvdXR1YmUAAAAAAAAAAA==", "noReplace": false, "startTime": "0"}
2020-08-11 22:16:30.327 ERROR 1634 --- [     parallel-3] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

java.lang.LinkageError: Failed to load native library due to an exception.
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:81) ~[lavaplayer-common-1.0.6.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManagerLibrary.getInstance(UdpQueueManagerLibrary.java:13) ~[udp-queue-1.0.8.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManager.<init>(UdpQueueManager.java:27) ~[udp-queue-1.0.8.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.initialiseQueueManager(NativeAudioSendFactory.java:40) ~[jda-nas-1.1.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory.addInstance(NativeAudioSendFactory.java:69) ~[jda-nas-1.1.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendSystem.start(NativeAudioSendSystem.java:23) ~[jda-nas-1.1.0.jar!/:na]
        at com.github.shredder121.asyncaudio.jda.AsyncAudioSendSystemWrapper.start(AsyncAudioSendSystemWrapper.java:37) ~[jda-async-packetprovider-1.3.2-MINN.jar!/:na]
        at space.npstr.magma.impl.connections.AudioConnection.startSendSystemIfReady(AudioConnection.java:320) ~[impl-0.12.5.jar!/:na]
        at space.npstr.magma.impl.connections.AudioConnection.handleSendHandlerUpdate(AudioConnection.java:237) ~[impl-0.12.5.jar!/:na]
        at space.npstr.magma.impl.connections.AudioConnection.hookOnNext(AudioConnection.java:222) ~[impl-0.12.5.jar!/:na]
        at space.npstr.magma.impl.connections.AudioConnection.hookOnNext(AudioConnection.java:61) ~[impl-0.12.5.jar!/:na]
        at reactor.core.publisher.BaseSubscriber.onNext(BaseSubscriber.java:158) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
        at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.2.12.RELEASE.jar!/:3.2.12.RELEASE]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.io.IOException: Failed to create directory for unpacked native library.
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary(NativeLibLoader.java:104) ~[lavaplayer-common-1.0.6.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77) ~[lavaplayer-common-1.0.6.jar!/:na]
        ... 20 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /tmp/lava-jni-natives/1597173390319
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[na:na]
        at java.base/java.nio.file.Files.createDirectory(Files.java:693) ~[na:na]
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:800) ~[na:na]
        at java.base/java.nio.file.Files.createDirectories(Files.java:786) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.createDirectoriesWithFullPermissions(NativeLibLoader.java:123) ~[lavaplayer-common-1.0.6.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary(NativeLibLoader.java:100) ~[lavaplayer-common-1.0.6.jar!/:na]
        ... 21 common frames omitted

2020-08-11 22:16:30.448  WARN 1634 --- [      Finalizer] c.s.d.l.natives.NativeResourceHolder     : Should have been closed before finalization (com.sedmelluq.discord.lavaplayer.udpqueue.natives.UdpQueueManager).
2020-08-11 22:16:31.294  INFO 1634 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$648/0x00000008011bb040@36038ba8
2020-08-11 22:16:31.297  INFO 1634 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2020-08-11 22:16:31.299 ERROR 1634 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library {}: loading failed.

java.lang.RuntimeException: java.io.IOException: Failed to create directory for unpacked native library.
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:139) ~[lava-common-1.1.0.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:113) ~[lava-common-1.1.0.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadAndRemember(NativeLibraryLoader.java:85) ~[lava-common-1.1.0.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:70) ~[lava-common-1.1.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:14) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.50.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.io.IOException: Failed to create directory for unpacked native library.
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.prepareExtractionDirectory(NativeLibraryLoader.java:155) ~[lava-common-1.1.0.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:131) ~[lava-common-1.1.0.jar!/:na]
        ... 26 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /tmp/lava-jni-natives/1597173391298
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[na:na]
        at java.base/java.nio.file.Files.createDirectory(Files.java:693) ~[na:na]
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:800) ~[na:na]
        at java.base/java.nio.file.Files.createDirectories(Files.java:786) ~[na:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.createDirectoriesWithFullPermissions(NativeLibraryLoader.java:210) ~[lava-common-1.1.0.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.prepareExtractionDirectory(NativeLibraryLoader.java:151) ~[lava-common-1.1.0.jar!/:na]
        ... 27 common frames omitted

2020-08-11 22:16:31.305 ERROR 1634 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of NOubzHCUt48

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.50.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.UnsatisfiedLinkError: 'long com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.create(int, int)'
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.create(Native Method) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:21) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.50.jar!/:na]
        ... 4 common frames omitted

Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.UnsatisfiedLinkError: 'long com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.create(int, int)'
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.create(Native Method)
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:21)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178)
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250)
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by freyacodes** [comment]
Your user does not have access `/tmp/lava-jni-natives/1597173391298`

If you ran Lavalink with root, it might be that `/tmp/lava-jni-natives` is owned by root.

**Comment by VozdyxDev** [comment]
Yeah, the problem was sudo permissions.
Thanks.
