### ISSUE TITLE
lava won't load playlist sometimes

### ISSUE THREAD

**Issue by Majoramari** [lavalink-devs/Lavalink#348]
## Description

when i try to load youtube playlists sometimes work but majority of the time i get this error
 `Error: Request failed with status code 500` OR `Request processing failed; nested exception is java.util.concurrent.CompletionException: java.lang.NullPointerException`

i'm sure it's a lavalink issue because i have my friend using Lavalink4NET (i'm using erela.js) and he is getting same errors

## Version info
**Client used:** erela.js@2.0.0

Output of `java -version`: 
```
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

```
2020-09-22 05:58:13.457  INFO 24017 --- [ XNIO-1 task-11] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-09-22 05:58:13.457  INFO 24017 --- [der-2-thread-39] c.s.l.e.y.tools.ip.Ipv6Block             : /2001:470:ca51:12a9:2170:b2b4:fb95:fcf3
2020-09-22 05:58:13.859  INFO 24017 --- [der-2-thread-39] c.s.l.e.y.tools.ip.Ipv6Block             : /2001:470:ca51:3a81:f89c:e16c:55b6:45f
2020-09-22 05:58:14.232  INFO 24017 --- [der-2-thread-39] c.s.l.e.y.tools.ip.Ipv6Block             : /2001:470:ca51:ed3:592e:ee14:7540:e0bb
2020-09-22 05:58:14.508  INFO 24017 --- [der-2-thread-39] lavalink.server.player.AudioLoader       : Loaded playlist POP Music Playlist 2020
2020-09-22 05:58:14.510 ERROR 24017 --- [  XNIO-1 task-8] io.undertow.request                      : UT005023: Exception handling request to /loadtracks

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.util.concurrent.CompletionException: java.lang.NullPointerException
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:81) ~[undertow-servlet-2.0.26.Fin
t-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:186) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$2$1.handleRequest(AsyncContextImpl.java:194) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$2.run(AsyncContextImpl.java:191) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$6.run(AsyncContextImpl.java:465) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$TaskDispatchRunnable.run(AsyncContextImpl.java:584) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[na:na]
        at lavalink.server.player.AudioLoader.playlistLoaded(AudioLoader.java:89) ~[classes!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:447) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.50.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.50.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        ... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
```

**Comment by exiify** [comment]
Yea same

**Comment by AlvaroMS25** [comment]
Me too, but also happens with track urls

**Comment by freyacodes** [comment]
Try the latest dev build. It has a newer Lavaplayer version

**Comment by exiify** [comment]
v3.3.1.1 Does not work

**Comment by AlvaroMS25** [comment]
where can i download the latest dev?

**Comment by freyacodes** [comment]
@Alvaro11143 https://ci.fredboat.com/viewType.html?buildTypeId=Lavalink_Build&branch_Lavalink=refs%2Fheads%2Fdev&tab=buildTypeStatusDiv&guest=1

**Comment by exiify** [comment]
It works! Thank you

**Comment by Majoramari** [comment]
@Frederikam hello, thank you I just tried the dev version and its working fine but I believe there's some issues like 

• spamming Ipv6Block over and over all the time (i'm using tunnelbroker)
```
2020-09-23 02:41:08.247  INFO 891 --- [ack-1-thread-26] c.s.l.e.y.tools.ip.Ipv6Block             : /2001:470:ca51:668f:d09d:708a:d2ec:1e49
2020-09-23 02:41:08.247  INFO 891 --- [ack-1-thread-34] c.s.l.e.y.tools.ip.Ipv6Block             : /2001:470:ca51:2b0:bfb1:165a:c1f8:a78e
2020-09-23 02:41:08.248  INFO 891 --- [ack-1-thread-29] c.s.l.e.y.tools.ip.Ipv6Block             : /2001:470:ca51:507e:a897:92cb:d5b7:6ced
2020-09-23 02:41:08.247  INFO 891 --- [ack-1-thread-22] c.s.l.e.y.tools.ip.Ipv6Block             : /2001:470:ca51:2023:6c22:38dc:4a92:7a2e
```
also the local files (files uploaded to discord) is not working in dev, + twtich still borken, both are giving same error.
```
2020-09-23 02:44:20.656 ERROR 891 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: No original bandcamp url found.
        at com.sedmelluq.discord.lavaplayer.source.bandcamp.BandcampAudioSourceManager.readOgUrl(BandcampAudioSourceManager.java:140) ~[lavaplayer-70f53b91.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.bandcamp.BandcampAudioSourceManager.lambda$loadItem$0(BandcampAudioSourceManager.java:72) ~[lavaplayer-70f53b91.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.bandcamp.BandcampAudioSourceManager.extractFromPageWithInterface(BandcampAudioSourceManager.java:191) ~[lavaplayer-70f53b91.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.bandcamp.BandcampAudioSourceManager.extractFromPage(BandcampAudioSourceManager.java:170) ~[lavaplayer-70f53b91.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.bandcamp.BandcampAudioSourceManager.loadItem(BandcampAudioSourceManager.java:70) ~[lavaplayer-70f53b91.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-70f53b91.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-70f53b91.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-70f53b91.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

**Comment by freyacodes** [comment]
I believe this issue has been fixed.

@Majoramari those don't seem related to this issue.
