### ISSUE TITLE
"Something broke when playing the track."

### ISSUE THREAD

**Issue by dakata1337** [lavalink-devs/Lavalink#354]
## Description
Today the bot worked just fine... now it doesn't. I also tryed downgrading to v3.3.1.1. Same issues.

## Version info
**Client used:** 
Victoria / Discord.Net

Output of `java -version`:
```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

 Version:        3.3.1.2
        Build:          1092
        Build time:     24.09.2020 08:45:36 UTC
        Branch          master
        Commit:         3dedc25
        Commit time:    24.09.2020 08:39:03 UTC
        JVM:            13.0.2
        Lavaplayer      1.3.51

Lavalink Logs:
```
2020-09-27 22:53:54.016  INFO 2264 --- [  XNIO-1 task-8] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:49998
2020-09-27 22:53:54.023  INFO 2264 --- [  XNIO-1 task-8] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:49998
2020-09-27 22:53:59.562  INFO 2264 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"guildId":"749076749345620028","sessionId":"cc692ba9212c26f2b75a8e0940d519fe","event":{"token":"450af5ae86c4353d","endpoint":"eu-central523.discord.media:443"},"op":"voiceUpdate"}
2020-09-27 22:54:01.606  INFO 2264 --- [  XNIO-1 task-9] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-09-27 22:54:02.191  INFO 2264 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: abba
2020-09-27 22:54:02.215  INFO 2264 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"volume":70,"guildId":"749076749345620028","op":"volume"}
2020-09-27 22:54:02.219  INFO 2264 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"endTime":232000,"track":"QAAAgwIAJUFiYmEgLSBEYW5jaW5nIFF1ZWVuIChPZmZpY2lhbCBWaWRlbykABEFCQkEAAAAAAAOKQAALeEZyR3V5dzFWOHMAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj14RnJHdXl3MVY4cwAHeW91dHViZQAAAAAAAAAA","noReplace":false,"startTime":0,"guildId":"749076749345620028","op":"play"}
2020-09-27 22:54:02.403 ERROR 2264 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of xFrGuyw1V8s

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.52.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.52.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.52.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:28) ~[lavaplayer-1.3.52.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:75) ~[lavaplayer-1.3.52.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.52.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.52.jar!/:na]
        ... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video page response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:39) ~[lavaplayer-1.3.52.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:26) ~[lavaplayer-1.3.52.jar!/:na]
        ... 7 common frames omitted
```

**Comment by Majoramari** [comment]
it works fine with me even with this error i get it after the track ends

**Comment by freyacodes** [comment]
You are getting ratelimited by YouTube. In short, you'll need multiple IPs.

This might help:
https://ramblings.fred.moe/2020/3/tunnelbroker-with-lavalink

Closing as this is not a bug.
