### ISSUE TITLE
Lavalink not playing tracks or audio

### ISSUE THREAD

**Issue by hburn7** [lavalink-devs/Lavalink#361]
I run a Discord bot that serves a few thousand servers and have loved Lavalink for music purposes. Yesterday, the player randomly broke without any changes to my application or Lavalink. I have updated Lavalink to the latest build and tried various other fixes to no avail.

Notably, my development machine works and plays audio perfectly fine, so I'm not exactly sure what the issue is. My `application.yml` files are identical on both machines.

Output of `java -version` (server):
```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

Output of `java -version` (development machine):
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```

Yes, the version is different, but I tried with Java 8 on the server to no avail as well, so I went with the recommended 13.0.2.

Here is some information from my latest log:
```
2020-10-10 23:25:52.404  INFO 6408 --- [XNIO-1 task-38] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-10-10 23:25:52.902  INFO 6408 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: Caramelldansen
2020-10-10 23:25:52.906  INFO 6408 --- [XNIO-1 I/O-7] lavalink.server.io.SocketServer          : {"endTime":179000,"track":"QAAApQIAPENhcmFtZWxsYSBHaXJscyAtIENhcmFtZWxsZGFuc2VuIFN3ZWRpc2ggT3JpZ2luYWwgKE9mZmljaWFsKQAPQ2FyYW1lbGxhIEdpcmxzAAAAAAACuzgAC3p2cTlyNlI2UUFZAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9enZxOXI2UjZRQVkAB3lvdXR1YmUAAAAAAAAAAA==","noReplace":false,"startTime":0,"guildId":"678461420962054145","op":"play"}
2020-10-10 23:25:53.012 ERROR 6408 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of zvq9r6R6QAY

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-a63c541dc5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-a63c541dc5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-a63c541dc5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager$$Lambda$581/0000000000000000.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:847) ~[na:na]
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 429
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:28) ~[lavaplayer-a63c541dc5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:75) ~[lavaplayer-a63c541dc5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-a63c541dc5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-a63c541dc5.jar!/:na]
	... 5 common frames omitted
Caused by: java.io.IOException: Invalid status code for video page response: 429
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:39) ~[lavaplayer-a63c541dc5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:26) ~[lavaplayer-a63c541dc5.jar!/:na]
	... 8 common frames omitted
```

Note that there are hundreds of these 429 error codes in my logs, first occurring at `2020-10-10 19:50:23`.

*Edit: I will also note that I am using the [Victoria](https://github.com/Yucked/Victoria) wrapper for C#.

**Comment by eepymoonshine** [comment]
You need to use IP rotation for playing youtube tracks. 429 means youtube banned you.

Refer to https://ramblings.fred.moe/2020/3/tunnelbroker-with-lavalink if you don't have a dedicated IPv6 /48.

**Comment by hburn7** [comment]
Okay thank you!
