### ISSUE TITLE
It doesn't play sound and returns an error.

### ISSUE THREAD

**Issue by Qroia** [lavalink-devs/Lavalink#368]
I don't understand what this error is: 
ERROR 156 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of W2xpPjV5FoI

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.54.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.54.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.54.3.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:31) ~[lavaplayer-1.3.54.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:75) ~[lavaplayer-1.3.54.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.54.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.54.3.jar!/:na]
        ... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video page response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:42) ~[lavaplayer-1.3.54.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:29) ~[lavaplayer-1.3.54.3.jar!/:na]
        ... 7 common frames omitted

And when I start I get strange warnings:

2020-10-19 13:50:40.155  INFO 156 --- [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        3.3.1.4
        Build:          1111
        Build time:     09.10.2020 14:42:03 UTC
        Branch          master
        Commit:         19972c2
        Commit time:    04.10.2020 15:12:22 UTC
        JVM:            13.0.2
        Lavaplayer      1.3.54.3

2020-10-19 13:50:40.812  INFO 156 --- [           main] lavalink.server.Launcher                 : Starting Launcher on 89b1f624-bfac-44da-9c94-f33f44bc7946 with PID 156 (/home/container/server.jar started by ? in /home/container)
2020-10-19 13:50:40.825  INFO 156 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2020-10-19 13:50:41.212  WARN 156 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-10-19 13:50:46.549  WARN 156 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2020-10-19 13:50:46.650  INFO 156 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2020-10-19 13:50:46.652  INFO 156 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 5492 ms
2020-10-19 13:50:48.745  WARN 156 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2020-10-19 13:50:48.761  INFO 156 --- [           main] l.s.c.AudioSendFactoryConfiguration      : OS: Linux, Arch: amd64
2020-10-19 13:50:48.762  INFO 156 --- [           main] l.s.c.AudioSendFactoryConfiguration      : JDA-NAS supported system detected. Enabled native audio sending.
2020-10-19 13:50:48.762  INFO 156 --- [           main] l.s.c.AudioSendFactoryConfiguration      : Setting buffer to 400ms
2020-10-19 13:50:48.763  INFO 156 --- [           main] l.s.c.AudioSendFactoryConfiguration      : Setting playlist load limit to 10
2020-10-19 13:50:50.017  INFO 156 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2020-10-19 13:50:52.022  INFO 156 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-10-19 13:50:53.686  INFO 156 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2020-10-19 13:50:53.707  INFO 156 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (jar:file:/home/container/server.jar!/BOOT-INF/lib/xnio-nio-3.3.8.Final.jar!/) to constructor sun.nio.ch.EPollSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-10-19 13:50:54.013  INFO 156 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 26978 (http) with context path ''
2020-10-19 13:50:54.028  INFO 156 --- [           main] lavalink.server.Launcher                 : Started Launcher in 17.724 seconds (JVM running for 21.674)

## Version info
**Client used:** 
        Version:        3.3.1.4
        Build:          1111
        Build time:     09.10.2020 14:42:03 UTC
        Branch          master
        Commit:         19972c2
        Commit time:    04.10.2020 15:12:22 UTC
        JVM:            13.0.2
        Lavaplayer      1.3.54.3

Output of `java -version`:
```
openjdk@1.13.0
```

**Comment by aikaterna** [comment]
429 = you've been ratelimited by YouTube. Also see the pinned issue about the warnings.

**Comment by freyacodes** [comment]
Opened a pinned issue for this

 #369
