### ISSUE TITLE
Unable to play audio

### ISSUE THREAD

**Issue by Vyprath** [lavalink-devs/Lavalink#378]
## Description

I am trying to play audio but Lavalink returns the error below. I don't think I've been rate-limited because it was just a single request in a private bot.

## Version info
**Client used:** 
Wavelink.py

Output of `java -version`:
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

Lavalink Logs
```
←[32m       .  ←[31m _                  _ _       _    ←[32m__ _ _
←[32m      /\\ ←[31m| | __ ___   ____ _| (_)_ __ | | __←[32m\ \ \ \
←[32m     ( ( )←[31m| |/ _` \ \ / / _` | | | '_ \| |/ /←[32m \ \ \ \
←[32m      \\/ ←[31m| | (_| |\ V / (_| | | | | | |   < ←[32m  ) ) ) )
←[32m       '  ←[31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\←[32m / / / /
←[0m    =========================================←[32m/_/_/_/←[0m

        Version:        3166d2dad1b0b3321934bbfd7e58623cb11b93f1-SNAPSHOT
        Build:          1117
        Build time:     19.10.2020 17:05:33 UTC
        Branch          dev
        Commit:         3166d2d
        Commit time:    19.10.2020 17:02:57 UTC
        JVM:            13.0.2
        Lavaplayer      1.3.59

2020-10-28 09:12:04.734  INFO 8040 --- [           main] lavalink.server.Launcher                 : Starting Launcher on DESKTOP-RMSLQ0A with PID 8040 (C:\Users\Vyprath\OneDrive\Documents\poof\Music bot\jdk-13.0.2\bin\Lavalink.jar started by Vyprath in C:\Users\Vyprath\OneDrive\Documents\poof\Music bot\jdk-13.0.2\bin)
2020-10-28 09:12:04.735  INFO 8040 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2020-10-28 09:12:04.806  WARN 8040 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-10-28 09:12:05.620  WARN 8040 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2020-10-28 09:12:05.637  INFO 8040 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2020-10-28 09:12:05.637  INFO 8040 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 871 ms
2020-10-28 09:12:05.888  WARN 8040 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2020-10-28 09:12:06.076  INFO 8040 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2020-10-28 09:12:06.334  INFO 8040 --- [           main] lavalink.server.config.KoeConfiguration  : OS: Windows 10, Arch: amd64
2020-10-28 09:12:06.334  WARN 8040 --- [           main] lavalink.server.config.KoeConfiguration  : This system and architecture appears to not support native audio sending! GC pauses may cause your bot to stutter during playback.
2020-10-28 09:12:06.506  INFO 8040 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-10-28 09:12:06.707  INFO 8040 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2020-10-28 09:12:06.716  INFO 8040 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2020-10-28 09:12:06.756  INFO 8040 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2020-10-28 09:12:06.760  INFO 8040 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.416 seconds (JVM running for 2.724)
2020-10-28 09:12:06.762  INFO 8040 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/Frederikam/Lavalink/issues/295
2020-10-28 09:12:23.103  INFO 8040 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-10-28 09:12:23.104  INFO 8040 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-10-28 09:12:23.108  INFO 8040 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2020-10-28 09:12:23.121  INFO 8040 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:59188
2020-10-28 09:12:23.166  INFO 8040 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:59188
2020-10-28 09:12:35.030  INFO 8040 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "volume", "guildId": "630785824958447626", "volume": 60}
2020-10-28 09:12:35.039  INFO 8040 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:blinding lights"
2020-10-28 09:12:35.966  INFO 8040 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: blinding lights
2020-10-28 09:12:36.382  INFO 8040 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "630785824958447626", "track": "QAAAlwIAM1RoZSBXZWVrbmQgLSBCbGluZGluZyBMaWdodHMgKE9mZmljaWFsIE11c2ljIFZpZGVvKQAKVGhlIFdlZWtuZAAAAAAABANYAAs0TlJYeDZVOEFCUQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PTROUlh4NlU4QUJRAAd5b3V0dWJlAAAAAAAAAAA=", "noReplace": false, "startTime": "0"}
2020-10-28 09:12:36.836  INFO 8040 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "630785824958447626", "sessionId": "8bfbdd8c4a9874a89caf6e5266bcc5f1", "event": {"token": "75fcae3bb5ebfe02", "guild_id": "630785824958447626", "endpoint": "japan517.discord.media:443"}}
2020-10-28 09:12:37.061 ERROR 8040 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 4NRXx6U8ABQ

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.59.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null
        at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:136) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.59.jar!/:na]
        ... 4 common frames omitted

```

**Comment by YVSemlani** [comment]
Had the same issue. Probably not due to rate limiting because I'm playing one song on user request.

**Comment by Walkyst** [comment]
Use lavalink from dev branch

**Comment by Vyprath** [comment]
> Use lavalink from dev branch

I am.

**Comment by freyacodes** [comment]
You are, though you should try the latest dev build from yesterday.

**Comment by Vyprath** [comment]
> You are, though you should try the latest dev build from yesterday.

Excuse me for my stupidity, but, is it a release or do I have to build it myself?
Also if it may help, it is loading playlists and URLs fine but the error occurs when I try to search the song.

Okay, I tried to dig more. I tried to skip through multiple songs (basically seek through the queue) and songs randomly skip [while throwing an error.](https://streamable.com/q74pfk) 

Not sure if this is a Wavelink issue or Lavalink at this point tbh. Or something with my code. Some clarification will be great. Thanks.

**Comment by YVSemlani** [comment]
I can only see the release from the 24th where is this release from yesterday?

**Comment by Vyprath** [comment]
> I can only see the release from the 24th where is this release from yesterday?

There was no release. However, there is a dev branch.

**Comment by dakata1337** [comment]
> > I can only see the release from the 24th where is this release from yesterday?
> 
> There was no release. However, there is a dev branch.

How can i build the dev branch?

**Comment by YVSemlani** [comment]
@Vyprath I checked on the dev branch too and there is still no release there. Sry for stupidity just a little confused.

**Comment by freyacodes** [comment]
To clear the grand confusion here, you can download from the CI. Builds are linked with each commit.

Ask in the support channel if you get stuck

**Comment by YVSemlani** [comment]
The issue continues even after I downloaded yesterdays dev version.

Heres the error I got
![image](https://user-images.githubusercontent.com/38896123/97480200-1c0a8a00-1921-11eb-8562-a3f04ec86acc.png)

Heres where I downloaded it from
![image](https://user-images.githubusercontent.com/38896123/97480271-2b89d300-1921-11eb-9b12-3110d575448a.png)

Client:
Wavelink

Java Version Output
![image](https://user-images.githubusercontent.com/38896123/97480430-61c75280-1921-11eb-9db8-abaf710c0f64.png)

**Comment by freyacodes** [comment]
@Halfblood1223 give me the output of `java -jar Lavalink.jar --version`

From the first screenshot it looks like you are not running the version in your second screenshot.

**Comment by YVSemlani** [comment]
Output Here
![image](https://user-images.githubusercontent.com/38896123/97481058-4446b880-1922-11eb-9666-eaad5eaba4f4.png)

I think I am running the wrong version but I'm not sure why as I downloaded it from their for sure. I'll try again and if it doesn't work I'll move to the support channel on the JDA discord.

**Comment by freyacodes** [comment]
Anyways I am closing this as I believe the issue to be resolved.
