### ISSUE TITLE
[Dev Branch] Error when trying to play any song.

### ISSUE THREAD

**Issue by ZandercraftGames** [lavalink-devs/Lavalink#390]
## Description
When requesting any song through the latest docker build of the lavalink dev branch, it returns the following error and will not play the song.

## Version info
**Client used:** Custom

Output of `java -version`:
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment Zulu13.29+9-CA (build 13.0.2+6-MTS)
OpenJDK 64-Bit Server VM Zulu13.29+9-CA (build 13.0.2+6-MTS, mixed mode, sharing)
```
```
2020-11-12 01:14:18.865 ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of OWs7CRvV9Bg
2020-11-12T01:14:18.867281100Z 
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.59.jar!/:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.RuntimeException: Error when extracting data EID: 5a2d5d8b-5652-4ca6-a696-ffd46f2ee248, mainJson:  redacted, check EID from log
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithLoggedPayload(ExceptionTools.java:131) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:65) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:40) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.59.jar!/:na]
... 4 common frames omitted
Caused by: java.lang.RuntimeException: No playability status block.
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.checkPlayabilityStatus(DefaultYoutubeTrackDetailsLoader.java:98) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:76) ~[lavaplayer-1.3.59.jar!/:na]
at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:54) ~[lavaplayer-1.3.59.jar!/:na]
... 8 common frames omitted
```

**Comment by natanbc** [comment]
[Youtube is down](https://twitter.com/TeamYouTube/status/1326681978037444608?s=20)

**Comment by ZandercraftGames** [comment]
@natanbc LOL! Whoops. I accessed the site and saw the error, but assumed it had something to do with my audio devices since I had messed with them earlier and YouTube is finicky about that. Thanks.
