### ISSUE TITLE
error Something broke when playing the track

### ISSUE THREAD

**Issue by LanaKee** [lavalink-devs/Lavalink#393]
## Version info
**Client used:** 
3.3.2 , @Lavacord/Discord.js

Output of `java -version`:
```
openjdk 13 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
```

```
2020-11-15 11:50:02.541  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : Connection closed from /183.111.253.116:46820 -- CloseStatus[code=1006, reason=]
2020-11-15 11:50:02.567  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2020-11-15 11:50:17.912  INFO 12206 --- [XNIO-1 task-5] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /183.111.253.116:52982
2020-11-15 11:50:18.068  INFO 12206 --- [XNIO-1 task-5] lavalink.server.io.SocketServer          : Connection successfully established from /183.111.253.116:52982
2020-11-15 11:54:22.823  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : Connection closed from /183.111.253.116:52982 -- CloseStatus[code=1006, reason=]
2020-11-15 11:54:22.826  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2020-11-15 11:54:38.259  INFO 12206 --- [XNIO-1 task-6] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /183.111.253.116:53042
2020-11-15 11:54:38.370  INFO 12206 --- [XNIO-1 task-6] lavalink.server.io.SocketServer          : Connection successfully established from /183.111.253.116:53042
2020-11-15 14:59:01.844  INFO 12206 --- [XNIO-1 task-7] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "scsearch: Yume wo Uchinuku Shunkan ni"
2020-11-15 14:59:02.427  INFO 12206 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: Yume wo Uchinuku Shunkan ni
2020-11-15 14:59:02.455  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"track":"QAABAQIAHFl1bWUgV28gVWNoaW51a3UgU2h1bmthbiBOaSEACFN1bm55IEtvAAAAAAAESAUAcU86aHR0cHM6Ly9hcGktdjIuc291bmRjbG91ZC5jb20vbWVkaWEvc291bmRjbG91ZDp0cmFja3M6ODAyNDg4OTA0L2U5MTU5MWMyLTg2OGMtNDk2MS04YzBkLWNkYTAzYzcwZmUwZS9zdHJlYW0vaGxzAAEARWh0dHBzOi8vc291bmRjbG91ZC5jb20vc3Vubnkta28tNzYxNDY0NjE0L3l1bWUtd28tdWNoaW51a3Utc2h1bmthbi1uaQAKc291bmRjbG91ZAAAAAAAAAAA","op":"play","guildId":"583665713462640661"}
2020-11-15 14:59:02.461  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"volume":100,"op":"volume","guildId":"583665713462640661"}
2020-11-15 14:59:02.850  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"de37adff610112fcad5e0684650078e4","event":{"token":"9a2bd6a3f479076f","guild_id":"583665713462640661","endpoint":"south-korea342.discord.media:443"},"op":"voiceUpdate","guildId":"583665713462640661"}
2020-11-15 15:03:11.582  INFO 12206 --- [XNIO-1 task-9] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /119.70.85.132:59868
2020-11-15 15:03:11.754  INFO 12206 --- [XNIO-1 task-9] lavalink.server.io.SocketServer          : Connection successfully established from /119.70.85.132:59868
2020-11-15 15:03:15.651  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"583665713462640661"}
2020-11-15 15:03:29.961  INFO 12206 --- [XNIO-1 task-10] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch: 꿈을 궤뚫는 순간에"
2020-11-15 15:03:30.767  INFO 12206 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: 꿈을 궤뚫는 순간에
2020-11-15 15:03:30.795  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"track":"QAAAqAIAOSJZdW1lIHdvIFVjaGludWt1IFNodW5rYW4gbmkhIiBieSBQb3BwaW4nUGFydHkg44CQRlVMTOOAkQAVRXJhaSDhtITQvc6xzrcg5a+d44KLAAAAAAAEwsAAC2VxSHhMajBtWGxrAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZXFIeExqMG1YbGsAB3lvdXR1YmUAAAAAAAAAAA==","op":"play","guildId":"763359000002953248"}
2020-11-15 15:03:30.798  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"volume":100,"op":"volume","guildId":"763359000002953248"}
2020-11-15 15:03:31.194  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"5b4caf74f0a7d89acc2a1db311afd771","event":{"token":"14e0b63afa32b0ad","guild_id":"763359000002953248","endpoint":"south-korea184.discord.media:443"},"op":"voiceUpdate","guildId":"763359000002953248"}
2020-11-15 15:03:31.572 ERROR 12206 --- [lava-daemon-pool-playback-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of eqHxLj0mXlk

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.59.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.59.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.59.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null

2020-11-15 15:03:31.660  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"763359000002953248"}
2020-11-15 15:05:36.978  INFO 12206 --- [XNIO-1 task-12] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch: 슈퍼마리오 갤럭시"
2020-11-15 15:05:37.552  INFO 12206 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: 슈퍼마리오 갤럭시
2020-11-15 15:05:37.604  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"track":"QAAAogIAOOyKiO2NvOuniOumrOyYpCDqsKTrn63si5wgW+yKiO2NvOuniOumrOyYpCAzRCDsu6zroInshZhdABDrhbnrkZDroZwg7JuU65OcAAAAAAI9A2gAC3R3Z0M3SldLellnAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9dHdnQzdKV0t6WWcAB3lvdXR1YmUAAAAAAAAAAA==","op":"play","guildId":"763359000002953248"}
2020-11-15 15:05:37.614  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"volume":100,"op":"volume","guildId":"763359000002953248"}
2020-11-15 15:05:38.003  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"5b4caf74f0a7d89acc2a1db311afd771","event":{"token":"291b0eddfcc2cb85","guild_id":"763359000002953248","endpoint":"south-korea184.discord.media:443"},"op":"voiceUpdate","guildId":"763359000002953248"}
2020-11-15 15:05:45.499  INFO 12206 --- [XNIO-1 task-14] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch: 꿈을 궤뚫는 순간에"
2020-11-15 15:05:45.961  INFO 12206 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: 꿈을 궤뚫는 순간에
2020-11-15 15:05:47.446  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"763359000002953248"}
2020-11-15 15:05:47.454  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"track":"QAAAqAIAOSJZdW1lIHdvIFVjaGludWt1IFNodW5rYW4gbmkhIiBieSBQb3BwaW4nUGFydHkg44CQRlVMTOOAkQAVRXJhaSDhtITQvc6xzrcg5a+d44KLAAAAAAAEwsAAC2VxSHhMajBtWGxrAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9ZXFIeExqMG1YbGsAB3lvdXR1YmUAAAAAAAAAAA==","op":"play","guildId":"763359000002953248"}
2020-11-15 15:05:47.458  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"volume":100,"op":"volume","guildId":"763359000002953248"}
2020-11-15 15:05:47.932 ERROR 12206 --- [lava-daemon-pool-playback-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of eqHxLj0mXlk

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.59.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.59.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.59.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null

2020-11-15 15:05:47.999  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"763359000002953248"}
2020-11-15 15:05:51.522  INFO 12206 --- [XNIO-1 task-16] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch: 안녕"
2020-11-15 15:05:52.183  INFO 12206 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: 안녕
2020-11-15 15:05:52.202  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"track":"QAAAoQIAN+2PtO2CtCAtIOyViOuFlSAo7Zi47YWUIOuNuOujqOuCmCBPU1QgUEFSVC4xMCkgLyDqsIDsgqwAEE11c2ljIGlzIG15IGxpZmUAAAAAAANy0AALVWlkaFFUbTF1bHcAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1VaWRoUVRtMXVsdwAHeW91dHViZQAAAAAAAAAA","op":"play","guildId":"763359000002953248"}
2020-11-15 15:05:52.207  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"volume":100,"op":"volume","guildId":"763359000002953248"}
2020-11-15 15:05:52.598  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"5b4caf74f0a7d89acc2a1db311afd771","event":{"token":"1bda0fa0ce224b06","guild_id":"763359000002953248","endpoint":"south-korea184.discord.media:443"},"op":"voiceUpdate","guildId":"763359000002953248"}
2020-11-15 15:05:52.795 ERROR 12206 --- [lava-daemon-pool-playback-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of UidhQTm1ulw

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.59.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.59.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.59.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null

2020-11-15 15:05:52.825  INFO 12206 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"763359000002953248"}
2020-11-15 15:06:33.754  INFO 12206 --- [Thread-1] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-11-15 15:06:33.763  INFO 12206 --- [Thread-1] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring disabled.
2020-11-15 15:06:33.797  INFO 12206 --- [Thread-1] io.undertow.servlet                      : Destroying Spring FrameworkServlet 'dispatcherServlet'
2020-11-15 15:06:33.815 ERROR 12206 --- [XNIO-1 I/O-2] org.xnio.listener                        : XNIO001007: A channel event listener threw an exception
```

Most of the songs don't play on YouTube.
But if you search with a link, it works fine.
what's the reason?

**Comment by freyacodes** [comment]
Duplicate of #380

Update your Lavalink if you haven't already
