### ISSUE TITLE
Failed to set channel option 'IP_TOS' with value '24' for channel '[id: 0xfcee6426]'

### ISSUE THREAD

**Issue by 1mgr007** [lavalink-devs/Lavalink#400]
## Description
I get this warning from running Lavalink.jar
I don't know what this means and what caused it.

## Version info
**Client used:**`
```
Lavalink: 3.3.2.1
Lavaplayer: 1.3.53
Erela.js: 2.2.0
Java: openjdk 13.0.4
OS: Ubuntu 20.04.1 LTS
```

```
2020-11-24 02:22:25.294  WARN 189 --- [ntLoopGroup-2-2] io.netty.bootstrap.Bootstrap             : Failed to set channel option 'IP_TOS' with value '24' for channel '[id: 0xfcee6426]'

io.netty.channel.ChannelException: java.net.SocketException: Operation not permitted
        at io.netty.channel.socket.DefaultDatagramChannelConfig.setTrafficClass(DefaultDatagramChannelConfig.java:358) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.socket.DefaultDatagramChannelConfig.setOption(DefaultDatagramChannelConfig.java:130) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.socket.nio.NioDatagramChannelConfig.setOption(NioDatagramChannelConfig.java:216) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:451) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]   
        at io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:443) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]  
        at io.netty.bootstrap.Bootstrap.init(Bootstrap.java:265) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:311) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]    
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at moe.kyokobot.koe.internal.handler.DiscordUDPConnection.connect(DiscordUDPConnection.java:60) ~[core-1.0.1.jar!/:na]
        at moe.kyokobot.koe.gateway.VoiceGatewayV4Connection.selectProtocol(VoiceGatewayV4Connection.java:150) ~[core-1.0.1.jar!/:na]
        at moe.kyokobot.koe.gateway.VoiceGatewayV4Connection.handlePayload(VoiceGatewayV4Connection.java:77) ~[core-1.0.1.jar!/:na]
        at moe.kyokobot.koe.gateway.AbstractVoiceGatewayConnection$WebSocketClientHandler.channelRead0(AbstractVoiceGatewayConnection.java:182) ~[core-1.0.1.jar!/:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[netty-codec-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) ~[netty-codec-4.1.48.Final.jar!/:4.1.48.Final]  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1486) ~[netty-handler-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235) ~[netty-handler-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282) ~[netty-handler-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) ~[netty-codec-4.1.48.Final.jar!/:4.1.48.Final]   
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.48.Final.jar!/:4.1.48.Final]  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]        
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.48.Final.jar!/:4.1.48.Final]  
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]      
Caused by: java.net.SocketException: Operation not permitted
        at java.base/sun.nio.ch.Net.setIntOption0(Native Method) ~[na:na]        at java.base/sun.nio.ch.Net.setSocketOption(Net.java:379) ~[na:na]
        at java.base/sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:237) ~[na:na]
        at java.base/sun.nio.ch.DatagramSocketAdaptor.setIntOption(DatagramSocketAdaptor.java:316) ~[na:na]
        at java.base/sun.nio.ch.DatagramSocketAdaptor.setTrafficClass(DatagramSocketAdaptor.java:387) ~[na:na]
        at io.netty.channel.socket.DefaultDatagramChannelConfig.setTrafficClass(DefaultDatagramChannelConfig.java:356) ~[netty-transport-4.1.48.Final.jar!/:4.1.48.Final]
        ... 43 common frames omitted
```

**Comment by freyacodes** [comment]
Are you by any chance using WSL?

**Comment by 1mgr007** [comment]
Yes, I use WSL
Is that what caused it ?

**Comment by freyacodes** [comment]
Looks like it. I did some searching.

https://github.com/microsoft/WSL/issues/6222

Maybe you can run Lavalink directly on Windows?

**Comment by 1mgr007** [comment]
Okey, thanks for the answer.
