### ISSUE TITLE
Something broke when playing the track.

### ISSUE THREAD

**Issue by Samir-OP** [lavalink-devs/Lavalink#403]
## Description
I just played a song and got this error.
I used it in windows 10 VPS. From my Pc, it's working fine but from VPS it's giving me an error.

## Version info
**Client used:** Erela.js

Output of `java -version`:
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

Version:        2f721caf9cb6b899effa9ba0cdb02400c5930bc4-SNAPSHOT
Build:          Unofficial
Build time:     08.11.2020 20:12:38 UTC
Branch          dev
Commit:         2f721ca
Commit time:    07.11.2020 02:10:57 UTC
JVM:            11
Lavaplayer      1.3.59

**Comment by freyacodes** [comment]
There are several problems with this issue
* You're not telling us enough to identify the error
* You're using an unofficial build that is horribly outdated. Use the official dev branch which now supports filters
* Your lavaplayer version is old

You should update to a version with Lavaplayer `1.3.61`. That will most likely fix your problem.

**Comment by eepymoonshine** [comment]
Update lavalink, that LP is old.

**Comment by Samir-OP** [comment]
after "java -jar Lavalink.jar --version"
```
Version:        3.3.2.2
Build:          1155
Build time:     28.11.2020 11:50:13 UTC
Branch          dev
Commit:         23c883a
Commit time:    28.11.2020 11:42:10 UTC
JVM:            11
Lavaplayer      1.3.61
```
I'm still getting that same error. 
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
```

**Comment by freyacodes** [comment]
You need to provide the full error trace

**Comment by Samir-OP** [comment]
Sure here it is
```
2020-11-29 11:34:47.429  INFO 8552 --- [           main] lavalink.server.Launcher                 : Starting Launcher on WIN-JG1E0O7FSBS with PID 8552 (C:\Users\DynamoYT\Desktop\Melodybeta\LAVA\Lavalink (1).jar started by DynamoYT in C:\Users\DynamoYT\Desktop\Melodybeta\LAVA)
2020-11-29 11:34:47.446  INFO 8552 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2020-11-29 11:34:47.426  WARN 8552 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-11-29 11:34:53.149  WARN 8552 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2020-11-29 11:34:53.259  INFO 8552 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2020-11-29 11:34:53.268  INFO 8552 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 5664 ms
2020-11-29 11:34:55.036  WARN 8552 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2020-11-29 11:34:56.243  INFO 8552 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2020-11-29 11:34:57.253  INFO 8552 --- [           main] lavalink.server.config.KoeConfiguration  : OS: Windows Server 2016, Arch: amd64
2020-11-29 11:34:57.258  WARN 8552 --- [           main] lavalink.server.config.KoeConfiguration  : This system and architecture appears to not support native audio sending! GC pauses may cause your bot to stutter during playback.
2020-11-29 11:34:58.005  INFO 8552 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-11-29 11:35:00.108  INFO 8552 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2020-11-29 11:35:00.140  INFO 8552 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2020-11-29 11:35:00.270  INFO 8552 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2020-11-29 11:35:00.286  INFO 8552 --- [           main] lavalink.server.Launcher                 : Started Launcher in 15.651 seconds (JVM running for 17.434)
2020-11-29 11:35:00.291  INFO 8552 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/Frederikam/Lavalink/issues/295
2020-11-29 11:35:57.985  INFO 8552 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-11-29 11:35:57.994  INFO 8552 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-11-29 11:35:58.014  INFO 8552 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 19 ms
2020-11-29 11:35:58.071  INFO 8552 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:64077
2020-11-29 11:35:58.252  INFO 8552 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:64077
2020-11-29 13:43:33.101  INFO 8552 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"746653541115887637","volume":100}
2020-11-29 13:43:33.445  INFO 8552 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"sessionId":"f93941396b46988170eaf01dc21e3c20","op":"voiceUpdate","guildId":"746653541115887637","event":{"token":"7e64bb0dd4bb58b1","guild_id":"746653541115887637","endpoint":"india517.discord.media:443"}}
2020-11-29 13:43:48.622  INFO 8552 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:Hasi female"
2020-11-29 13:43:49.595  INFO 8552 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: Hasi female
2020-11-29 13:43:49.683  INFO 8552 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"play","guildId":"746653541115887637","track":"QAAAvAIAVUhhc2kgLSBGZW1hbGUgVmVyc2lvbiAtIEhhbWFyaSBBZGh1cmkgS2FoYW5pfE9mZmljaWFsIEJvbGx5d29vZCBMeXJpY3N8U2hyZXlhIEdob3NoYWwADUx5cmljR3VydVZFVk8AAAAAAAL9oAALWHBQaHBBSHlHTzAAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1YcFBocEFIeUdPMAAHeW91dHViZQAAAAAAAAAA"}
2020-11-29 13:43:49.876 ERROR 8552 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of XpPhpAHyGO0

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.60.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:42) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.60.jar!/:na]
        ... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video page response: 429
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromMainPage(DefaultYoutubeTrackDetailsLoader.java:169) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:51) ~[lavaplayer-1.3.60.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:40) ~[lavaplayer-1.3.60.jar!/:na]
        ... 7 common frames omitted
```

**Comment by topi314** [comment]
Http code 429
You are being ratelimited by YT

**Comment by Samir-OP** [comment]
any solution for it?

**Comment by topi314** [comment]
ipv6 rotation
for more information join the jda discord there is a channel related to lavalink

**Comment by freyacodes** [comment]
Duplicate of #369
