### ISSUE TITLE
My bot does not send sound

### ISSUE THREAD

**Issue by egeakman** [lavalink-devs/Lavalink#404]
## Description
Hi. I have a problem with my Discord bot. It can not play music. It connects to voice channel, finds the song, says now playing "...  song" but it doesn't send any sounds. I use wavelink [(github link)](https://github.com/PythonistaGuild/Wavelink/). Thanks in advance.

## Version info
**Client used:** Wavelink [github link](https://github.com/PythonistaGuild/Wavelink/)

Output of `java -version`:
```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

## Logs:
```
2020-11-30 10:56:41.952  INFO 2672 --- [           main] lavalink.server.Launcher                 :

←[32m       .  ←[31m _                  _ _       _    ←[32m__ _ _
←[32m      /\\ ←[31m| | __ ___   ____ _| (_)_ __ | | __←[32m\ \ \ \
←[32m     ( ( )←[31m| |/ _` \ \ / / _` | | | '_ \| |/ /←[32m \ \ \ \
←[32m      \\/ ←[31m| | (_| |\ V / (_| | | | | | |   < ←[32m  ) ) ) )
←[32m       '  ←[31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\←[32m / / / /
←[0m    =========================================←[32m/_/_/_/←[0m

        Version:        3.3.2
        Build:          1122
        Build time:     24.10.2020 09:19:26 UTC
        Branch          master
        Commit:         644b8c9
        Commit time:    24.10.2020 09:14:00 UTC
        JVM:            13.0.2
        Lavaplayer      1.3.59

2020-11-30 10:56:42.042  INFO 2672 --- [           main] lavalink.server.Launcher                 : Starting Launcher on DESKTOP-4I30U5D with PID 2672 (C:\Users\User\OneDrive\Masa³st³\Eg-Bot\Lavalink.jar started by User in C:\Users\User\OneDrive\Masa³st³\Eg-Bot)
2020-11-30 10:56:42.043  INFO 2672 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2020-11-30 10:56:42.147  WARN 2672 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-11-30 10:56:43.320  WARN 2672 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2020-11-30 10:56:43.345  INFO 2672 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2020-11-30 10:56:43.345  INFO 2672 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1255 ms
2020-11-30 10:56:43.781  WARN 2672 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2020-11-30 10:56:44.049  INFO 2672 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2020-11-30 10:56:44.411  INFO 2672 --- [           main] lavalink.server.config.KoeConfiguration  : OS: Windows 10, Arch: amd64
2020-11-30 10:56:44.412  WARN 2672 --- [           main] lavalink.server.config.KoeConfiguration  : This system and architecture appears to not support native audio sending! GC pauses may cause your bot to stutter during playback.
2020-11-30 10:56:44.673  INFO 2672 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-11-30 10:56:44.968  INFO 2672 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2020-11-30 10:56:44.982  INFO 2672 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2020-11-30 10:56:45.048  INFO 2672 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2020-11-30 10:56:45.053  INFO 2672 --- [           main] lavalink.server.Launcher                 : Started Launcher in 3.648 seconds (JVM running for 4.185)
2020-11-30 10:56:45.056  INFO 2672 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/Frederikam/Lavalink/issues/295
2020-11-30 10:57:01.111  INFO 2672 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-11-30 10:57:01.112  INFO 2672 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-11-30 10:57:01.120  INFO 2672 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 8 ms
2020-11-30 10:57:01.143  INFO 2672 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /0:0:0:0:0:0:0:1:52289
2020-11-30 10:57:01.223  INFO 2672 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /0:0:0:0:0:0:0:1:52289
2020-11-30 10:57:09.822  INFO 2672 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:test music"
2020-11-30 10:57:10.072  INFO 2672 --- [   XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "706234454733226106", "sessionId": "b3e00947a6725e6e9dd970d559d756b2", "event": {"token": "1a60baf59e766553", "guild_id": "706234454733226106", "endpoint": "eu-central5825.discord.media:443"}}
2020-11-30 10:57:10.974  INFO 2672 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: test music
2020-11-30 10:57:11.352  INFO 2672 --- [   XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "706234454733226106", "track": "QAAAyAIAWk1VU0lDIFRFU1QgQVVESU8gU1lTVEVNIC0gQVVESU9QSElMRSBNVVNJQyBDT0xMRUNUSU9OIDIwMTggIC0gQXVkaW9waGlsZSBNdXNpYyAtIE5iUiBNdXNpYwAUQXVkaW9waGlsZSBOQlIgTXVzaWMAAAAAAEo76AALN2FFVWFrS01MQnMAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj03YUVVYWtLTUxCcwAHeW91dHViZQAAAAAAAAAA", "noReplace": false, "startTime": "0"}
2020-11-30 10:57:12.290  WARN 2672 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of 7aEUakKMLBs

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Track information is unavailable.
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackBaseInfoFromEmbedPage(DefaultYoutubeTrackDetailsLoader.java:186) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:69) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:29) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:75) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.59.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.59.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.IllegalStateException: Expected player config is not present in embed page.
        ... 10 common frames omitted
```

**Comment by topi314** [comment]
seems like the track you are trying to paly is age restricted
lavaplayer 1.3.61 has a workaround just update lavalink to latest

**Comment by egeakman** [comment]
> seems like the track you are trying to paly is age restricted
> lavaplayer 1.3.61 has a workaround just update lavalink to latest

Thank you so much problem solved.
