### ISSUE TITLE
Hello. When I try to play an age restricted video on YouTube, it does not play with the message "Track information is unavailable."

### ISSUE THREAD

**Issue by shfancy** [lavalink-devs/Lavalink#406]
## Description
Hello. When I try to play an age restricted video on YouTube, it does not play with this message.

In my opinion, it seems to be related to a video that previously had an age restriction, but it was played on the embed page, but it has not been done recently.

How can I do it? It is downloaded to youtube-dl, but I don't know why...

## Version info
**Client used:** lavalink 3.3.2.1

Output of `java -version`:
```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

lavalink log:
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Track information is unavailable.
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackBaseInfoFromEmbedPage(DefaultYoutubeTrackDetailsLoader.java:199) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:83) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:54) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:40) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.53.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.IllegalStateException: Expected player config is not present in embed page.
        ... 11 common frames omitted
```

**Comment by freyacodes** [comment]
You're using an outdated version

**Comment by DaliborTrampota** [comment]
I have the newest 1.3.67 and get this error as well

**Comment by MidnightInsomnia** [comment]
Same. Please update LavaPlayer version in Lavalink

**Comment by topi314** [comment]
just use the latest dev release

**Comment by MidnightInsomnia** [comment]
I am using latest version of Lavalink (#1209 Build 17 Feb 23:22). Still got issue #441. Judging by the discussions in the LavaPlayer repository, such problems are fixed in the new versions (Newest version of LavaPlayer is 1.3.71, Current in Lavalink - 1.3.65). 
In the CHANGELOG we can see, that this issue was fixed in 1.3.69

https://github.com/sedmelluq/lavaplayer/blob/1.3.71/CHANGELOG.md

**Comment by topi314** [comment]
#1209 is master and not dev branch.

**Comment by MidnightInsomnia** [comment]
> #1209 is master and not dev branch.

I'm sorry if it is stupid question, but where can i find dev branch?

**Comment by MidnightInsomnia** [comment]
It works! I can finally enjoy listening to Ram Ranch 2! Thank you!

Build #1210 fixed my problem.

**Comment by topi314** [comment]
dev branch currently has filters which are not yet merged to master
maybe soon
