### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by Samir-OP** [lavalink-devs/Lavalink#410]
## Description
I just played a song..

## Version info
**Client used:** Erela.js

Output of `java -version`:
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

## lavalink logs
```
2020-12-05 23:47:36.654  INFO 9084 --- [           main] lavalink.server.Launcher                 :

[32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[0m    =========================================[32m/_/_/_/[0m

        Version:        3.3.2.2
        Build:          1155
        Build time:     28.11.2020 11:50:13 UTC
        Branch          dev
        Commit:         23c883a
        Commit time:    28.11.2020 11:42:10 UTC
        JVM:            11
        Lavaplayer      1.3.61

2020-12-05 23:47:37.029  INFO 9084 --- [           main] lavalink.server.Launcher                 : Starting Launcher on WIN-JG1E0O7FSBS with PID 9084 (C:\Users\DynamoYT\Desktop\Lavalink\LAVA\Lavalink (1).jar started by DynamoYT in C:\Users\DynamoYT\Desktop\Lavalink\LAVA)
2020-12-05 23:47:37.115  INFO 9084 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2020-12-05 23:47:37.151  WARN 9084 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2020-12-05 23:47:41.178  WARN 9084 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2020-12-05 23:47:41.339  INFO 9084 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2020-12-05 23:47:41.341  INFO 9084 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 4039 ms
2020-12-05 23:47:42.354  WARN 9084 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2020-12-05 23:47:42.756  INFO 9084 --- [           main] c.s.l.e.y.tools.ip.Ipv6Block             : Using Ipv6Block with 18446744073709551616 addresses
2020-12-05 23:47:42.840  INFO 9084 --- [           main] c.s.l.e.y.planner.AbstractRoutePlanner   : Active RoutePlanner: com.sedmelluq.lava.extensions.youtuberotator.planner.RotatingIpRoutePlanner using total of 18446744073709551616 ips
2020-12-05 23:47:43.842  INFO 9084 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2020-12-05 23:47:44.410  INFO 9084 --- [           main] lavalink.server.config.KoeConfiguration  : OS: Windows Server 2016, Arch: amd64
2020-12-05 23:47:44.412  WARN 9084 --- [           main] lavalink.server.config.KoeConfiguration  : This system and architecture appears to not support native audio sending! GC pauses may cause your bot to stutter during playback.
2020-12-05 23:47:45.241  INFO 9084 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-12-05 23:47:46.373  INFO 9084 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2020-12-05 23:47:46.424  INFO 9084 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2020-12-05 23:47:46.572  INFO 9084 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2020-12-05 23:47:46.591  INFO 9084 --- [           main] lavalink.server.Launcher                 : Started Launcher in 12.171 seconds (JVM running for 14.745)
2020-12-05 23:47:46.644  INFO 9084 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/Frederikam/Lavalink/issues/295
2020-12-05 23:50:01.425  INFO 9084 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-12-05 23:50:01.427  INFO 9084 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-12-05 23:50:01.445  INFO 9084 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 14 ms
2020-12-05 23:50:01.497  INFO 9084 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:58940
2020-12-05 23:50:01.674  INFO 9084 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:58940
2020-12-05 23:50:09.053  INFO 9084 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"746653541115887637","volume":100}
2020-12-05 23:50:09.113  INFO 9084 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:mirhci"
2020-12-05 23:50:09.341  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:11 as new outgoing ip
2020-12-05 23:50:09.359  INFO 9084 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"e7262716a54dd7cd6be9e88977166329","op":"voiceUpdate","guildId":"746653541115887637","event":{"token":"2427ce21c9bbae73","guild_id":"746653541115887637","endpoint":"india91.discord.media:443"}}
2020-12-05 23:50:09.406  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:11, marking address as failing and retry!
2020-12-05 23:50:09.422  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:20 as new outgoing ip
2020-12-05 23:50:09.427  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:20, marking address as failing and retry!
2020-12-05 23:50:09.428  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:33 as new outgoing ip
2020-12-05 23:50:09.428  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:33, marking address as failing and retry!
2020-12-05 23:50:09.428  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:40 as new outgoing ip
2020-12-05 23:50:09.437  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:40, marking address as failing and retry!
2020-12-05 23:50:09.441  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:50 as new outgoing ip
2020-12-05 23:50:09.446  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:50, marking address as failing and retry!
2020-12-05 23:50:09.468 ERROR 9084 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item ytsearch:mirhci

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:237) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:226) ~[lavaplayer-1.3.61.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.RuntimeException: com.sedmelluq.lava.extensions.youtuberotator.tools.RateLimitException: Retry aborted, too many retries on ratelimit.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:58) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:77) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:254) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:220) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:34) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:188) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:127) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.61.jar!/:na]
        ... 4 common frames omitted
Caused by: com.sedmelluq.lava.extensions.youtuberotator.tools.RateLimitException: Retry aborted, too many retries on ratelimit.
        at com.sedmelluq.lava.extensions.youtuberotator.YoutubeIpRotatorFilter.limitedRetry(YoutubeIpRotatorFilter.java:114) ~[lavaplayer-ext-youtube-rotator-0.2.3.jar!/:na]
        at com.sedmelluq.lava.extensions.youtuberotator.YoutubeIpRotatorFilter.onRequestException(YoutubeIpRotatorFilter.java:102) ~[lavaplayer-ext-youtube-rotator-0.2.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequestException(SettableHttpRequestFilter.java:61) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:79) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:67) ~[lavaplayer-1.3.61.jar!/:na]
        ... 12 common frames omitted

2020-12-05 23:50:09.477 ERROR 9084 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:237) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:226) ~[lavaplayer-1.3.61.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.RuntimeException: com.sedmelluq.lava.extensions.youtuberotator.tools.RateLimitException: Retry aborted, too many retries on ratelimit.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:58) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:77) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:254) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:220) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:34) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:188) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:127) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.61.jar!/:na]
        ... 4 common frames omitted
Caused by: com.sedmelluq.lava.extensions.youtuberotator.tools.RateLimitException: Retry aborted, too many retries on ratelimit.
        at com.sedmelluq.lava.extensions.youtuberotator.YoutubeIpRotatorFilter.limitedRetry(YoutubeIpRotatorFilter.java:114) ~[lavaplayer-ext-youtube-rotator-0.2.3.jar!/:na]
        at com.sedmelluq.lava.extensions.youtuberotator.YoutubeIpRotatorFilter.onRequestException(YoutubeIpRotatorFilter.java:102) ~[lavaplayer-ext-youtube-rotator-0.2.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequestException(SettableHttpRequestFilter.java:61) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:79) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:67) ~[lavaplayer-1.3.61.jar!/:na]
        ... 12 common frames omitted

2020-12-05 23:50:09.489 ERROR 9084 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:237) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:226) ~[lavaplayer-1.3.61.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.RuntimeException: com.sedmelluq.lava.extensions.youtuberotator.tools.RateLimitException: Retry aborted, too many retries on ratelimit.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:58) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:77) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:254) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:220) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:34) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:188) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:127) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.61.jar!/:na]
        ... 4 common frames omitted
Caused by: com.sedmelluq.lava.extensions.youtuberotator.tools.RateLimitException: Retry aborted, too many retries on ratelimit.
        at com.sedmelluq.lava.extensions.youtuberotator.YoutubeIpRotatorFilter.limitedRetry(YoutubeIpRotatorFilter.java:114) ~[lavaplayer-ext-youtube-rotator-0.2.3.jar!/:na]
        at com.sedmelluq.lava.extensions.youtuberotator.YoutubeIpRotatorFilter.onRequestException(YoutubeIpRotatorFilter.java:102) ~[lavaplayer-ext-youtube-rotator-0.2.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequestException(SettableHttpRequestFilter.java:61) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:79) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:67) ~[lavaplayer-1.3.61.jar!/:na]
        ... 12 common frames omitted
```
## output of "java -jar Lavalink.jar --version"

```
Version:        3.3.2.2
Build:          1155
Build time:     28.11.2020 11:50:13 UTC
Branch          dev
Commit:         23c883a
Commit time:    28.11.2020 11:42:10 UTC
JVM:            11
Lavaplayer      1.3.61
```

**Comment by duncte123** [comment]
Download the latest version from the ci, your build is outdated

**Comment by Samir-OP** [comment]
what is ci?

**Comment by eepymoonshine** [comment]
https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1

**Comment by eepymoonshine** [comment]
Eitherway, looking at your logs, your IPs have been banned from Youtube. Using the latest build won't help you, besides being more clear about what happened :)

```
2020-12-05 23:50:09.341  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:11 as new outgoing ip
2020-12-05 23:50:09.359  INFO 9084 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"e7262716a54dd7cd6be9e88977166329","op":"voiceUpdate","guildId":"746653541115887637","event":{"token":"2427ce21c9bbae73","guild_id":"746653541115887637","endpoint":"india91.discord.media:443"}}
2020-12-05 23:50:09.406  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:11, marking address as failing and retry!
2020-12-05 23:50:09.422  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:20 as new outgoing ip
2020-12-05 23:50:09.427  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:20, marking address as failing and retry!
2020-12-05 23:50:09.428  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:33 as new outgoing ip
2020-12-05 23:50:09.428  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:33, marking address as failing and retry!
2020-12-05 23:50:09.428  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:40 as new outgoing ip
2020-12-05 23:50:09.437  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:40, marking address as failing and retry!
2020-12-05 23:50:09.441  INFO 9084 --- [ader-2-thread-1] c.s.l.e.y.p.RotatingIpRoutePlanner       : Selected /2001:470:b862:0:0:0:0:50 as new outgoing ip
2020-12-05 23:50:09.446  WARN 9084 --- [ader-2-thread-1] c.s.l.e.y.YoutubeIpRotatorFilter         : Cannot assign requested address /2001:470:b862:0:0:0:0:50, marking address as failing and retry!
2020-12-05 23:50:09.468 ERROR 9084 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item ytsearch:mirhci
```

`com.sedmelluq.lava.extensions.youtuberotator.tools.RateLimitException: Retry aborted, too many retries on ratelimit`

**Comment by Samir-OP** [comment]
So what I have to do to unban it from YouTube?
