### ISSUE TITLE
after running lavalink for 20 minutes i get this error.

### ISSUE THREAD

**Issue by kpopdev** [lavalink-devs/Lavalink#412]
## Description
<i have to restart lavalink always or else im getting this error also the ip rotataion settings and everything is fine bc my bot working good when i start it but after playing 5 or more songs im getting that error and it wont play anymore.it just join vc and leave.>

## Version info
**Client used:** <v3.3.2.2>

Output of `java -version`:

13
```

<!-- 2020-12-11 03:41:09.410  INFO 1817 --- [XNIO-1 task-4] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:twice better"
2020-12-11 03:41:10.388  INFO 1817 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: twice better
2020-12-11 03:41:10.401  INFO 1817 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"track":"QAAAnAIAHlRXSUNFIOOAjEJFVFRFUuOAjSBNdXNpYyBWaWRlbwAkVFdJQ0UgSkFQQU4gT0ZGSUNJQUwgWW91VHViZSBDaGFubmVsAAAAAAADdrgAC3NMbUx3Z3huUFVFAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9c0xtTHdneG5QVUUAB3lvdXR1YmUAAAAAAAAAAA==","op":"play","guildId":"760364973423067198"}
2020-12-11 03:41:10.560  INFO 1817 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"9a23652dc838f42bc49827a3e5ee886d","event":{"token":"6b3e93a34956a0a1","guild_id":"760364973423067198","endpoint":"russia297.discord.media:443"},"op":"voiceUpdate","guildId":"760364973423067198"}
2020-12-11 03:41:11.662 ERROR 1817 --- [lava-daemon-pool-playback-1-thread-10] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of sLmLwgxnPUE

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.62.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:117) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:151) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:167) ~[lavaplayer-1.3.62.jar!/:na]
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.62.jar!/:na]
	... 4 common frames omitted

2020-12-11 03:41:11.682  INFO 1817 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"760364973423067198"}
2020-12-11 03:41:29.848  INFO 1817 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:50338 -- CloseStatus[code=1000, reason=]
2020-12-11 03:41:29.849  INFO 1817 --- [XNIO-1 I/O-2] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2020-12-11 03:41:29.856  INFO 1817 --- [XNIO-1 task-3] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:50612
2020-12-11 03:41:29.864  INFO 1817 --- [XNIO-1 task-3] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:50612
2020-12-11 03:41:36.777  INFO 1817 --- [XNIO-1 task-16] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:twice better"
2020-12-11 03:41:37.762  INFO 1817 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: twice better
2020-12-11 03:41:37.767  INFO 1817 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"track":"QAAAnAIAHlRXSUNFIOOAjEJFVFRFUuOAjSBNdXNpYyBWaWRlbwAkVFdJQ0UgSkFQQU4gT0ZGSUNJQUwgWW91VHViZSBDaGFubmVsAAAAAAADdrgAC3NMbUx3Z3huUFVFAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9c0xtTHdneG5QVUUAB3lvdXR1YmUAAAAAAAAAAA==","op":"play","guildId":"760364973423067198"}
2020-12-11 03:41:37.926  INFO 1817 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"df32355bc86b90a889c364734050d04f","event":{"token":"fafb58008bee492c","guild_id":"760364973423067198","endpoint":"russia297.discord.media:443"},"op":"voiceUpdate","guildId":"760364973423067198"}
2020-12-11 03:41:39.086  INFO 1817 --- [XNIO-1 task-11] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:stop"
2020-12-11 03:41:39.112 ERROR 1817 --- [lava-daemon-pool-playback-1-thread-11] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of sLmLwgxnPUE

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.62.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.RuntimeException: Not success status code: 403
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:117) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:151) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:167) ~[lavaplayer-1.3.62.jar!/:na]
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-1.3.62.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.62.jar!/:na]
	... 4 common frames omitted

2020-12-11 03:41:39.126  INFO 1817 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"760364973423067198"}
2020-12-11 03:41:40.113  INFO 1817 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: stop -->

**Comment by Matcheryt** [comment]
Also getting the same error. My bot started skipping every song from a playlist with hundreds of songs, and was only playing very few of them. Maybe youtube rate limited? But then the bot wouldn't be able to play any music at all, but it plays some songs.

### Versions:
```
        Java:
        openjdk version "13.0.4" 2020-07-14
        
        Lavalink:
        Version:        3.3.2.2
        Build:          1155
        Build time:     28.11.2020 11:50:13 UTC
        Branch          dev
        Commit:         23c883a
        Commit time:    28.11.2020 11:42:10 UTC
        JVM:            13.0.4
        Lavaplayer      1.3.61
```
### Exception:
```
2020-12-21 21:56:02.901  INFO 86873 --- [ XNIO-1 task-10] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=aP6orw0M-bY"
2020-12-21 21:56:03.099  INFO 86873 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"guildId":"297435935178752012","sessionId":"4b350c007f873069286e3e8396eec064","event":{"token":"c8cb781a9fe0081c","endpoint":"eu-central986.discord.media:443"},"op":"voiceUpdate"}
2020-12-21 21:56:03.241  INFO 86873 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Os Azeitonas - Quem és tu miúda
2020-12-21 21:56:03.251  INFO 86873 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"endTime":255000,"track":"QAAAjwIAIU9zIEF6ZWl0b25hcyAtIFF1ZW0gw6lzIHR1IG1pw7pkYQAUTWlndWVsIEFyYcO6am8gSm9yZ2UAAAAAAAPkGAALYVA2b3J3ME0tYlkAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1hUDZvcncwTS1iWQAHeW91dHViZQAAAAAAAAAA","noReplace":false,"startTime":0,"guildId":"297435935178752012","op":"play"}
2020-12-21 21:56:03.622 ERROR 86873 --- [ack-1-thread-11] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of aP6orw0M-bY

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.61.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-1.3.61.jar!/:na]        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:117) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:151) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:167) ~[lavaplayer-1.3.61.jar!/:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-1.3.61.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.61.jar!/:na]
        ... 4 common frames omitted

2020-12-21 21:56:03.651  INFO 86873 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"guildId":"297435935178752012","op":"stop"}
2020-12-21 21:56:03.652  INFO 86873 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"guildId":"297435935178752012","op":"stop"}
2020-12-21 21:56:03.652  INFO 86873 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"guildId":"297435935178752012","op":"destroy"}
```

**Comment by arynxd** [comment]
403 Suggests that you were banned from Youtube

**Comment by kpopdev** [comment]
i guess i close this ticket i fixed my bot with RotatingNanoSwitch. so all good now.
