### ISSUE TITLE
Lavalink not conecting With Discord Py Bot

### ISSUE THREAD

**Issue by Waffelcek** [lavalink-devs/Lavalink#426]
I don't know what's wrong and I don't understand it but I think its something with ports

Lavalink:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (jar:file:/home/jakob/Bot/Plexi/jdk-11.0.1/bin/Lavalink.jar!/BOOT-INF/lib/xnio-nio-3.3.8.Final.jar!/) to constructor sun.nio.ch.EPollSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Discord Bot
```
WEBSOCKET | Connection Failure:: Cannot connect to host 127.0.0.1:2333 ssl:default [Connect call failed ('127.0.0.1', 2333)]
Traceback (most recent call last):
  File "/home/jakob/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1017, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1002, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 916, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 485, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 517, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 2333)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jakob/.local/lib/python3.8/site-packages/wavelink/websocket.py", line 76, in _connect
    self._websocket = await self._node.session.ws_connect(uri, headers=self.headers, heartbeat=self._node.heartbeat)
  File "/home/jakob/.local/lib/python3.8/site-packages/aiohttp/client.py", line 721, in _ws_connect
    resp = await self.request(method, url,
  File "/home/jakob/.local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/home/jakob/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/jakob/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/home/jakob/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/jakob/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/jakob/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:2333 ssl:default [Connect call failed ('127.0.0.1', 2333)]```

**Comment by freyacodes** [comment]
Looks like Lavalink is not running on `127.0.0.1:2333`. The log fragment from lavalink is harmless.

**Comment by Waffelcek** [comment]
What does this mean?

`Authorization Failed for Node:: MAIN | europe | (Shard: None)`

**Comment by freyacodes** [comment]
This issue tracker is not general support. Please use the discord channel for that.

It appears you are using the wrong password.
