### ISSUE TITLE
UnknownHostException

### ISSUE THREAD

**Issue by lunaseraphica** [lavalink-devs/Lavalink#469]
2021-04-09 14:48:01.180 ERROR 134 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of Y8481t8EHOU

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.74.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.74
  os.arch: amd64
  os.name: Linux
  os.version: 4.19.0-16-amd64
  java.vendor: Oracle Corporation
  java.version: 13.0.2
  java.runtime.version: 13.0.2+8
  java.vm.version: 13.0.2+8
Caused by: java.lang.RuntimeException: java.net.UnknownHostException: r5---sn-4g5e6nze.googlevideo.com: Temporary failure in name resolution
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:56) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.74.jar!/:na]
        ... 4 common frames omitted
Caused by: java.net.UnknownHostException: r5---sn-4g5e6nze.googlevideo.com: Temporary failure in name resolution
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:930) ~[na:na]
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1499) ~[na:na]
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:849) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1489) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1348) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1282) ~[na:na]
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.10.jar!/:4.5.10]
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.resolveAddresses(ExtendedConnectionOperator.java:138) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connect(ExtendedConnectionOperator.java:69) ~[lavaplayer-1.3.74.jar!/:na]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar!/:4.5.10]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:113) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:150) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:166) ~[lavaplayer-1.3.74.jar!/:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78) ~[lavaplayer-1.3.74.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.3.74.jar!/:na]
        ... 9 common frames omitted

**Comment by freyacodes** [comment]
> UnknownHostException: r5---sn-4g5e6nze.googlevideo.com: Temporary failure in name resolution

Looks like a network failure on your end.

**Comment by Nuzair46** [comment]
Im having this exact same issue. The code or config is untouched and i'm using the latest Lavalink.

**Comment by zabihexes** [comment]
I am having a similliar issue running lavalink via [docker](https://hub.docker.com/r/fredboat/lavalink).
Restarting the container usually fixes it. Any idea for a better fix?
**Error:**
```console
lavalink_1     | 2021-05-26T13:05:39.414680830Z com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
lavalink_1     | 2021-05-26T13:05:39.414691477Z         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414702112Z         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:236) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414712560Z         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:225) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414723123Z         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
lavalink_1     | 2021-05-26T13:05:39.414744756Z         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
lavalink_1     | 2021-05-26T13:05:39.414755662Z         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
lavalink_1     | 2021-05-26T13:05:39.414765857Z         at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
lavalink_1     | 2021-05-26T13:05:39.414775836Z         Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
lavalink_1     | 2021-05-26T13:05:39.414785909Z   lavaplayer.version: 1.3.76
lavalink_1     | 2021-05-26T13:05:39.414795638Z   os.arch: amd64
lavalink_1     | 2021-05-26T13:05:39.414805145Z   os.name: Linux
lavalink_1     | 2021-05-26T13:05:39.414826935Z   os.version: 5.10.29-0-lts
lavalink_1     | 2021-05-26T13:05:39.414840547Z   java.vendor: Azul Systems, Inc.
lavalink_1     | 2021-05-26T13:05:39.414850160Z   java.version: 13.0.2
lavalink_1     | 2021-05-26T13:05:39.414859639Z   java.runtime.version: 13.0.2+6-MTS
lavalink_1     | 2021-05-26T13:05:39.414869218Z   java.vm.version: 13.0.2+6-MTS
lavalink_1     | 2021-05-26T13:05:39.414878807Z Caused by: java.lang.RuntimeException: java.net.UnknownHostException: www.youtube.com
lavalink_1     | 2021-05-26T13:05:39.414901733Z         at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:58) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414912943Z         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:74) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414923616Z         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:262) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414935896Z         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:228) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414961602Z         at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:35) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414985257Z         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.414996141Z         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:131) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.415007212Z         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.415017633Z         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.415028379Z         at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.415038972Z         ... 4 common frames omitted
lavalink_1     | 2021-05-26T13:05:39.415070287Z Caused by: java.net.UnknownHostException: www.youtube.com
lavalink_1     | 2021-05-26T13:05:39.415080810Z         at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:798) ~[na:na]
lavalink_1     | 2021-05-26T13:05:39.415091042Z         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1489) ~[na:na]
lavalink_1     | 2021-05-26T13:05:39.415100982Z         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1348) ~[na:na]
lavalink_1     | 2021-05-26T13:05:39.415110958Z         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1282) ~[na:na]
lavalink_1     | 2021-05-26T13:05:39.415132315Z         at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415143900Z         at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.resolveAddresses(ExtendedConnectionOperator.java:138) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.415154829Z         at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connect(ExtendedConnectionOperator.java:69) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.415165506Z         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415177419Z         at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415188168Z         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415209095Z         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415220551Z         at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415230945Z         at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415249884Z         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415261039Z         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar!/:4.5.10]
lavalink_1     | 2021-05-26T13:05:39.415271324Z         at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.415293493Z         at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:67) ~[lavaplayer-1.3.76.jar!/:na]
lavalink_1     | 2021-05-26T13:05:39.415304964Z         ... 12 common frames omitted
lavalink_1     | 2021-05-26T13:05:39.415314844Z
lavalink_1     | 2021-05-26T13:05:39.415407880Z 2021-05-26 13:05:39.414 ERROR 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed
```
