### ISSUE TITLE
NullPointerException in websocket when playing track

### ISSUE THREAD

**Issue by itsfolf** [lavalink-devs/Lavalink#47]
I'm getting this error on the LavaLink log when adding a track trought IPlayer#playTrack

```
[13:17:00] [ INFO ] [SocketServer] {"op":"play","startTime":0,"track":"QAAAlQIAHlZhdGUgTWMgLSBSdW1vIChwcm9kLiBUw7N4aWNvKQANTWFsQW1hZG9zUHJvZAAAAAAAA7U4AAtmUnJWYm5ZblIyZwABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PWZSclZiblluUjJnABdzcG90aWZ5X3BsYXlsaXN0X2ltcG9ydAAAAAAAAAAA","guildId":"219254781384851467","pause":false}
[13:17:00] [ ERROR] [SocketServer] Caught exception in websocket
java.lang.NullPointerException: null
        at lavalink.server.io.SocketServer.onMessage(SocketServer.java:158)
        at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:524)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:417)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:170)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:781)
```

**Comment by freyacodes** [comment]
What version of the server are you using? I would look at line 158 of SocketServer.java, but it is only 146 lines long.

**Comment by itsfolf** [comment]
I'm using v1.5.8.RELEASE, also, I was able to fix the NullPointerException by fixing the source manager name in the base64 wich was wrong. But now all it does is log the json into the console but doesn't play.

EDIT: It also seems to be requesting permission, guild and channel check infinitely, not sure if that's normal

**Comment by freyacodes** [comment]
`v1.5.8.RELEASE`

???

That's a Spring Boot version and has nothing to do with this. 

What do you mean the base64 was wrong?

**Comment by itsfolf** [comment]
That's all I was able to find in the console, where do I check for the version then?

In the base64 of the error I sent here the source manager was set to spotify because of an error in my code, I now changed it to youtube and the NullPointerException is no longer firing, but it's still not playing.

**Comment by freyacodes** [comment]
Closing this issue as it was supposedly solved judging by your DM messages
