### ISSUE TITLE
m3u8 Playback - Failed to get next part of the stream.

### ISSUE THREAD

**Issue by Luc1412** [lavalink-devs/Lavalink#493]
## Description
I got following valid m3u8 stream: https://fortnite-vod.akamaized.net/hgsuJcchvKuaEzzijr/b06f21e1-ab7f-4db7-ad86-a461d15e7a9c/master_es_ES.m3u8 which I like to replay with lavalink. When starting the playback it crash.

## Version info
Version:        2ac6bf4e0dcab9ba7493b0494316b8bee698913d-SNAPSHOT
Build:          1232
Build time:     20.04.2021 07:05:21 UTC
Branch          master
Commit:         2ac6bf4
Commit time:    20.04.2021 07:02:46 UTC
JVM:            13.0.2
Lavaplayer      1.3.76

Output of `java -version`:
![image](https://user-images.githubusercontent.com/24532065/120248162-5ef55d00-c276-11eb-92ed-af3b50e5bef0.png)

```
2021-05-31 23:12:33.332  INFO 1 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://fortnite-vod.akamaized.net/hgsuJcchvKuaEzzijr/b06f21e1-ab7f-4db7-ad86-a461d15e7a9c/master_es_ES.m3u8"
2021-05-31 23:12:33.374  INFO 1 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "443432012095946753", "sessionId": "684853bc7c77899f80e4bf927cb52bf4", "event": {"token": "0f3be14f6189e754", "guild_id": "443432012095946753", "endpoint": "eu-central4608.discord.media:443"}}
2021-05-31 23:12:33.709  INFO 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Unknown title
2021-05-31 23:12:33.750  INFO 1 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "443432012095946753", "track": "QAABIwIADVVua25vd24gdGl0bGUADlVua25vd24gYXJ0aXN0f/////////8AbGh0dHBzOi8vZm9ydG5pdGUtdm9kLmFrYW1haXplZC5uZXQvaGdzdUpjY2h2S3VhRXp6aWpyL2IwNmYyMWUxLWFiN2YtNGRiNy1hZDg2LWE0NjFkMTVlN2E5Yy9tYXN0ZXJfZXNfRVMubTN1OAEBAGxodHRwczovL2ZvcnRuaXRlLXZvZC5ha2FtYWl6ZWQubmV0L2hnc3VKY2Nodkt1YUV6emlqci9iMDZmMjFlMS1hYjdmLTRkYjctYWQ4Ni1hNDYxZDE1ZTdhOWMvbWFzdGVyX2VzX0VTLm0zdTgABGh0dHAADW0zdXxobHMtb3V0ZXIAAAAAAAAAAA==", "noReplace": false, "startTime": "0"}
2021-05-31 23:12:33.779  INFO 1 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$552/0x000000080117c440@350864b4
2021-05-31 23:12:33.779  INFO 1 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2021-05-31 23:12:33.815  INFO 1 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: successfully loaded.
2021-05-31 23:12:33.883  WARN 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of https://fortnite-vod.akamaized.net/hgsuJcchvKuaEzzijr/b06f21e1-ab7f-4db7-ad86-a461d15e7a9c/master_es_ES.m3u8


com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Failed to get next part of the stream.
	at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamSegmentUrlProvider.getNextSegmentUrl(M3uStreamSegmentUrlProvider.java:79) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamSegmentUrlProvider.getNextSegmentStream(M3uStreamSegmentUrlProvider.java:92) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamAudioTrack.lambda$process$0(M3uStreamAudioTrack.java:33) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.ChainedInputStream.loadNextStream(ChainedInputStream.java:25) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.ChainedInputStream.read(ChainedInputStream.java:55) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.GreedyInputStream.read(GreedyInputStream.java:23) ~[lavaplayer-1.3.76.jar!/:na]
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.container.mpegts.MpegTsElementaryInputStream.processPacket(MpegTsElementaryInputStream.java:132) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mpegts.MpegTsElementaryInputStream.findElementaryData(MpegTsElementaryInputStream.java:113) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mpegts.MpegTsElementaryInputStream.read(MpegTsElementaryInputStream.java:87) ~[lavaplayer-1.3.76.jar!/:na]
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.container.mpegts.PesPacketInputStream.makeBytesAvailable(PesPacketInputStream.java:38) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mpegts.PesPacketInputStream.read(PesPacketInputStream.java:74) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamReader.scanForPacketHeader(AdtsStreamReader.java:76) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamReader.findPacketHeader(AdtsStreamReader.java:59) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamReader.findPacketHeader(AdtsStreamReader.java:46) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsStreamProvider.provideFrames(AdtsStreamProvider.java:62) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.adts.AdtsAudioTrack.process(AdtsAudioTrack.java:35) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.stream.MpegTsM3uStreamAudioTrack.processJoinedStream(MpegTsM3uStreamAudioTrack.java:25) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamAudioTrack.process(M3uStreamAudioTrack.java:34) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:53) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.76.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.76
  os.arch: amd64
  os.name: Linux
  os.version: 4.19.0-16-amd64
  java.vendor: Azul Systems, Inc.
  java.version: 13.0.2
  java.runtime.version: 13.0.2+6-MTS
  java.vm.version: 13.0.2+6-MTS

Caused by: org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187) ~[httpclient-4.5.10.jar!/:4.5.10]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar!/:4.5.10]
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseLines(HttpClientTools.java:264) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamSegmentUrlProvider.loadStreamSegmentsList(M3uStreamSegmentUrlProvider.java:144) ~[lavaplayer-1.3.76.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.stream.M3uStreamSegmentUrlProvider.getNextSegmentUrl(M3uStreamSegmentUrlProvider.java:62) ~[lavaplayer-1.3.76.jar!/:na]
	... 29 common frames omitted
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71) ~[httpclient-4.5.10.jar!/:4.5.10]
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125) ~[httpclient-4.5.10.jar!/:4.5.10]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.10.jar!/:4.5.10]
	... 34 common frames omitted
```

**Comment by Muh9049** [comment]
@Luc1412 I just tried this link, and yes the same error also occurs. This doesn’t seem to be a Lavalink issue though, instead it seems to be a Lavaplayer issue. This specific link does not work with any other music bots either and returns the same error.

Might be better if you create an issue about this on the Lavaplayer GitHub 🤔

**Comment by Luc1412** [comment]
Alright, I moved this issue to Lavaplayer
