### ISSUE TITLE
Soundcloud is not working

### ISSUE THREAD

**Issue by varma02** [lavalink-devs/Lavalink#507]
## Description

When I want to play a soundcloud song, from my Discord.py bot, this error happens.
I'm using wavelink as a client.

## Version info
Docker hub: fredboat/lavalink:master

## Log
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.

at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.76.jar!/:na]

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]

at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:

lavaplayer.version: 1.3.76

os.arch: amd64

os.name: Linux

os.version: 5.10.16.3-microsoft-standard-WSL2

java.vendor: Azul Systems, Inc.

java.version: 13.0.2

java.runtime.version: 13.0.2+6-MTS

java.vm.version: 13.0.2+6-MTS

Caused by: java.io.IOException: Invalid status code for soundcloud stream: 401

at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudHelper.loadPlaybackUrl(SoundCloudHelper.java:22) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.loadSegments(SoundCloudM3uAudioTrack.java:50) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.createSegmentTracker(SoundCloudM3uAudioTrack.java:55) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.process(SoundCloudM3uAudioTrack.java:38) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.playFromIdentifier(SoundCloudAudioTrack.java:51) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:38) ~[lavaplayer-1.3.76.jar!/:na]

at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.76.jar!/:na]

... 4 common frames omitted
```

Output of `java -version`:
```
Docker: azul/zulu-openjdk:13
```

**Comment by freyacodes** [comment]
Try the dev version

**Comment by varma02** [comment]
Thanks, it works with dev.
