### ISSUE TITLE
Error 410 with some urls

### ISSUE THREAD

**Issue by zvshka** [lavalink-devs/Lavalink#511]
## Description

Some videos on YouTube trigger 410 error code

## Version info
**Client used:** 
Erela.js
Output of `java -version`:
```
JVM:            13.0.8
```

`
Logs 
`

```
2021-08-24 12:01:12.906 ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of R4KUvKUxQvw


com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.

at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.77.jar!/:na]

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]

at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 

  lavaplayer.version: 1.3.77

  os.arch: amd64

  os.name: Linux

  os.version: 5.10.16.3-microsoft-standard-WSL2

  java.vendor: Azul Systems, Inc.

  java.version: 13.0.8

  java.runtime.version: 13.0.8+5-MTS

  java.vm.version: 13.0.8+5-MTS

Caused by: java.lang.RuntimeException: Error when extracting data EID: 55a2f788-66aa-4453-850c-28462f24aa49, mainJson <redacted>

at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:70) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:45) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.77.jar!/:na]

... 4 common frames omitted

Caused by: java.io.IOException: Invalid status code for video info response: 410

at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:155) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackArgsFromVideoInfoPage(DefaultYoutubeTrackDetailsLoader.java:226) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:97) ~[lavaplayer-1.3.77.jar!/:na]

at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59) ~[lavaplayer-1.3.77.jar!/:na]

... 8 common frames omitted
```
`
Lavalink Version
`

```
       .   _                  _ _       _    __ _ _

      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \

     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \

      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )

       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /

    =========================================/_/_/_/


Version:        8125918d30a26e2739cefe8a7ce4b88ccb656d1e-SNAPSHOT

Build:          1234

Build time:     26.05.2021 12:32:38 UTC

Branch          dev

Commit:         8125918

Commit time:    26.05.2021 12:29:08 UTC

JVM:            13.0.8

Lavaplayer      1.3.77
```

**Comment by aikaterna** [comment]
If that's an age restricted track, it will be fixed when someone merges in <https://github.com/sedmelluq/lavaplayer/pull/649>, creates a new Lavaplayer release, and then that release is used in Lavalink.

**Comment by Midorina** [comment]
> If that's an age restricted track, it will be fixed when someone merges in [sedmelluq/lavaplayer#649](https://github.com/sedmelluq/lavaplayer/pull/649), creates a new Lavaplayer release, and then that release is used in Lavalink.

+1. Please do this.

**Comment by topi314** [comment]
https://github.com/freyacodes/Lavalink/pull/513 should have fixed that
(make sure to grab the latest version from the ci)
