### ISSUE TITLE
Error when connecting to the lavalink server.

### ISSUE THREAD

**Issue by AviDoesDev** [lavalink-devs/Lavalink#516]
## Description

Error when I connect to the server.
Same error occours on external host as well as my pc.

## Version info
**Client used:** erela.js-vk 

Output of `java -version`:
```
Java 16 docker image - quay.io/devil38/felix-dev:java16
(I can't change the docket image to the lavalink one because of hosting restrictions)
```

Lavalink logs:
```
2021-09-13 11:05:34.207  INFO 36 --- [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        3.3.2.5
        Build:          1222
        Build time:     11.04.2021 08:07:27 UTC
        Branch          master
        Commit:         7b914f2
        Commit time:    09.04.2021 17:14:27 UTC
        JVM:            16.0.1
        Lavaplayer      1.3.76

2021-09-13 11:05:34.392  INFO 36 --- [           main] o.s.boot.SpringApplication               : 
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.8.RELEASE)


2021-09-13 11:05:35.266  WARN 36 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2021-09-13 11:05:35.312  INFO 36 --- [           main] lavalink.server.Launcher                 : Starting Launcher on 0a9d2339-44c1-42fc-a462-05fa0ffcc6a1 with PID 36 (/home/container/server.jar started by ? in /home/container)
2021-09-13 11:05:35.418  INFO 36 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2021-09-13 11:05:43.176  WARN 36 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2021-09-13 11:05:43.248  INFO 36 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2021-09-13 11:05:43.249  INFO 36 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 7249 ms
2021-09-13 11:05:44.982  WARN 36 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2021-09-13 11:05:48.258  INFO 36 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2021-09-13 11:05:49.866  INFO 36 --- [           main] lavalink.server.config.KoeConfiguration  : OS: Linux, Arch: amd64
2021-09-13 11:05:49.867  INFO 36 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2021-09-13 11:05:49.878  INFO 36 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2021-09-13 11:05:49.908  INFO 36 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2021-09-13 11:05:53.063  INFO 36 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-09-13 11:05:55.283  INFO 36 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2021-09-13 11:05:55.329  INFO 36 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2021-09-13 11:05:56.258  INFO 36 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 25976 (http) with context path ''
2021-09-13 11:05:56.275  INFO 36 --- [           main] lavalink.server.Launcher                 : Started Launcher in 25.169 seconds (JVM running for 28.975)
2021-09-13 11:05:56.286  INFO 36 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/Frederikam/Lavalink/issues/295
2021-09-13 11:05:57.159  INFO 36 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-09-13 11:05:57.159  INFO 36 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-09-13 11:05:57.193  INFO 36 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 34 ms
2021-09-13 11:05:57.275  INFO 36 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /103.16x.xxx.xxx:51722
2021-09-13 11:05:58.115 ERROR 36 --- [  XNIO-1 task-1] w.s.h.ExceptionWebSocketHandlerDecorator : Closing session due to exception for StandardWebSocketSession[id=aaf8254e-4d12-ba2d-6038-0c09a24a9445, uri=/]

java.lang.NumberFormatException: For input string: "undefined"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:660) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:778) ~[na:na]
        at lavalink.server.io.SocketServer.afterConnectionEstablished(SocketServer.kt:72) ~[classes!/:na]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.afterConnectionEstablished(WebSocketHandlerDecorator.java:70) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.afterConnectionEstablished(LoggingWebSocketHandlerDecorator.java:48) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.afterConnectionEstablished(ExceptionWebSocketHandlerDecorator.java:48) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onOpen(StandardWebSocketHandlerAdapter.java:103) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at io.undertow.websockets.jsr.EndpointSessionHandler.onConnect(EndpointSessionHandler.java:129) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$4.handleUpgrade(ServerWebSocketContainer.java:466) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.protocol.http.HttpReadListener.exchangeComplete(HttpReadListener.java:385) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.protocol.http.HttpServerConnection.exchangeComplete(HttpServerConnection.java:232) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.HttpServerExchange.invokeExchangeCompleteListeners(HttpServerExchange.java:1279) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.HttpServerExchange.terminateResponse(HttpServerExchange.java:1563) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.Connectors.terminateResponse(Connectors.java:159) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:197) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:195) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.conduits.HeadStreamSinkConduit.exitFlush(HeadStreamSinkConduit.java:192) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.conduits.HeadStreamSinkConduit.flush(HeadStreamSinkConduit.java:133) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
        at io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at org.xnio.channels.Channels.flushBlocking(Channels.java:63) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
        at io.undertow.servlet.spec.ServletOutputStreamImpl.close(ServletOutputStreamImpl.java:618) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.spec.HttpServletResponseImpl.closeStreamAndWriter(HttpServletResponseImpl.java:528) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.spec.HttpServletResponseImpl.responseDone(HttpServletResponseImpl.java:617) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:328) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
```

**Comment by AviDoesDev** [comment]
Seems as the error was due to the fact that I was passing undefined as the shard count.
