### ISSUE TITLE
Invalid status code for video info response: 410

### ISSUE THREAD

**Issue by FriendlyButFire** [lavalink-devs/Lavalink#525]
## Description
Cannot play certain videos from YouTube

## Version info
latest

Output of `java -version`:
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

2021-09-23 19:33:21.565 ERROR 7345 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of ItM3yOtkXD4

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.76.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.76
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.128-1-pve
  java.vendor: Ubuntu
  java.version: 11.0.11
  java.runtime.version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
  java.vm.version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
Caused by: java.lang.RuntimeException: Error when extracting data EID: c4a72cd6-247b-414e-a4ff-dc2855abbf3c, mainJson <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:66) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:41) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:76) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.76.jar!/:na]
        ... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for video info response: 410
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:155) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackArgsFromVideoInfoPage(DefaultYoutubeTrackDetailsLoader.java:214) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:88) ~[lavaplayer-1.3.76.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:55) ~[lavaplayer-1.3.76.jar!/:na]
        ... 8 common frames omitted
![image](https://user-images.githubusercontent.com/20314571/134572476-41ace088-d129-45f9-b8aa-c5b2c76c89fd.png)

**Comment by aikaterna** [comment]
Use a Lavalink.jar from the dev branch instead, build 1244+ or greater on the Lavalink CI.
