### ISSUE TITLE
Can't play spotify links. org.json.JSONException: JSONObject["track"] not found.

### ISSUE THREAD

**Issue by lolliet** [lavalink-devs/Lavalink#531]
## Description
Can't play spotify links. `org.json.JSONException: JSONObject["track"] not found.` Youtube links works fine, but can't play using spotify links.

## Version info
**Client used:** @lavacord/discord.js - 0.0.7

Output of `java -version`:
```
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

on a side note my host computer is a debian 10 that runs java version 11.0.11. But the error happens on both the windows and debian.
```

**Lavalink Logs:**

```
[32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[0m    =========================================[32m/_/_/_/[0m

	Version:        3.3.2.5
	Build:          1222
	Build time:     11.04.2021 08:07:27 UTC
	Branch          master
	Commit:         7b914f2
	Commit time:    09.04.2021 17:14:27 UTC
	JVM:            17
	Lavaplayer      1.3.76

2021-10-03 10:48:46.732  INFO 7796 --- [main] lavalink.server.Launcher                 : Starting Launcher on DESKTOP-HDD9932 with PID 7796 (E:\Discord Workspace\Astrix Lavacord (v13)\Lavalink.jar started by zephy in E:\Discord Workspace\Astrix Lavacord (v13))
2021-10-03 10:48:46.734  INFO 7796 --- [main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2021-10-03 10:48:46.947  WARN 7796 --- [background-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2021-10-03 10:48:48.829  WARN 7796 --- [main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2021-10-03 10:48:48.874  INFO 7796 --- [main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2021-10-03 10:48:48.875  INFO 7796 --- [main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2042 ms
2021-10-03 10:48:49.461  WARN 7796 --- [main] l.server.config.SentryConfiguration      : Turning off sentry
2021-10-03 10:48:49.994  INFO 7796 --- [main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2021-10-03 10:48:50.407  INFO 7796 --- [main] lavalink.server.config.KoeConfiguration  : OS: Windows 10, Arch: amd64
2021-10-03 10:48:50.409  WARN 7796 --- [main] lavalink.server.config.KoeConfiguration  : This system and architecture appears to not support native audio sending! GC pauses may cause your bot to stutter during playback.
2021-10-03 10:48:50.920  INFO 7796 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-10-03 10:48:51.457  INFO 7796 --- [main] org.xnio                                 : XNIO version 3.3.8.Final
2021-10-03 10:48:51.479  INFO 7796 --- [main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2021-10-03 10:48:51.622  INFO 7796 --- [main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2021-10-03 10:48:51.630  INFO 7796 --- [main] lavalink.server.Launcher                 : Started Launcher in 6.054 seconds (JVM running for 7.096)
2021-10-03 10:48:51.634  INFO 7796 --- [main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/Frederikam/Lavalink/issues/295
2021-10-03 10:49:18.896  INFO 7796 --- [XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-10-03 10:49:18.896  INFO 7796 --- [XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-10-03 10:49:18.903  INFO 7796 --- [XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
2021-10-03 10:49:18.942  INFO 7796 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:49799
2021-10-03 10:49:19.152  INFO 7796 --- [XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:49799
2021-10-03 10:50:19.326  INFO 7796 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:49799 -- CloseStatus[code=1006, reason=]
2021-10-03 10:50:19.327  INFO 7796 --- [XNIO-1 I/O-3] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 10:50:30.814  INFO 7796 --- [XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:49809
2021-10-03 10:50:30.820  INFO 7796 --- [XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:49809
2021-10-03 10:50:50.287  INFO 7796 --- [XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:maps ly"
2021-10-03 10:50:51.732  INFO 7796 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: maps ly
2021-10-03 10:50:51.965  INFO 7796 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"track":"QAAAfwIAHU1hcm9vbiA1IC0gTWFwcyAoTHlyaWMgVmlkZW8pAAhNYXJvb24gNQAAAAAAAuJIAAtZN2l4NlJJVFhNMAABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVk3aXg2UklUWE0wAAd5b3V0dWJlAAAAAAAAAAA=","op":"play","guildId":"833567195261960222"}
2021-10-03 10:50:52.461  INFO 7796 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"sessionId":"b54412371388e06eca4c205ed11bfefa","event":{"token":"22ae89a3a0b39990","guild_id":"833567195261960222","endpoint":"india10009.discord.media:443"},"op":"voiceUpdate","guildId":"833567195261960222"}
2021-10-03 10:51:58.779  INFO 7796 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:49809 -- CloseStatus[code=1006, reason=]
2021-10-03 10:51:58.782  INFO 7796 --- [XNIO-1 I/O-1] lavalink.server.io.SocketContext         : Shutting down 1 playing players.
2021-10-03 10:52:08.631  INFO 7796 --- [XNIO-1 task-5] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:59288
2021-10-03 10:52:08.638  INFO 7796 --- [XNIO-1 task-5] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:59288
2021-10-03 10:52:10.567  INFO 7796 --- [XNIO-1 task-6] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:maps ly"
2021-10-03 10:52:11.507  INFO 7796 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: maps ly
2021-10-03 10:52:11.651  INFO 7796 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"track":"QAAAfwIAHU1hcm9vbiA1IC0gTWFwcyAoTHlyaWMgVmlkZW8pAAhNYXJvb24gNQAAAAAAAuJIAAtZN2l4NlJJVFhNMAABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVk3aXg2UklUWE0wAAd5b3V0dWJlAAAAAAAAAAA=","op":"play","guildId":"833567195261960222"}
2021-10-03 10:52:12.840  INFO 7796 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"sessionId":"8e0738f8dfd9c6eecd9af915a297624b","event":{"token":"22ae89a3a0b39990","guild_id":"833567195261960222","endpoint":"india10009.discord.media:443"},"op":"voiceUpdate","guildId":"833567195261960222"}
2021-10-03 10:56:28.396  INFO 7796 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:59288 -- CloseStatus[code=1006, reason=]
2021-10-03 10:56:28.399  INFO 7796 --- [XNIO-1 I/O-4] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 10:56:37.613  INFO 7796 --- [XNIO-1 task-8] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:55670
2021-10-03 10:56:37.622  INFO 7796 --- [XNIO-1 task-8] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:55670
2021-10-03 11:00:56.252  INFO 7796 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:55670 -- CloseStatus[code=1006, reason=]
2021-10-03 11:00:56.253  INFO 7796 --- [XNIO-1 I/O-2] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 11:01:05.171  INFO 7796 --- [XNIO-1 task-9] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:57917
2021-10-03 11:01:05.179  INFO 7796 --- [XNIO-1 task-9] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:57917
2021-10-03 11:02:38.713  INFO 7796 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:57917 -- CloseStatus[code=1006, reason=]
2021-10-03 11:02:38.716  INFO 7796 --- [XNIO-1 I/O-1] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 11:02:59.758  INFO 7796 --- [XNIO-1 task-10] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:55534
2021-10-03 11:02:59.764  INFO 7796 --- [XNIO-1 task-10] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:55534
2021-10-03 11:22:50.095  WARN 7796 --- [lava-daemon-pool-manager-3-thread-1] c.s.d.l.tools.GarbageCollectionMonitor   : Suspicious GC results for the last 2 minutes: [Bucket 0 = 0] [Bucket 20 = 0] [Bucket 50 = 0] [Bucket 200 = 0] [Bucket 500 = 1] [Bucket 2000 = 0] 
2021-10-03 11:48:45.301  INFO 7796 --- [XNIO-1 task-11] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:slchld - my stargirl Audio"
2021-10-03 11:48:46.555  INFO 7796 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: slchld - my stargirl Audio
2021-10-03 11:50:41.882  INFO 7796 --- [XNIO-1 task-13] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:slchld - she likes spring, I prefer winter Audio"
2021-10-03 11:50:43.021  INFO 7796 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: slchld - she likes spring, I prefer winter Audio
2021-10-03 11:54:41.889  INFO 7796 --- [XNIO-1 I/O-2] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:55534 -- CloseStatus[code=1006, reason=]
2021-10-03 11:54:41.906  INFO 7796 --- [XNIO-1 I/O-2] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 12:00:43.267  INFO 7796 --- [XNIO-1 task-15] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:60100
2021-10-03 12:00:43.525  INFO 7796 --- [XNIO-1 task-15] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:60100
2021-10-03 12:03:23.794  INFO 7796 --- [XNIO-1 I/O-4] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:60100 -- CloseStatus[code=1006, reason=]
2021-10-03 12:03:23.797  INFO 7796 --- [XNIO-1 I/O-4] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 12:03:29.217  INFO 7796 --- [XNIO-1 task-16] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:53349
2021-10-03 12:03:29.244  INFO 7796 --- [XNIO-1 task-16] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:53349
2021-10-03 12:03:40.008  INFO 7796 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:53349 -- CloseStatus[code=1006, reason=]
2021-10-03 12:03:40.015  INFO 7796 --- [XNIO-1 I/O-1] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 12:03:51.312  INFO 7796 --- [XNIO-1 task-17] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:50939
2021-10-03 12:03:51.316  INFO 7796 --- [XNIO-1 task-17] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:50939
2021-10-03 12:05:15.886  INFO 7796 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:50939 -- CloseStatus[code=1006, reason=]
2021-10-03 12:05:15.887  INFO 7796 --- [XNIO-1 I/O-3] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 12:05:21.911  INFO 7796 --- [XNIO-1 task-18] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:52083
2021-10-03 12:05:21.933  INFO 7796 --- [XNIO-1 task-18] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:52083
2021-10-03 12:15:10.622  INFO 7796 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:52083 -- CloseStatus[code=1006, reason=]
2021-10-03 12:15:10.623  INFO 7796 --- [XNIO-1 I/O-3] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2021-10-03 12:15:18.132  INFO 7796 --- [XNIO-1 task-19] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:55123
2021-10-03 12:15:18.135  INFO 7796 --- [XNIO-1 task-19] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:55123
2021-10-03 12:15:28.629  INFO 7796 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op":"play","guildId":"833567195261960222"}
2021-10-03 12:15:28.760 ERROR 7796 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : Exception while handling websocket message

org.json.JSONException: JSONObject["track"] not found.
	at org.json.JSONObject.get(JSONObject.java:566) ~[json-20180813.jar!/:na]
	at org.json.JSONObject.getString(JSONObject.java:851) ~[json-20180813.jar!/:na]
	at lavalink.server.io.WebSocketHandlers.play(WebSocketHandlers.kt:40) ~[classes!/:na]
	at lavalink.server.io.SocketServer.handleTextMessageSafe(SocketServer.kt:152) ~[classes!/:na]
	at lavalink.server.io.SocketServer.handleTextMessage(SocketServer.kt:129) ~[classes!/:na]
	at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:113) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:84) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:81) ~[spring-websocket-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:286) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:604) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:594) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.FrameHandler.invokeTextHandler(FrameHandler.java:266) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.FrameHandler.onFullTextMessage(FrameHandler.java:317) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.jsr.FrameHandler.onText(FrameHandler.java:182) ~[undertow-websockets-jsr-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:951) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:932) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
```

**Comment by topi314** [comment]
lavalink does not support playing from spotify
besides that you sent an invalid play payload missing the `track` node
```json
{
    "op": "play",
    "track": "base64 encoded track",
    "guildId":"833567195261960222"
}
```
or see here https://github.com/freyacodes/Lavalink/blob/master/IMPLEMENTATION.md#play-a-track
