### ISSUE TITLE
Soundcloud causing error again

### ISSUE THREAD

**Issue by vSilva-gb** [lavalink-devs/Lavalink#543]
## Description
I'm having this error when trying to play some soundcloud song

## Version info
3.3.2.3
**Client used:**
Erela.js

Output of `java -version`:
```
java 13.0.2 2020-01-14
```

2021-10-18 01:30:23.358  INFO 28628 --- [XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://soundcloud.com/rangel-br-313063877/waiting-for-love-funk-trap-remix-rangel-e-pmm"
2021-10-18 01:30:23.420  INFO 28628 --- [lava-daemon-pool-info-loader-2-thread-1] c.s.d.l.s.s.SoundCloudClientIdTracker    : Updating SoundCloud client ID (current is null).
2021-10-18 01:30:24.167 ERROR 28628 --- [lava-daemon-pool-info-loader-2-thread-1] c.s.d.l.s.s.SoundCloudClientIdTracker    : SoundCloud client ID update failed.

java.lang.IllegalStateException: Could not find client ID from application script.
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudClientIdTracker.findClientIdFromApplicationScript(SoundCloudClientIdTracker.java:116) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudClientIdTracker.findClientIdFromSite(SoundCloudClientIdTracker.java:79) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudClientIdTracker.updateClientId(SoundCloudClientIdTracker.java:52) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudClientIdTracker.getClientId(SoundCloudClientIdTracker.java:63) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudHttpContextFilter.onRequest(SoundCloudHttpContextFilter.java:47) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequest(SettableHttpRequestFilter.java:41) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:69) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.DefaultSoundCloudHtmlDataLoader.load(DefaultSoundCloudHtmlDataLoader.java:31) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadFromTrackPage(SoundCloudAudioSourceManager.java:202) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.processAsSingleTrack(SoundCloudAudioSourceManager.java:179) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioSourceManager.loadItem(SoundCloudAudioSourceManager.java:116) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.74.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.74.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

Version:        3.3.2.3
Build:          1176
Build time:     28.12.2020 18:59:16 UTC
Branch          master
Commit:         68d398a
Commit time:    28.12.2020 18:56:23 UTC
JVM:            13.0.2
Lavaplayer      1.3.65

**Comment by topi314** [comment]
use latest dev from the ci

**Comment by aikaterna** [comment]
Your Lavalink.jar is very out of date, grab a new one from the dev branch of the Lavalink CI. Current latest is at https://ci.fredboat.com/viewLog.html?buildId=8907&buildTypeId=Lavalink_Build&tab=artifacts&branch_Lavalink=refs%2Fheads%2Fdev - if it asks you for a username and password it's guest with no pw.
