### ISSUE TITLE
Heroku Hosting Error 

### ISSUE THREAD

**Issue by JackW25** [lavalink-devs/Lavalink#592]
## Description
Hi there, whenever I try to host my bot on Heroku, I get an error:

2022-01-02T19:08:24.510352+00:00 app[worker.1]: /app/node_modules/lavaclient/dist/lib/cluster/Cluster.js:23
2022-01-02T19:08:24.510410+00:00 app[worker.1]:         this.userId ??= user && (0, Utils_1.getId)(user);
2022-01-02T19:08:24.510417+00:00 app[worker.1]:                     ^^^
2022-01-02T19:08:24.510421+00:00 app[worker.1]: 
2022-01-02T19:08:24.510425+00:00 app[worker.1]: SyntaxError: Unexpected token '??='

## Version info
**Client used:** 

Output of `java -version`:
```
openjdk version "13.0.9" 2021-10-19
OpenJDK Runtime Environment Zulu13.44+13-CA (build 13.0.9+3-MTS)
OpenJDK 64-Bit Server VM Zulu13.44+13-CA (build 13.0.9+3-MTS, mixed mode, sharing)
```

Heroku Logs:

2022-01-02T19:08:24.510352+00:00 app[worker.1]: /app/node_modules/lavaclient/dist/lib/cluster/Cluster.js:23
2022-01-02T19:08:24.510410+00:00 app[worker.1]:         this.userId ??= user && (0, Utils_1.getId)(user);
2022-01-02T19:08:24.510417+00:00 app[worker.1]:                     ^^^
2022-01-02T19:08:24.510421+00:00 app[worker.1]: 
2022-01-02T19:08:24.510425+00:00 app[worker.1]: SyntaxError: Unexpected token '??='
2022-01-02T19:08:24.510425+00:00 app[worker.1]:     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
2022-01-02T19:08:24.510425+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:1049:27)
2022-01-02T19:08:24.510429+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2022-01-02T19:08:24.510429+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2022-01-02T19:08:24.510429+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-01-02T19:08:24.510429+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:974:19)
2022-01-02T19:08:24.510430+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:93:18)
2022-01-02T19:08:24.510430+00:00 app[worker.1]:     at Object.<anonymous> (/app/node_modules/lavaclient/dist/index.js:15:14)
2022-01-02T19:08:24.510430+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-01-02T19:08:24.510430+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

Sorry if my explanations or skill level is quite bad, thank you in advance.

**Comment by freyacodes** [comment]
This looks like it has nothing to do with Lavalink itself. Consider getting help from whomever made lavaclient
