### ISSUE TITLE
Native library connector: loading failed.

### ISSUE THREAD

**Issue by Niraj-Dilshan** [lavalink-devs/Lavalink#598]
## Description
Native library connector: loading failed. Showing on ubuntu 

## Version info

        Version:        f73ce7e39abc70184e956adc41f35cce9156b8ab-SNAPSHOT
        Build:          1324
        Build time:     30.12.2021 15:31:19 UTC
        Branch          dev
        Commit:         f73ce7e
        Commit time:    30.12.2021 15:27:34 UTC
        JVM:            17.0.1
        Lavaplayer      1.3.97-original

Output of `java -version`:

ubuntu@infinite:~/lavalink$ java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.1+12-Ubuntu-120.04, mixed mode, sharing)

2022-01-06 10:03:09.877  INFO 12139 --- [           main] lavalink.server.Launcher                 : Starting Launcher on infinite with PID 12139 (/home/ubuntu/lavalink/Lavalink.jar started by ubuntu in /home/ubuntu/lavalink)
2022-01-06 10:03:09.881  INFO 12139 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2022-01-06 10:03:10.019  WARN 12139 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2022-01-06 10:03:11.299  INFO 12139 --- [           main] lavalink.server.Launcher                 : Started Launcher in 1.995 seconds (JVM running for 2.493)
2022-01-06 10:03:11.301  INFO 12139 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/freyacodes/Lavalink/issues/295
2022-01-06 10:03:11.346  INFO 12139 --- [           main] lavalink.server.Launcher                 :

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        f73ce7e39abc70184e956adc41f35cce9156b8ab-SNAPSHOT
        Build:          1324
        Build time:     30.12.2021 15:31:19 UTC
        Branch          dev
        Commit:         f73ce7e
        Commit time:    30.12.2021 15:27:34 UTC
        JVM:            17.0.1
        Lavaplayer      1.3.97-original

2022-01-06 10:03:11.356  INFO 12139 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to default profiles: default
2022-01-06 10:03:12.112  WARN 12139 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-01-06 10:03:12.146  INFO 12139 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-01-06 10:03:12.147  INFO 12139 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 787 ms
2022-01-06 10:03:12.240  INFO 12139 --- [           main] l.server.metrics.PrometheusMetrics       : Prometheus metrics set up
2022-01-06 10:03:12.287  WARN 12139 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2022-01-06 10:03:12.682  INFO 12139 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2022-01-06 10:03:12.881  INFO 12139 --- [           main] lavalink.server.config.KoeConfiguration  : OS: Linux, Arch: aarch64
2022-01-06 10:03:12.882  WARN 12139 --- [           main] lavalink.server.config.KoeConfiguration  : This system and architecture appears to not support native audio sending! GC pauses may cause your bot to stutter during playback.
2022-01-06 10:03:13.050  INFO 12139 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2022-01-06 10:03:13.224  INFO 12139 --- [           main] org.xnio                                 : XNIO version 3.3.8.Final
2022-01-06 10:03:13.233  INFO 12139 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.8.Final
2022-01-06 10:03:13.294  INFO 12139 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 4430 (http) with context path ''
2022-01-06 10:03:13.295  INFO 12139 --- [           main] lavalink.server.Launcher                 : Started Launcher in 1.988 seconds (JVM running for 4.489)
2022-01-06 10:03:23.119  INFO 12139 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-01-06 10:03:23.120  INFO 12139 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-01-06 10:03:23.125  INFO 12139 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
2022-01-06 10:03:23.141  INFO 12139 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:42212
2022-01-06 10:03:23.201  INFO 12139 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from erela.js
2022-01-06 10:03:30.125  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"886138596011175996","volume":100}
2022-01-06 10:03:30.129  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"886138596011175996"}
2022-01-06 10:03:30.155  INFO 12139 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=Bh1398ddGDw"
2022-01-06 10:03:30.410  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"sessionId":"bc848144ac3a087c11b8f4be996fc6d8","op":"voiceUpdate","guildId":"886138596011175996","event":{"token":"71834a9fb50cbb1e","guild_id":"886138596011175996","endpoint":"singapore2881.discord.media:443"}}
2022-01-06 10:03:30.934  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"886138596011175996","volume":50}
2022-01-06 10:03:30.935  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"op":"equalizer","guildId":"886138596011175996","bands":[{"band":0,"gain":0.25},{"band":1,"gain":0.025},{"band":2,"gain":0.0125},{"band":3,"gain":0},{"band":4,"gain":0},{"band":5,"gain":-0.0125},{"band":6,"gain":-0.025},{"band":7,"gain":-0.0175},{"band":8,"gain":0},{"band":9,"gain":0},{"band":10,"gain":0.0125},{"band":11,"gain":0.025},{"band":12,"gain":0.25},{"band":13,"gain":0.125},{"band":14,"gain":0.125}]}
2022-01-06 10:03:30.936  WARN 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.WebSocketHandler      : The 'equalizer' op has been deprecated in favour of the 'filters' op. Please switch to use that one, as this op will get removed in v4.
2022-01-06 10:03:30.984  INFO 12139 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track NEFFEX Music Mix ● Best of NEFFEX ● Copyright Free Music Mix #1
2022-01-06 10:03:31.010  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"op":"play","guildId":"886138596011175996","track":"QAAArwIAQ05FRkZFWCBNdXNpYyBNaXgg4pePIEJlc3Qgb2YgTkVGRkVYIOKXjyBDb3B5cmlnaHQgRnJlZSBNdXNpYyBNaXggIzEAEkVkdWFyZCBTdG9uZSBHYW1lcwAAAAAAVRkoAAtCaDEzOThkZEdEdwABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PUJoMTM5OGRkR0R3AAd5b3V0dWJlAAAAAAAAAAA="}
2022-01-06 10:03:31.328  INFO 12139 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$616/0x00000008012ae300@65e5329
2022-01-06 10:03:31.330  INFO 12139 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2022-01-06 10:03:31.333 ERROR 12139 --- [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading failed.

java.lang.UnsatisfiedLinkError: Required library was not found
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:125) ~[lava-common-1.1.2.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:110) ~[lava-common-1.1.2.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:84) ~[lava-common-1.1.2.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69) ~[lava-common-1.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:13) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:193) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-01-06 10:03:31.339 ERROR 12139 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of Bh1398ddGDw

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.97-original
  os.arch: aarch64
  os.name: Linux
  os.version: 5.11.0-1023-oracle
  java.vendor: Private Build
  java.version: 17.0.1
  java.runtime.version: 17.0.1+12-Ubuntu-120.04
  java.vm.version: 17.0.1+12-Ubuntu-120.04
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Required library was not found
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:88) ~[lava-common-1.1.2.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69) ~[lava-common-1.1.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:13) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:193) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[lavaplayer-fork-1.3.97.jar!/:na]
        ... 10 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: Required library was not found
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:125) ~[lava-common-1.1.2.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:110) ~[lava-common-1.1.2.jar!/:na]
        at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:84) ~[lava-common-1.1.2.jar!/:na]
        ... 24 common frames omitted

2022-01-06 10:03:31.341  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"886138596011175996"}
2022-01-06 10:03:31.343  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"886138596011175996"}
2022-01-06 10:03:32.055  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"sessionId":"bc848144ac3a087c11b8f4be996fc6d8","op":"voiceUpdate","guildId":"886138596011175996","event":{"token":"71834a9fb50cbb1e","guild_id":"886138596011175996","endpoint":"singapore2881.discord.media:443"}}
2022-01-06 10:03:41.361  INFO 12139 --- [  XNIO-1 I/O-15] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"886138596011175996"}

**Comment by duncte123** [comment]
ARM CPU's are not supported by the official version, use this one instead https://github.com/Cog-Creators/Lavalink-Jars
