### ISSUE TITLE
Can't play age restricted videos

### ISSUE THREAD

**Issue by nascarrym0** [lavalink-devs/Lavalink#616]
I cant play age restricted videos. 

![image](https://user-images.githubusercontent.com/98837307/152015532-83a2bd7c-2121-4628-afd6-bcb7ae837762.png)
![image](https://user-images.githubusercontent.com/98837307/152015702-45316389-a52d-4441-9ea1-04e0015423a0.png)

 Version:        3.4
        Build:          1257
        Build time:     26.10.2021 14:18:37 UTC
        Branch          master
        Commit:         a364833
        Commit time:    26.10.2021 14:15:20 UTC
        
2022-02-01 20:04:16.628  WARN 7328 --- [back-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of B3eAMGXFw1o

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unable to play this YouTube track.
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetails.loadTrackFormats(DefaultYoutubeTrackDetails.java:79) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetails.getFormats(DefaultYoutubeTrackDetails.java:49) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:83) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.96-original
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 11.0.13
  java.runtime.version: 11.0.13+10-LTS-370
  java.vm.version: 11.0.13+10-LTS-370

**Comment by aikaterna** [comment]
Update your Lavalink to a version that includes Walkyst's lavaplayer fork @ 1.3.97 or greater and follow the instructions on https://github.com/Walkyst/lavaplayer-fork/issues/18

**Comment by nascarrym0** [comment]
Thank you i updated to #1337 and its now working.
https://ci.fredboat.com/viewLog.htmlbuildId=9327&buildTypeId=Lavalink_Build&tab=artifacts&branch_Lavalink=refs%2Fheads%2Fdev
