### ISSUE TITLE
Blocked content copyright crash.

### ISSUE THREAD

**Issue by NeonChicken** [lavalink-devs/Lavalink#619]
## Description
Request to load a copyright blocked video will cause strange behaviour. 
Lavalink and the bot will still run, but no longer respond.

## Version info
Output of `java -jar Lavalink.jar --version`
```
Version:        3.4
Build:          1257
Build time:     26.10.2021 14:18:37 UTC
Branch          master
Commit:         a364833
Commit time:    26.10.2021 14:15:20 UTC
JVM:            17.0.1
Lavaplayer      1.3.96-original
```
Output of `java -version`
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing) 
```

## Log
```
2022-02-09 12:06:03.434  INFO 19012 --- [ XNIO-1 task-28] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=cZRzK3g5oi4"
2022-02-09 12:06:03.482 ERROR 19012 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video contains content from Nintendo, who has blocked it on copyright grounds
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.checkPlayabilityStatus(DefaultYoutubeTrackDetailsLoader.java:111) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadBaseResponse(DefaultYoutubeTrackDetailsLoader.java:74) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:53) ~[lavaplayer-fork-1.3.96.jar!/:na] 
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:208) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:232) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:228) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:99) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:64) ~[lavaplayer-fork-1.3.96.jar!/:na]  
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:42) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196) ~[lavaplayer-fork-1.3.96.jar!/:na]      
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:131) ~[lavaplayer-fork-1.3.96.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-fork-1.3.96.jar!/:na]   
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-fork-1.3.96.jar!/:na]       
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-fork-1.3.96.jar!/:na] 
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na] 
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.96-original
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Eclipse Adoptium
  java.version: 17.0.1
  java.runtime.version: 17.0.1+12
  java.vm.version: 17.0.1+12
```

**Comment by freyacodes** [comment]
Please elaborate on what you mean by it not responding

**Comment by NeonChicken** [comment]
Ah never mind, I think the problem lies with my music bot, not within Lavalink.
Apologies!
