### ISSUE TITLE
UT005023: Exception handling request to /loadtracks

### ISSUE THREAD

**Issue by itsmishra19** [lavalink-devs/Lavalink#637]
## Description
There's an exception while making a HTTP request on /loadtracks

## Version info
**Client used:** Shoukaku

Java: https://github.com/freyacodes/Lavalink/blob/master/LavalinkServer/docker/Dockerfile

```java
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:81)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:186)
    at io.undertow.servlet.spec.AsyncContextImpl$2$1.handleRequest(AsyncContextImpl.java:194)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
    at io.undertow.servlet.spec.AsyncContextImpl$2.run(AsyncContextImpl.java:191)
    at io.undertow.servlet.spec.AsyncContextImpl$6.run(AsyncContextImpl.java:465)
    at io.undertow.servlet.spec.AsyncContextImpl$TaskDispatchRunnable.run(AsyncContextImpl.java:584)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
java.lang.NullPointerException: null
    at java.io.DataOutputStream.writeUTF(DataOutputStream.java:352)
    at java.io.DataOutputStream.writeUTF(DataOutputStream.java:326)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.encodeTrack(DefaultAudioPlayerManager.java:248)
    at lavalink.server.util.Util.toMessage(Util.java:49)
    at lavalink.server.player.AudioLoaderRestHandler.lambda$encodeLoadResult$0(AudioLoaderRestHandler.java:89)
    at java.util.ArrayList.forEach(ArrayList.java:1507)
    at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
    at lavalink.server.player.AudioLoaderRestHandler.encodeLoadResult(AudioLoaderRestHandler.java:84)
    at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144)
    at lavalink.server.player.AudioLoader.playlistLoaded(AudioLoader.java:89)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:446)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
```

This is the stack trace i got from sentry.

Lavalink: 77a3bd81c1f3335ce2ed380814c0ebfbc8148984-SNAPSHOT

**Comment by topi314** [comment]
as far as I can tell whatever you loaded there has a null title 
`at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.encodeTrack(DefaultAudioPlayerManager.java:248)`

https://github.com/Walkyst/lavaplayer-fork/blob/original/main/src/main/java/com/sedmelluq/discord/lavaplayer/player/DefaultAudioPlayerManager.java#L248

additional logs on what you did there would be helpful 

at the end this is also a lavaplayer issue but without additional info they can't do anything either

**Comment by devoxin** [comment]
This issue is quite old, and I believe should've been fixed a while ago. You can grab the [3.5-rc1](https://github.com/freyacodes/Lavalink/releases/tag/3.5-rc1) build if you're still hitting this issue.

With the above in mind, as well as lack of new/recent reports, I'm going to close this as resolved.
Please report back if this is not the case!
