### ISSUE TITLE
Video L4-MJdbgPXo with no detected format field

### ISSUE THREAD

**Issue by itsmishra19** [lavalink-devs/Lavalink#639]
Java: https://github.com/freyacodes/Lavalink/blob/master/LavalinkServer/docker/Dockerfile

More Details
```java
<html>
<body>
<!--StartFragment-->

L4-MJdbgPXo
--


<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

```java
<html>
<body>
<!--StartFragment-->

{"responseContext":{"visitorData":"CgtlQTA0NEd0TXhzbyiRn4ySBg%3D%3D","serviceTrackingParams":[{"service":"GFEEDBACK","params":[{"key":"is_viewed_live","value":"True"},{"key":"logged_in","value":"0"},{"key":"country-type","value":"B"},{"key":"e","value":"23966208,24080738,24188933,24174661,24183272,24183574,24184445,24140247,24117491,24120820,23998056,24077241,24007246,24145515,24185614,24173787,24021124,23946420,23918597,24165226,24177193,24165219,24188848,24187043,24161848,24036948,24004644,24054345,24169500,24063124,24176755,24082662,24163232,23888716,24189899,24184052,24106839,39321475,24179789,24110902,24175488,24180089,24034168,24185065,24138064,24060091,24117247,24149832,24189419,24177978,24165080,24185349,24085811,24171338,24186023,24169726,23934970,23744176,24154616,24077266,24184785,24135310,24181182,24123943,24001373,24175468,23882685,24138442,23983296,1714254"}]},{"service":"CSI","params":[{"key":"yt_ad","value":"1"},{"key":"c","value":"ANDROID"},{"key":"cver","value":"16.24"},{"key":"yt_li","value":"0"},{"key":"GetPlayer_rid","value":"0xc4bcb5b0304e7a9e"}]},{"service":"GUIDED_HELP","params":[{"key":"logged_in","value":"0"}]},{"service":"ECATCHER","params":[{"key":"client.version","value":"16.24"},{"key":"client.name","value":"ANDROID"},{"key":"client.fexp","value":"23966208,24080738,24188933,24174661,24183272,24183574,24184445,24140247,24117491,24120820,23998056,24077241,24007246,24145515,24185614,24173787,24021124,23946420,23918597,24165226,24177193,24165219,24188848,24187043,24161848,24036948,24004644,24054345,24169500,24063124,24176755,24082662,24163232,23888716,24189899,24184052,24106839,39321475,24179789,24110902,24175488,24180089,24034168,24185065,24138064,24060091,24117247,24149832,24189419,24177978,24165080,24185349,24085811,24171338,24186023,24169726,23934970,23744176,24154616,24077266,24184785,24135310,24181182,24123943,24001373,24175468,23882685,24138442,23983296,1714254"}]},{"service":"LISTNR","params":[{"key":"e","value":"24033252,24110902,24185065,24024517,24152482,24176...
--


<!--EndFragment-->
</body>
</html>
```
Stack Trace:
```java
    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetails.loadTrackFormats(DefaultYoutubeTrackDetails.java:72)
    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetails.getFormats(DefaultYoutubeTrackDetails.java:49)
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:83)
    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```
Lavalink: 77a3bd81c1f3335ce2ed380814c0ebfbc8148984-SNAPSHOT

**Comment by topi314** [comment]
this is a lavaplayer issue
open an issue there

**Comment by itsmishra19** [comment]
Alright.
