### ISSUE TITLE
Lavalink cannot play audio format: wav

### ISSUE THREAD

**Issue by itsmishra19** [lavalink-devs/Lavalink#640]
```java
ava.lang.IllegalStateException: Invalid audio format 3, must be 1 (PCM)
    at com.sedmelluq.discord.lavaplayer.container.wav.WavFileLoader$InfoBuilder.validateFormat(WavFileLoader.java:106)
    at com.sedmelluq.discord.lavaplayer.container.wav.WavFileLoader$InfoBuilder.build(WavFileLoader.java:98)
    at com.sedmelluq.discord.lavaplayer.container.wav.WavFileLoader$InfoBuilder.access$300(WavFileLoader.java:88)
    at com.sedmelluq.discord.lavaplayer.container.wav.WavFileLoader.parseHeaders(WavFileLoader.java:53)
    at com.sedmelluq.discord.lavaplayer.container.wav.WavContainerProbe.probe(WavContainerProbe.java:45)
    at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:91)
    at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:76)
    at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:61)
    at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.detectContainerWithClient(HttpAudioSourceManager.java:142)
    at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.detectContainer(HttpAudioSourceManager.java:120)
    at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
```

Lavalink: 77a3bd81c1f3335ce2ed380814c0ebfbc8148984-SNAPSHOT

**Comment by topi314** [comment]
this is a lavaplayer issue 
open an issue there

**Comment by itsmishra19** [comment]
Alright.
