### ISSUE TITLE
Youtbe Links dead? 

### ISSUE THREAD

**Issue by MrUnknownDE** [lavalink-devs/Lavalink#645]
## Description
The bot has not been able to play YouTube links for some time. Only SoundCloud and so on. 

## Version info
**Client used: Redbot ** 

Output of `java -version`:
```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Debian-1deb11u1, mixed mode, sharing)
```

```
redbot_lavalink    |    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1                                                     0.jar!/:4.5.10]
redbot_lavalink    |    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpc                                                     lient-4.5.10.jar!/:4.5.10]
redbot_lavalink    |    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpcl                                                     ient-4.5.10.jar!/:4.5.10]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[lava                                                     player-fork-1.3.96.jar!/:na]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpS                                                     tream.java:113) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.j                                                     ava:105) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStr                                                     eam.java:150) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java                                                     :166) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger                                                     (MatroskaEbmlReader.java:39) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement                                                     (MatroskaFileReader.java:45) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaSt                                                     reamingFile.java:78) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(Matro                                                     skaAudioTrack.java:51) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    ... 9 common frames omitted
redbot_lavalink    |    Suppressed: com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator$AdditionalDet                                                     ails: Encountered when opening a connection with the following details:
redbot_lavalink    |   host: https://rr1---sn-gxuog0-jx3e.googlevideo.com:443
redbot_lavalink    |   localAddress: <unspecified>
redbot_lavalink    |   remoteAddress: rr1---sn-gxuog0-jx3e.googlevideo.com/87.245.195.172:443
redbot_lavalink    |   connectTimeout: 3000
redbot_lavalink    |   triedAddresses: rr1---sn-gxuog0-jx3e.googlevideo.com/87.245.195.172
redbot_lavalink    | Caused by: java.net.SocketTimeoutException: Connect timed out
redbot_lavalink    |    at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[na:na]
redbot_lavalink    |    at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
redbot_lavalink    |    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339) ~[na:na]
redbot_lavalink    |    at java.base/java.net.Socket.connect(Socket.java:603) ~[na:na]
redbot_lavalink    |    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.                                                     java:368) ~[httpclient-4.5.10.jar!/:4.5.10]
redbot_lavalink    |    at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination                                                     (ExtendedConnectionOperator.java:157) ~[lavaplayer-fork-1.3.96.jar!/:na]
redbot_lavalink    |    ... 28 common frames omitted
```

**Comment by aikaterna** [comment]
`Caused by: java.net.SocketTimeoutException: Connect timed out`
Your vps didn't receive a response from the video url in time/you have network issues on that device.
