### ISSUE TITLE
why do I get the error in my discord server ERROR: WebSocket connection to server isn't in open state?

### ISSUE THREAD

**Issue by Niccii03** [lavalink-devs/Lavalink#656]
## Description

why do I get the error in my discord server ERROR: WebSocket connection to server isn't in open state? Also i have private IP address. My discord music bot doesn't play any music.

## Version info
**Client used:**  Victoria

Output of `java -version`:
```
18.0.1
(paste here)
```

 
2022-05-19 16:13:44.675  WARN 17880 --- [XNIO-1 Accept] org.xnio.nio.selector                    : XNIO008000: Received an I/O error on selection: java.io.IOException: The remote host forcibly terminated the existing connection

java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
[spring.log.2022-05-19.141.gz] (https://github.com/freyacodes/Lavalink/files/8729750/spring.log.2022-05-19.141.gz)

	at java.base/sun.nio.ch.IOUtil.drain(Native Method) ~[na:na]
	at java.base/sun.nio.ch.WEPollSelectorImpl.clearInterrupt(WEPollSelectorImpl.java:248) ~[na:na]
	at java.base/sun.nio.ch.WEPollSelectorImpl.processEvents(WEPollSelectorImpl.java:186) ~[na:na]
	at java.base/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:116) ~[na:na]
	at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129) ~[na:na]
	at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:146) ~[na:na]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:511) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

**Comment by topi314** [comment]
can you please only provide the relevant log part?
I'm not interested into a 1GB log file sorry
![image](https://user-images.githubusercontent.com/15636011/175325136-c7e522f6-3b57-483e-bf38-e0ed4825f576.png)

**Comment by topi314** [comment]
I'm going to close this as their hasn't been any response. Feel free to reopen it with more info
