### ISSUE TITLE
3.5-rc2 unable to play from YouTube

### ISSUE THREAD

**Issue by cloudwithax** [lavalink-devs/Lavalink#707]
## Description

When playing a YouTube result, it errors out with `Problematic youtube script`

## Version info
**Client used:** 
Pomice 1.1.7b

Output of `java -version`:
```
java 18.0.1.1 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

```
2022-08-11 13:59:39.103 ERROR 10296 --- [back-1-thread-1] .s.d.l.s.y.YoutubeSignatureCipherManager : Problematic YouTube player script /s/player/324f67b9/player_ias.vflset/en_US/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\clxud\AppData\Local\Temp\lavaplayer-yt-player-script1084576625002329503.js.
2022-08-11 13:59:39.130 ERROR 10296 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of U9D2l3u3l-c

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.98.1.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.98-original
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 18.0.1.1
  java.runtime.version: 18.0.1.1+2-6
  java.vm.version: 18.0.1.1+2-6
Caused by: java.lang.IllegalStateException: No match found
        at java.base/java.util.regex.Matcher.group(Matcher.java:644) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:250) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:165) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:207) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:56) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:44) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:77) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:43) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.98.1.jar!/:na]
        ... 4 common frames omitted
```

**Comment by topi314** [comment]
currently waiting on https://github.com/Walkyst/lavaplayer-fork/commit/47df2b1ca75675528f5262cf68fa478b45f32caa to go to the original branch
then we can publish a fix

**Comment by Dramex** [comment]
> currently waiting on [Walkyst/lavaplayer-fork@47df2b1](https://github.com/Walkyst/lavaplayer-fork/commit/47df2b1ca75675528f5262cf68fa478b45f32caa) to go to the original branch then we can publish a fix

merged ig

**Comment by topi314** [comment]
resolved in https://github.com/freyacodes/Lavalink/releases/tag/3.5-rc3

**Comment by DakshNamdev** [comment]
https://paste.zorino.in/hevedadesapijidi

**Comment by topi314** [comment]
this has nothing to do with this issue
