### ISSUE TITLE
Broken Search

### ISSUE THREAD

**Issue by Vretu-Dev** [lavalink-devs/Lavalink#708]
## Description

Searching is broken

## Version info
**Client used:** Dev Build: 1371
	Version:        469d1b817dab04987e1d22e465aa3b0278661939-SNAPSHOT

Output of `java -version`:
```
java.vm.version: 19-ea+29-2143
```

```
022-08-11 18:51:12.184 ERROR 1 --- [back-1-thread-1] .s.d.l.s.y.YoutubeSignatureCipherManager : Problematic YouTube player script /s/player/324f67b9/player_ias.vflset/de_DE/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script12288626172116557426.js.
2022-08-11 18:51:12.203 ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of mRD0-GxqHVo

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.98.1.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98-original
  os.arch: aarch64
  os.name: Linux
  os.version: 5.13.0-1027-oracle
  java.vendor: Oracle Corporation
  java.version: 19-ea
  java.runtime.version: 19-ea+29-2143
  java.vm.version: 19-ea+29-2143
Caused by: java.lang.IllegalStateException: No match found
	at java.base/java.util.regex.Matcher.group(Matcher.java:644) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:250) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:165) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:207) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:56) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:44) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:77) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:43) ~[lavaplayer-1.3.98.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.98.1.jar!/:na]
	... 4 common frames omitted
```

**Comment by topi314** [comment]
duplicate of https://github.com/freyacodes/Lavalink/issues/707

**Comment by Vretu-Dev** [comment]
> duplicate of #707

oh yes
