### ISSUE TITLE
No Audio Output on Discord Bot in VC

### ISSUE THREAD

**Issue by KarlIsTired** [lavalink-devs/Lavalink#712]
Whenever I attempt to use my play command, the track loads into the queue completely fine, but as soon as I try to play it I get an error message... Thanks for any help i get in advance!

```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
```
```
        Version:        3.5-rc2
        Build:          Unknown
        Build time:     30.07.2022 02:04:50 UTC
        Branch          HEAD
        Commit:         df2f7f3
        Commit time:    30.07.2022 01:26:09 UTC
        JVM:            13
        Lavaplayer      1.3.98-original
```

```
2022-08-15 00:20:43.399  INFO 19596 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-08-15 00:20:44.192  WARN 19596 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-08-15 00:20:44.214  INFO 19596 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-08-15 00:20:44.214  INFO 19596 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 810 ms
2022-08-15 00:20:44.440  INFO 19596 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2022-08-15 00:20:44.497  WARN 19596 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2022-08-15 00:20:44.841  INFO 19596 --- [           main] lavalink.server.config.KoeConfiguration  : OS: WINDOWS, Arch: X86_64
2022-08-15 00:20:44.841  INFO 19596 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2022-08-15 00:20:44.845  INFO 19596 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2022-08-15 00:20:44.851  INFO 19596 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2022-08-15 00:20:45.090  INFO 19596 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2022-08-15 00:20:45.100  INFO 19596 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2022-08-15 00:20:45.110  INFO 19596 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2022-08-15 00:20:45.180  INFO 19596 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2022-08-15 00:20:45.223  INFO 19596 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8081 (http)
2022-08-15 00:20:45.226  INFO 19596 --- [           main] lavalink.server.Launcher                 : Started Launcher in 1.88 seconds (JVM running for 3.818)
2022-08-15 00:20:45.227  INFO 19596 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2022-08-15 00:21:51.894  INFO 19596 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-15 00:21:51.895  INFO 19596 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-15 00:21:51.896  INFO 19596 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2022-08-15 00:21:51.914  INFO 19596 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /0:0:0:0:0:0:0:1:50376
2022-08-15 00:21:51.969  INFO 19596 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from Lavalink.py
2022-08-15 00:21:51.985  INFO 19596 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "music-node", "timeout": 60}
2022-08-15 00:22:00.593  INFO 19596 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:something"
2022-08-15 00:22:01.545  INFO 19596 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: something
2022-08-15 00:22:01.567  INFO 19596 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "935335387151360000", "track": "QAAAfAIAF1RoZSBCZWF0bGVzIC0gU29tZXRoaW5nAAtUaGUgQmVhdGxlcwAAAAAAAt5gAAtVZWxEcloxYUZlWQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVVlbERyWjFhRmVZAAd5b3V0dWJlAAAAAAAAAAA=", "startTime": 0, "endTime": 0, "noReplace": false}
2022-08-15 00:22:01.578  WARN 19596 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
2022-08-15 00:22:01.870 ERROR 19596 --- [back-1-thread-1] .s.d.l.s.y.YoutubeSignatureCipherManager : Problematic YouTube player script /s/player/4c3f79c5/player_ias.vflset/en_US/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\Solarity\AppData\Local\Temp\lavaplayer-yt-player-script3832824357780300957.js.
2022-08-15 00:22:01.886 ERROR 19596 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of UelDrZ1aFeY

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.98.1.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.98-original
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 13
  java.runtime.version: 13+33
  java.vm.version: 13+33
Caused by: java.lang.IllegalStateException: No match found
        at java.base/java.util.regex.Matcher.group(Matcher.java:645) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.extractFromScript(YoutubeSignatureCipherManager.java:250) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getExtractedScript(YoutubeSignatureCipherManager.java:165) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:207) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:56) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:44) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:77) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:43) ~[lavaplayer-1.3.98.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.98.1.jar!/:na]
        ... 4 common frames omitted

2022-08-15 00:22:01.888  INFO 19596 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "935335387151360000"}

```

**Comment by aikaterna** [comment]
Try the RC3 release instead.

**Comment by topi314** [comment]
duplicate of https://github.com/freyacodes/Lavalink/issues/707

**Comment by KarlIsTired** [comment]
Ok so I downloaded the v3,5-rc3 version, and the same problem happens but there is no exception this time. I still get no audio from Discord... Any other suggestions? thanks
```
←[32m       .  ←[31m _                  _ _       _    ←[32m__ _ _
←[32m      /\\ ←[31m| | __ ___   ____ _| (_)_ __ | | __←[32m\ \ \ \
←[32m     ( ( )←[31m| |/ _` \ \ / / _` | | | '_ \| |/ /←[32m \ \ \ \
←[32m      \\/ ←[31m| | (_| |\ V / (_| | | | | | |   < ←[32m  ) ) ) )
←[32m       '  ←[31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\←[32m / / / /
←[0m    =========================================←[32m/_/_/_/←[0m

        Version:        3.5-rc3
        Build:          Unknown
        Build time:     11.08.2022 18:37:19 UTC
        Branch          HEAD
        Commit:         1b8e84f
        Commit time:    11.08.2022 18:22:22 UTC
        JVM:            13
        Lavaplayer      1.3.98.2-original

2022-08-15 08:26:39.012  INFO 10600 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-08-15 08:26:39.811  WARN 10600 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2022-08-15 08:26:39.832  INFO 10600 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2022-08-15 08:26:39.832  INFO 10600 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 815 ms
2022-08-15 08:26:40.077  INFO 10600 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2022-08-15 08:26:40.137  WARN 10600 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2022-08-15 08:26:40.508  INFO 10600 --- [           main] lavalink.server.config.KoeConfiguration  : OS: WINDOWS, Arch: X86_64
2022-08-15 08:26:40.508  INFO 10600 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2022-08-15 08:26:40.514  INFO 10600 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2022-08-15 08:26:40.520  INFO 10600 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2022-08-15 08:26:40.765  INFO 10600 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2022-08-15 08:26:40.775  INFO 10600 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2022-08-15 08:26:40.787  INFO 10600 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2022-08-15 08:26:40.858  INFO 10600 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2022-08-15 08:26:40.906  INFO 10600 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8081 (http)
2022-08-15 08:26:40.911  INFO 10600 --- [           main] lavalink.server.Launcher                 : Started Launcher in 1.954 seconds (JVM running for 3.949)
2022-08-15 08:26:40.912  INFO 10600 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2022-08-15 08:26:51.743  INFO 10600 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-15 08:26:51.743  INFO 10600 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-15 08:26:51.745  INFO 10600 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2022-08-15 08:26:51.763  INFO 10600 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /0:0:0:0:0:0:0:1:55429
2022-08-15 08:26:51.820  INFO 10600 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from Lavalink.py
2022-08-15 08:26:51.836  INFO 10600 --- [   XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "music-node", "timeout": 60}
2022-08-15 08:27:05.096  INFO 10600 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:something"
2022-08-15 08:27:06.087  INFO 10600 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: something
2022-08-15 08:28:12.843  INFO 10600 --- [   XNIO-1 I/O-5] lavalink.server.io.SocketServer          : Connection closed from /0:0:0:0:0:0:0:1:55429 with status CloseStatus[code=1006, reason=] -- Session can be resumed within the next 60 seconds with key music-node
2022-08-15 08:28:18.131  INFO 10600 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /0:0:0:0:0:0:0:1:60013
2022-08-15 08:28:18.133  INFO 10600 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from Lavalink.py
2022-08-15 08:28:18.135  INFO 10600 --- [  XNIO-1 I/O-11] lavalink.server.io.SocketServer          : {"op": "configureResuming", "key": "music-node", "timeout": 60}
2022-08-15 08:28:29.684  INFO 10600 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:come as you are"
2022-08-15 08:28:30.172  INFO 10600 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: come as you are
2022-08-15 08:28:30.178  INFO 10600 --- [  XNIO-1 I/O-11] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "935335387151360000", "track": "QAAAkQIAME5pcnZhbmEgLSBDb21lIEFzIFlvdSBBcmUgKE9mZmljaWFsIE11c2ljIFZpZGVvKQAHTmlydmFuYQAAAAAAA27oAAt2YWJuWjktZXg3bwABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PXZhYm5aOS1leDdvAAd5b3V0dWJlAAAAAAAAAAA=", "startTime": 0, "endTime": 0, "noReplace": false}
2022-08-15 08:28:30.188  WARN 10600 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
```

**Comment by topi314** [comment]
you never forward the voice state update to lavalink which contains the info to where it should connect
reach out to your clients developer to resolve this as it's not a lavalink issue
