### ISSUE TITLE
cloudflare origin dns error

### ISSUE THREAD

**Issue by djohts** [lavalink-devs/Lavalink#721]
## Description
fails to fetch yt master token due to issues on https://youtube.minerea.su

## Version info
**Client used:** irrelevant

Output of `java -version`:
```
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode)
```

```
2022-08-24 02:28:04.438 ERROR 35 --- [onPool-worker-3] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube master token update failed.
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Origin DNS error | youtube.minerea.su | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="[truncated 5732 chars]; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4703) ~[jackson-databind-2.13.2.2.jar!/:2.13.2.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076) ~[jackson-databind-2.13.2.2.jar!/:2.13.2.2]
        at com.sedmelluq.discord.lavaplayer.tools.JsonBrowser.parse(JsonBrowser.java:204) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.requestMasterToken(YoutubeAccessTokenTracker.java:205) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchMasterToken(YoutubeAccessTokenTracker.java:186) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.lambda$updateMasterToken$0(YoutubeAccessTokenTracker.java:111) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

<details>
<summary>java -jar Lavalink.jar --version</summary>
<br>
<pre>
Version:        3.5-rc4
Build time:     18.08.2022 16:03:31 UTC
Branch          HEAD
Commit:         b69f613
Commit time:    18.08.2022 15:52:23 UTC
JVM:            11.0.15
Lavaplayer      1.3.98.4-original
</pre>
</details>

**Comment by djohts** [comment]
[solved](https://status.heroku.com/incidents/2453) (I contacted owner of the domain)
