### ISSUE TITLE
Error when using effects or filters

### ISSUE THREAD

**Issue by TechnoHaX** [lavalink-devs/Lavalink#803]
## Description

I just came across an error when I try to use filters on my bot that uses lavalink. When you apply any effects to a track, the player crashes.

## Version info
**Client used:** 
`v3.6.2`
Output of `java -version`:
```
openjdk version "18" 2022-03-22
OpenJDK Runtime Environment (build 18+36-2087)
OpenJDK 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
```

```
2023-01-14 12:03:12.729  INFO 445499 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"equalizer","guildId":"420256166355009545","bands":[{"band":0,"gain":0.125},{"band":1,"gain":0.25},{"band":2,"gain":-0.25},{"band":3,"gain":-0.125},{"band":4,"gain":0},{"band":5,"gain":-0.0125},{"band":6,"gain":-0.025},{"band":7,"gain":-0.0175},{"band":8,"gain":0},{"band":9,"gain":0},{"band":10,"gain":0.0125},{"band":11,"gain":0.025},{"band":12,"gain":0.375},{"band":13,"gain":0.125},{"band":14,"gain":0.125}]}
2023-01-14 12:03:12.730  WARN 445499 --- [   XNIO-1 I/O-1] lavalink.server.io.WebSocketHandler      : The 'equalizer' op has been deprecated in favour of the 'filters' op. Please switch to use that one, as this op will get removed in v4.
2023-01-14 12:03:12.732  INFO 445499 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"filters","guildId":"420256166355009545","equalizer":[{"band":0,"gain":0.125},{"band":1,"gain":0.25},{"band":2,"gain":-0.25},{"band":3,"gain":-0.125},{"band":4,"gain":0},{"band":5,"gain":-0.0125},{"band":6,"gain":-0.025},{"band":7,"gain":-0.0175},{"band":8,"gain":0},{"band":9,"gain":0},{"band":10,"gain":0.0125},{"band":11,"gain":0.025},{"band":12,"gain":0.375},{"band":13,"gain":0.125},{"band":14,"gain":0.125}],"timescale":{"speed":1,"pitch":1,"rate":1}}
2023-01-14 12:03:12.744 ERROR 445499 --- [ack-1-thread-98] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of W08xLiT5i_c

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:354) ~[lavaplayer-1.3.99.1.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.99.1-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.10.0-19-cloud-amd64
  java.vendor: Oracle Corporation
  java.version: 18
  java.runtime.version: 18+36-2087
  java.vm.version: 18+36-2087
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to create directory for unpacked native library.
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:88) ~[lava-common-1.3.99.1.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:69) ~[lava-common-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoderLibrary.getInstance(OpusDecoderLibrary.java:13) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:20) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:193) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:177) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:93) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:46) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[lavaplayer-1.3.99.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[lavaplayer-1.3.99.1.jar!/:na]
	... 10 common frames omitted
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to create directory for unpacked native library.
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:136) ~[lava-common-1.3.99.1.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:110) ~[lava-common-1.3.99.1.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadWithFailureCheck(NativeLibraryLoader.java:84) ~[lava-common-1.3.99.1.jar!/:na]
	... 24 common frames omitted
Caused by: java.io.IOException: Failed to create directory for unpacked native library.
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.prepareExtractionDirectory(NativeLibraryLoader.java:152) ~[lava-common-1.3.99.1.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:128) ~[lava-common-1.3.99.1.jar!/:na]
	... 26 common frames omitted
Caused by: java.nio.file.AccessDeniedException: /tmp/lava-jni-natives/1673101894775
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[na:na]
	at java.base/java.nio.file.Files.createDirectory(Files.java:700) ~[na:na]
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[na:na]
	at java.base/java.nio.file.Files.createDirectories(Files.java:793) ~[na:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.createDirectoriesWithFullPermissions(NativeLibraryLoader.java:207) ~[lava-common-1.3.99.1.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.prepareExtractionDirectory(NativeLibraryLoader.java:148) ~[lava-common-1.3.99.1.jar!/:na]
	... 27 common frames omitted
2023-01-14 12:03:12.747  INFO 445499 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"420256166355009545"}
2023-01-14 12:03:12.748  INFO 445499 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"420256166355009545"}
```

**Comment by topi314** [comment]
it seems like your user has no access to write to `/tmp/lava-jni-natives/1673101894775`
this can happen if you run lavalink with multiple users and `/tmp/lava-jni-natives/` was created by the other user
