### ISSUE TITLE
Lavalink error when moving bot to another channel

### ISSUE THREAD

**Issue by jgculebras** [lavalink-devs/Lavalink#808]
## Description:
Hello I am developing a discord music bot to display music when anyone requests it, issue I have is that if the bot is in a voice channel and suddenly anyone moves it from discord to another voice channel it breaks and doesn't displays any music unless I restart the program.

## **Javalink Logs**:
>ERROR 1134212 --- [   XNIO-1 I/O-3] w.s.h.ExceptionWebSocketHandlerDecorator : Closing session due to exception for StandardWebSocketSession
org.json.JSONException: JSONObject["token"] not found.
        at org.json.JSONObject.get(JSONObject.java:570) ~[json-20220924.jar!/:na]
        at org.json.JSONObject.getString(JSONObject.java:857) ~[json-20220924.jar!/:na]
        at lavalink.server.io.WebSocketHandler.voiceUpdate(WebSocketHandler.kt:68) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler.access$voiceUpdate(WebSocketHandler.kt:19) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler$handlers$1.invoke(WebSocketHandler.kt:38) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler$handlers$1.invoke(WebSocketHandler.kt:38) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler.handle(WebSocketHandler.kt:59) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessage(SocketServer.kt:186) ~[classes!/:na]
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:288) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:610) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:600) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.invokeTextHandler(FrameHandler.java:268) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.onFullTextMessage(FrameHandler.java:319) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.onText(FrameHandler.java:184) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:955) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:935) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) ~[xnio-nio-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) ~[xnio-nio-3.8.6.Final.jar!/:3.8.6.Final]

## Version info
**Client used:** Wavelink

> **java -version:**
java version "13" 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)

> **Java -jar Lavalink.jar --version:**
Version:        3.7.1
Build time:     17.01.2023 13:18:11 UTC
Branch          HEAD
Commit:         e29cb91
Commit time:    17.01.2023 13:15:32 UTC
JVM:            13
Lavaplayer      1.3.99.2-original

Any help would be appreciated. Thanks

**Comment by topi314** [comment]
Your voice state update op doesn't include the token which lavalink needs to connect to discord voice servers. 
Reach out to you client lib maintainers for help on how to use their client

**Comment by jgculebras** [comment]
I don't find when or where to include that token, where is that token also be retrieved?

Bot can connects into a channel and runs perfectly if it is not in a channel previously.

**Comment by jgculebras** [comment]
@TopiSenpai
