### ISSUE TITLE
lavalink docker issue

### ISSUE THREAD

**Issue by KingBananaDuck** [lavalink-devs/Lavalink#847]
2023-03-08 17:55:01 2023-03-08 15:55:01.826  INFO 1 --- [   XNIO-2 I/O-7] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"949057676816547910","volume":100}
2023-03-08 17:55:02 2023-03-08 15:55:02.332  INFO 1 --- [   XNIO-2 I/O-7] lavalink.server.io.SocketServer          : {"op":"voiceUpdate","guildId":"949057676816547910","sessionId":"51b38a9c4d59b4c3b6e3ae1079ecc72f","event":{"token":"cdfe55e01477aea8","guild_id":"949057676816547910","endpoint":"frankfurt8139.discord.media:443"}}
2023-03-08 17:55:02 2023-03-08 15:55:02.868  INFO 1 --- [  XNIO-2 task-4] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2023-03-08 17:55:03 2023-03-08 15:55:03.604 ERROR 1 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item https://www.youtube.com/watch?v=OyDyOweu-PA
2023-03-08 17:55:03 
2023-03-08 17:55:03 com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:226) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromUrlWithVideoId(YoutubeAudioSourceManager.java:316) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromMainDomain(YoutubeAudioSourceManager.java:253) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadNonSearch(YoutubeAudioSourceManager.java:323) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:189) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:128) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
2023-03-08 17:55:03 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
2023-03-08 17:55:03 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
2023-03-08 17:55:03 at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
2023-03-08 17:55:03 Caused by: java.io.IOException: Invalid status code for video info response: 410
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.determineFailureReason(YoutubeAudioSourceManager.java:385) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:374) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:201) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 ... 12 common frames omitted
2023-03-08 17:55:03 
2023-03-08 17:55:03 2023-03-08 15:55:03.605 ERROR 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed
2023-03-08 17:55:03 
2023-03-08 17:55:03 com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:226) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromUrlWithVideoId(YoutubeAudioSourceManager.java:316) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadFromMainDomain(YoutubeAudioSourceManager.java:253) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadNonSearch(YoutubeAudioSourceManager.java:323) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:189) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:128) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
2023-03-08 17:55:03 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
2023-03-08 17:55:03 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
2023-03-08 17:55:03 at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
2023-03-08 17:55:03 Caused by: java.io.IOException: Invalid status code for video info response: 410
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.determineFailureReason(YoutubeAudioSourceManager.java:385) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getTrackInfoFromMainPage(YoutubeAudioSourceManager.java:374) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:201) ~[lavaplayer-1.3.19.jar!/:na]
2023-03-08 17:55:03 ... 12 common frames omitted
2023-03-08 17:55:03 
2023-03-08 17:55:03 2023-03-08 15:55:03.616  INFO 1 --- [   XNIO-2 I/O-7] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"949057676816547910"}
2023-03-08 17:55:04 2023-03-08 15:55:04.036  INFO 1 --- [     parallel-9] s.n.magma.connections.AudioWebSocket     : Websocket to wss://frankfurt8139.discord.media:443/?v=4 closed with code 4014 and reason Disconnected.
2023-03-08 17:55:04 2023-03-08 15:55:04.038  INFO 1 --- [     parallel-9] s.n.magma.connections.AudioWebSocket     : Resuming

**Comment by devoxin** [comment]
You're on an extremely outdated version of Lavalink.

**Comment by KingBananaDuck** [comment]
It won't play anything

**Comment by devoxin** [comment]
Again, you're on an extremely outdated version of Lavalink. You should consider updating, I'm pretty confident that it'll fix your issue.

**Comment by KingBananaDuck** [comment]
What command should I run to do so

**Comment by topi314** [comment]
you can find the docker images here
https://github.com/freyacodes/Lavalink/pkgs/container/lavalink

update and your issue should be fixed
