### ISSUE TITLE
Response code from channel info is 400

### ISSUE THREAD

**Issue by 14yao** [lavalink-devs/Lavalink#873]
## Description
Using Lavalink with the [LavaSrc](https://github.com/TopiSenpai/LavaSrc) plugin to use Spotify as a source, but getting an error as shown in the logs at the bottom.

## Version info
**Client used:** [@lavacord/discord.js v0.0.7](https://github.com/lavacord/discord.js)

Output of `java -version`:
```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)
```

## Lavalink Logs
```
2023-04-29 23:13:36.630  INFO 13616 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 11.0.12 on ASTURA0001 with PID 13616 (C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\Lavalink.jar started by tncz in C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink)
2023-04-29 23:13:36.728  INFO 13616 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: 
"default"
2023-04-29 23:13:40.043  INFO 13616 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'lavasrc' version 3.1.7
2023-04-29 23:13:40.160  INFO 13616 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded lavasrc-plugin-3.2.0.jar (24 classes)
2023-04-29 23:13:40.965  INFO 13616 --- [           main] lavalink.server.Launcher                 : Started Launcher in 5.761 seconds (JVM running for 10.709)2023-04-29 23:13:41.059  INFO 13616 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/freyacodes/Lavalink/issues/295
2023-04-29 23:13:41.487  INFO 13616 --- [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        3.6.0
        Build time:     12.10.2022 12:50:15 UTC
        Branch          HEAD
        Commit:         db242da
        Commit time:    12.10.2022 12:41:38 UTC
        JVM:            11.0.12
        Lavaplayer      1.3.98.4-original

2023-04-29 23:13:41.526  INFO 13616 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: 
"default"
2023-04-29 23:13:43.398  WARN 13616 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-04-29 23:13:43.443  INFO 13616 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-04-29 23:13:43.444  INFO 13616 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1813 ms
2023-04-29 23:13:43.620  INFO 13616 --- [           main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Loading LavaSrc plugin...
2023-04-29 23:13:44.014  INFO 13616 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2023-04-29 23:13:44.088  INFO 13616 --- [           main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Registering Spotify audio source manager...
2023-04-29 23:13:44.341  INFO 13616 --- [           main] lavalink.server.config.KoeConfiguration  : OS: WINDOWS, Arch: X86_64
2023-04-29 23:13:44.342  INFO 13616 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2023-04-29 23:13:44.356  INFO 13616 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2023-04-29 23:13:44.410  INFO 13616 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2023-04-29 23:13:44.444  WARN 13616 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2023-04-29 23:13:44.815  INFO 13616 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2023-04-29 23:13:44.831  INFO 13616 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2023-04-29 23:13:44.853  INFO 13616 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2023-04-29 23:13:45.022  INFO 13616 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2023-04-29 23:13:45.110  INFO 13616 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 2333 (http)
2023-04-29 23:13:45.116  INFO 13616 --- [           main] lavalink.server.Launcher                 : Started Launcher in 4.038 seconds (JVM running for 14.86)
2023-04-29 23:13:45.121  INFO 13616 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2023-04-29 23:14:01.606  INFO 13616 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-04-29 23:14:01.608  INFO 13616 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-04-29 23:14:01.611  INFO 13616 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2023-04-29 23:14:01.657  INFO 13616 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:49931
2023-04-29 23:14:02.128  INFO 13616 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established
2023-04-29 23:14:02.129  WARN 13616 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Library developers: Please specify a 'Client-Name' header.2023-04-29 23:14:17.092  INFO 13616 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "spsearch:butterfly effect astro"
2023-04-29 23:14:18.770  INFO 13616 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: butterfly effect astro2023-04-29 23:14:22.233  INFO 13616 --- [   XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"volume":75,"op":"volume","guildId":"1032526965070110720"}
2023-04-29 23:14:22.256  INFO 13616 --- [   XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"track":"QAAA1gIAEEJ1dHRlcmZseSBFZmZlY3QABUFTVFJPAAAAAAADR2AAFjJnRlJPZUJhRlZla3pvTktXbEhyODMAAQA1aHR0cHM6Ly9vcGVuLnNwb3RpZnkuY29tL3RyYWNrLzJnRlJPZUJhRlZla3pvTktXbEhyODMAB3Nwb3RpZnkBAAxLUkEzODIxMDIyODUBAEBodHRwczovL2kuc2Nkbi5jby9pbWFnZS9hYjY3NjE2ZDAwMDBiMjczZTBjYTc0N2VhZTQ5NGU5NDQ4NGYzOTk3AAAAAAAAAAA=","op":"play","guildId":"1032526965070110720"}
2023-04-29 23:14:22.608  WARN 13616 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Suspicious exception for loading item sprec:KRA382102285

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseAsJson(HttpClientTools.java:261) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getJson(SpotifySourceManager.java:159) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getRecommendations(SpotifySourceManager.java:172) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:111) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Microsoft
  java.version: 11.0.12
  java.runtime.version: 11.0.12+7
  java.vm.version: 11.0.12+7
Caused by: java.lang.IllegalStateException: Response code from channel info is 400
        ... 11 common frames omitted

2023-04-29 23:14:22.619 ERROR 13616 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 2gFROeBaFVekzoNKWlHr83

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.98.4.jar!/:na]   
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Microsoft
  java.version: 11.0.12
  java.runtime.version: 11.0.12+7
  java.vm.version: 11.0.12+7
Caused by: java.util.concurrent.CompletionException: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044) ~[na:na]
        at com.github.topisenpai.lavasrc.mirror.MirroringAudioTrack.loadItem(MirroringAudioTrack.java:89) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.github.topisenpai.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:52) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.github.topisenpai.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:13) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.github.topisenpai.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:44) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.98.4.jar!/:na]   
        ... 4 common frames omitted
Caused by: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseAsJson(HttpClientTools.java:261) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getJson(SpotifySourceManager.java:159) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getRecommendations(SpotifySourceManager.java:172) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:111) ~[jar:file:C:\Users\ascen\OneDrive\Documents\Programming\Bots\Adix\lavalink\.\plugins\lavasrc-plugin-3.2.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        ... 3 common frames omitted
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Microsoft
  java.version: 11.0.12
  java.runtime.version: 11.0.12+7
  java.vm.version: 11.0.12+7
Caused by: java.lang.IllegalStateException: Response code from channel info is 400
        ... 11 common frames omitted

2023-04-29 23:14:22.670  INFO 13616 --- [   XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"sessionId":"a5a7c60b75185839bd17f1178966ec8d","event":{"token":"c2a20124c0a8b949","guild_id":"1032526965070110720","endpoint":"sydney6268.discord.media:443"},"op":"voiceUpdate","guildId":"1032526965070110720"}
```

**Comment by topi314** [comment]
This is the Lavalink issue tracker. Not LavaSrc
