### ISSUE TITLE
Track loading issue.

### ISSUE THREAD

**Issue by chredeur** [lavalink-devs/Lavalink#881]
## Description
When I load an ogg audio stream (icecast webradio), I get this error: 

```
2023-05-17 18:30:23.670  INFO 94 --- [XNIO-1 task-12] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "http://icecast.flazebot.com:8100/phonk_premium.ogg"
2023-05-17 18:30:23.671  WARN 94 --- [lava-daemon-pool-info-loader-2-thread-1] c.s.d.l.container.ogg.OggContainerProbe  : Failed to collect additional information on OGG stream.

java.lang.NullPointerException: Cannot invoke "com.sedmelluq.discord.lavaplayer.container.ogg.OggStreamSizeInfo.getDuration()" because "sizeInfo" is null
	at com.sedmelluq.discord.lavaplayer.container.ogg.vorbis.OggVorbisCodecHandler.loadMetadata(OggVorbisCodecHandler.java:62) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggTrackLoader.loadMetadata(OggTrackLoader.java:36) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggContainerProbe.collectStreamInformation(OggContainerProbe.java:61) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggContainerProbe.probe(OggContainerProbe.java:46) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:91) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:76) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:61) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.detectContainerWithClient(HttpAudioSourceManager.java:142) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.detectContainer(HttpAudioSourceManager.java:120) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:449) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:431) ~[lavaplayer-1.4.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-1.4.0.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-05-17 18:30:23.671  INFO 94 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track phonk
```

The track plays correctly but at the end of the music, the end of track event is called and the stream is not played anymore even though the audio stream has not stopped.

After taking the version 3.7.4 of Lavalink it turns out that the problem is solved, I think it comes from the update of lavaplayer to 1.4.0, the lavalink logs (same configuration) :

```
2023-05-17 20:16:21.626  INFO 230156 --- [XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "http://icecast.flazebot.com:8100/phonk_premium.ogg"
2023-05-17 20:16:21.902  INFO 230156 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track phonk
2023-05-17 20:16:21.905  INFO 230156 --- [XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : GET /v3/loadtracks?identifier=http://icecast.flazebot.com:8100/phonk_premium.ogg, client=192.168.0.2
```

## Version info
**Client used: Pomice**

Output of `java -version`:
```
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1deb11u1, mixed mode, sharing)
```
Output of `java -jar Lavalink.jar --version`:
```
Version:        3.7.5
Build time:     06.03.2023 12:02:05 UTC
Branch          HEAD
Commit:         c00286d
Commit time:    06.03.2023 11:59:46 UTC
JVM:            17.0.6
Lavaplayer      1.4.0-original
```

**Comment by TopiSenpai** [comment]
https://github.com/Walkyst/lavaplayer-fork/compare/1.3.99.2...1.4.0
seems like there was some work on ogg between those versions, please open an issue with lavaplayer instead

**Comment by chredeur0** [comment]
> [Walkyst/lavaplayer-fork@1.3.99.2...1.4.0](https://github.com/Walkyst/lavaplayer-fork/compare/1.3.99.2...1.4.0) seems like there was some work on ogg between those versions, please open an issue with lavaplayer instead

It's done. https://github.com/Walkyst/lavaplayer-fork/issues/101

**Comment by topi314** [comment]
This jar is based of master
https://godrive.zip/lavalink/Lavalink-ogg-stream-fix.jar (I can't attach jar files in github for whatever reason)

**Comment by chredeur** [comment]
> This jar is based of master https://godrive.zip/lavalink/Lavalink-ogg-stream-fix.jar (I can't attach jar files in github for whatever reason)

Thank you, after testing the patch solved the problem.

**Comment by topi314** [comment]
let's keep this open until we release a version with the fix
