### ISSUE TITLE
Unable to play the track.

### ISSUE THREAD

**Issue by ChandanOP** [lavalink-devs/Lavalink#885]
```
2|Lavalink  |   ... 28 common frames omitted
2|Lavalink  | 2023-05-23 14:13:03.282 ERROR 4161540 --- [ack-1-thread-71] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of kwN7DaBB4XE
2|Lavalink  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
2|Lavalink  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
2|Lavalink  |   at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
2|Lavalink  |   Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
2|Lavalink  |   lavaplayer.version: 1.4.0-original
2|Lavalink  |   os.arch: amd64
2|Lavalink  |   os.name: Linux
2|Lavalink  |   os.version: 5.4.0-42-generic
2|Lavalink  |   java.vendor: Azul Systems, Inc.
2|Lavalink  |   java.version: 13.0.5
2|Lavalink  |   java.runtime.version: 13.0.5+3-MTS
2|Lavalink  |   java.vm.version: 13.0.5+3-MTS
2|Lavalink  | Caused by: java.lang.RuntimeException: org.apache.http.conn.ConnectTimeoutException: Connect to rr4---sn-qxoedne7.googlevideo.com:443 [rr4---sn-qxoedne7.googlevideo.com/2607:f8b0:400f:1:0:0:0:9] failed: Connect timed out
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:56) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.0.jar!/:na]
2|Lavalink  |   ... 4 common frames omitted
2|Lavalink  | Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to rr4---sn-qxoedne7.googlevideo.com:443 [rr4---sn-qxoedne7.googlevideo.com/2607:f8b0:400f:1:0:0:0:9] failed: Connect timed out
2|Lavalink  |   at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination(ExtendedConnectionOperator.java:162) ~[lavaplayer-1.4.0.jar!/:na
```

**Comment by topi314** [comment]
This is either an issue with your network or youtube, nothing we can fix for you
