### ISSUE TITLE
Spotify doesnt work:

### ISSUE THREAD

**Issue by KasaiKonoru** [lavalink-devs/Lavalink#887]
```
lavalink.server.player.AudioLoader       : Load failed
0|lavalink  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.4.0.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.4.0.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:449) ~[lavaplayer-1.4.0.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:431) ~[lavaplayer-1.4.0.jar!/:na]
0|lavalink  |   at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-1.4.0.jar!/:na]
0|lavalink  |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
0|lavalink  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
0|lavalink  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
0|lavalink  |   at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
0|lavalink  |   Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
0|lavalink  |   lavaplayer.version: 1.4.0-original
0|lavalink  |   os.arch: amd64
0|lavalink  |   os.name: Linux
0|lavalink  |   os.version: 5.15.0-70-generic
0|lavalink  |   java.vendor: Oracle Corporation
0|lavalink  |   java.version: 13
0|lavalink  |   java.runtime.version: 13+33
0|lavalink  |   java.vm.version: 13+33
0|lavalink  | 2023-05-27 17:09:11.250  INFO 31380 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : GET /loadtracks?identifier=https%3A%2F%2Fopen.spotify.com%2Fintl-de%2Ftrack%2F4W4fNrZYkobj539TOWsLO2%3Fsi%3D91d0ebf2d8114b83, client=127.0.0.1
```

**Comment by devoxin** [comment]
Lavalink doesn't support Spotify out of the box. If you use a plugin, you'll need to open an issue on the plugin developer's repo.

**Comment by KasaiKonoru** [comment]
yeah sry, I got it. Spotify changed the uri format for tracks.... So I updated the regex
