### ISSUE TITLE
trying to start Lavalink.jar throws errors

### ISSUE THREAD

**Issue by fakesmile9704** [lavalink-devs/Lavalink#899]
## Description

I am trying to start the lavalink using `java -jar Lavalink.jar` but keeps erroring

## Version info
**Client used:** 

Output of `java -version`:
```
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-Ubuntu-0ubuntu322.04)
OpenJDK 64-Bit Server VM (build 19.0.2+7-Ubuntu-0ubuntu322.04, mixed mode, sharing)
```

```
Version:        3.7.6
Build time:     29.06.2023 23:49:57 UTC
Branch          HEAD
Commit:         40f0c80
Commit time:    29.06.2023 23:39:20 UTC
JVM:            19.0.2
Lavaplayer      1.4.2-original
```

```
2023-06-30 09:30:46.323  INFO 2977692 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 19.0.2 on ubuntu with PID 2977692 (/home/ubuntu/redlav/Lavalink.jar started by root in /home/ubuntu/redlav)
2023-06-30 09:30:46.327  INFO 2977692 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-06-30 09:30:47.411  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'lavalink-filter-plugin' version 0.0.1
2023-06-30 09:30:47.430  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded lavalink-filter-plugin-0.0.1.jar (1 classes)
2023-06-30 09:30:47.431  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'DuncteBot-plugin' version 1.4.1
2023-06-30 09:30:47.439  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded skybot-lavalink-plugin-1.4.1.jar (3 classes)
2023-06-30 09:30:47.440  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'lava-xm-plugin' version 0.2.1
2023-06-30 09:30:47.446  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded lava-xm-plugin-v0.2.1.jar (5 classes)
2023-06-30 09:30:47.447  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'SponsorBlock-Plugin' version 2.0.0
2023-06-30 09:30:47.468  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded sponsorblock-plugin-2.0.0.jar (4 classes)
2023-06-30 09:30:47.469  INFO 2977692 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'lavasrc' version 85b39d1
2023-06-30 09:30:47.475  WARN 2977692 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$9d5e5728]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: dev/arbjerg/lavalink/api/AudioPluginInfoModifier
2023-06-30 09:30:47.490  INFO 2977692 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-06-30 09:30:47.525 ERROR 2977692 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$9d5e5728]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: dev/arbjerg/lavalink/api/AudioPluginInfoModifier
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at lavalink.server.Launcher.launchPluginBootstrap(Launcher.kt:133) ~[classes!/:na]
        at lavalink.server.Launcher.main(Launcher.kt:125) ~[classes!/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[Lavalink.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$9d5e5728]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: dev/arbjerg/lavalink/api/AudioPluginInfoModifier
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.18.jar!/:5.3.18]
        ... 23 common frames omitted
Caused by: java.lang.NoClassDefFoundError: dev/arbjerg/lavalink/api/AudioPluginInfoModifier
        at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[na:na]
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[na:na]
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[na:na]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[na:na]
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[na:na]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) ~[na:na]
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        at lavalink.server.bootstrap.PluginManager.loadJar(PluginManager.kt:146) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager.loadJars(PluginManager.kt:115) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager.<init>(PluginManager.kt:29) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$9d5e5728.<init>(<generated>) ~[classes!/:na]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.18.jar!/:5.3.18]
        ... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: dev.arbjerg.lavalink.api.AudioPluginInfoModifier
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        ... 44 common frames omitted
```

**Comment by topi314** [comment]
this is not an issue with Lavalink.
You try to use LavaSrc vor Lavalink v4 with Lavalink v3
