### ISSUE TITLE
YouTube access token update failed.

### ISSUE THREAD

**Issue by legouju** [lavalink-devs/Lavalink#908]
## Description
![image](https://github.com/lavalink-devs/Lavalink/assets/44247490/bd255326-faba-47c7-b1fe-ba73290897a4)
## To Reproduce
Start the server
Send a request to play audio (im using a discord bot)
Watch logs and it spitts the error

The connection eventually times out as seen below:
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:249) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.4.2-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.10.0-20-amd64
  java.vendor: Debian
  java.version: 17.0.4
  java.runtime.version: 17.0.4+8-Debian-1deb11u1
  java.vm.version: 17.0.4+8-Debian-1deb11u1
Caused by: java.lang.RuntimeException: org.apache.http.conn.ConnectTimeoutException: Connect to rr3---sn-n4v7snl7.googlevideo.com:443 [rr3---sn-n4v7snl7.googlevideo.com/74.125.103.136, rr3---sn-n4v7snl7.googlevideo.com/2607:f8b0:4005:4:0:0:0:8] failed: Connect timed out
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:308) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275) ~[lavaplayer-1.4.2.jar!/:na]
        ... 10 common frames omitted
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to rr3---sn-n4v7snl7.googlevideo.com:443 [rr3---sn-n4v7snl7.googlevideo.com/74.125.103.136, rr3---sn-n4v7snl7.googlevideo.com/2607:f8b0:4005:4:0:0:0:8] failed: Connect timed out
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination(ExtendedConnectionOperator.java:162) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connect(ExtendedConnectionOperator.java:81) ~[lavaplayer-1.4.2.jar!/:na]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar!/:4.5.10]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:72) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:120) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubePersistentHttpStream.internalRead(YoutubePersistentHttpStream.java:52) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:193) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MutableMatroskaBlock.getNextFrameBuffer(MutableMatroskaBlock.java:54) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:371) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:335) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:320) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:296) ~[lavaplayer-1.4.2.jar!/:na]
        ... 12 common frames omitted
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator$AdditionalDetails: Encountered when opening a connection with the following details:
  host: https://rr3---sn-n4v7snl7.googlevideo.com:443
  localAddress: <unspecified>
  remoteAddress: rr3---sn-n4v7snl7.googlevideo.com/[2607:f8b0:4005:4:0:0:0:8]:443
  connectTimeout: 3000
  triedAddresses: rr3---sn-n4v7snl7.googlevideo.com/74.125.103.136, rr3---sn-n4v7snl7.googlevideo.com/2607:f8b0:4005:4:0:0:0:8
Caused by: java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[httpclient-4.5.10.jar!/:4.5.10]
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination(ExtendedConnectionOperator.java:157) ~[lavaplayer-1.4.2.jar!/:na]
        ... 32 common frames omitted

2023-07-06 16:00:42.705  INFO 1468779 --- [XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"967619403317411860"}
2023-07-06 16:01:06.548  INFO 1468779 --- [SpringApplicationShutdownHook] io.undertow                              : stopping server: Undertow - 2.2.16.Final
2023-07-06 16:01:06.550 ERROR 1468779 --- [XNIO-1 I/O-5] org.xnio.listener                        : XNIO001007: A channel event listener threw an exception

```

## Expected behavior
Lavalink not skipping the audio/request and playing the whole track with no issue

## Version info
**Client used:** 3.7.6

Output of `java -version`:
```
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1deb11u1, mixed mode, sharing)
```

Lavalink Logs:

[logs.txt](https://github.com/lavalink-devs/Lavalink/files/11987088/logs.txt)

## Additional context
When it skips it Causes a "something went wrong with decoding the file"
Most likely because Google is timing out the connection (see logs)

**Comment by topi314** [comment]
This is an issue with lavaplayer
Please open an issue there instead 
https://github.com/Walkyst/lavaplayer-fork/issues/new

**Comment by topi314** [comment]
can you see if this build fixes the issue?
https://github.com/lavalink-devs/Lavalink/tree/patch/yt-access-token

**Comment by topi314** [comment]
this has been fixed in
<https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.0-beta.3>
<https://github.com/lavalink-devs/Lavalink/releases/tag/3.7.8>
