### ISSUE TITLE
LiveStream on V4

### ISSUE THREAD

**Issue by Caio-Sc** [lavalink-devs/Lavalink#922]
## Description
when you play a YouTube livestream, destroy the player and try to play another livestream, it won't play on v4.
It also happens when you close your bot while playing a stream.
After that, only restarting lavalink or playing another song and skipping to the livestream to start working again.
I had never used lavalink, so I went back to 3.7 and switched to erela.js and the problem won't happen, so I guess it is a v4 problem or a magmastream is messing something up.
I also noticed that if you play a livestream and close the bot it will continue to play it after closed (the bot won't disconnect or anything)

## To Reproduce
1. Start playing a livestream from YouTube
2. use a stop command to delete the player.
3. use the play command again to play the livestream

## Expected behavior
I expected it to play the stream, but it just sits there and won't play anything.
## Version info
**Client used:** magmastream

Output of `java -version`:
``` 
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
```

Lavalink Logs:
```
2023-07-21T07:08:19.420581574Z  2023-07-21T04:08:19.420-03:00  INFO 1 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=jfKfPfyJRdk"
2023-07-21T07:08:19.469610449Z  2023-07-21T04:08:19.469-03:00  INFO 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track lofi hip hop radio  - beats to relax/study to
2023-07-21T07:08:19.472026676Z  2023-07-21T04:08:19.471-03:00  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DjfKfPfyJRdk, client=51.81.38.169
2023-07-21T07:08:19.662121940Z  2023-07-21T04:08:19.661-03:00  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/0guj86u9g6hucykf/players/1119839379947532348?noReplace=false, client=51.81.38.169, payload={"volume":100}
2023-07-21T07:08:19.665614938Z  2023-07-21T04:08:19.665-03:00  INFO 1 --- [  XNIO-1 task-4] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/0guj86u9g6hucykf/players/1119839379947532348?noReplace=false, client=51.81.38.169, payload={"encodedTrack":"QAAA2QMAM2xvZmkgaGlwIGhvcCByYWRpbyDtoL3ts5ogLSBiZWF0cyB0byByZWxheC9zdHVkeSB0bwAJTG9maSBHaXJsf/////////8AC2pmS2ZQZnlKUmRrAQEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9amZLZlBmeUpSZGsBAD9odHRwczovL2kueXRpbWcuY29tL3ZpL2pmS2ZQZnlKUmRrL21heHJlc2RlZmF1bHQuanBnP3Y9NjQzNTk2NjQAAAd5b3V0dWJlAAAAAAAAAAA="}
2023-07-21T07:08:20.378245951Z  2023-07-21T04:08:20.377-03:00  INFO 1 --- [  XNIO-1 task-4] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/0guj86u9g6hucykf/players/1119839379947532348?noReplace=false, client=51.81.38.169, payload={"voice":{"token":"06d0ba9ba4bb1691","endpoint":"brazil1570.discord.media:443","sessionId":"6c8988081db59b100a10422d4eef731f"}}
2023-07-21T07:08:20.406897402Z  2023-07-21T04:08:20.378-03:00 ERROR 1 --- [  XNIO-1 task-4] io.undertow.request                      : UT005023: Exception handling request to /v4/sessions/0guj86u9g6hucykf/players/1119839379947532348
2023-07-21T07:08:20.406929262Z  
2023-07-21T07:08:20.406934932Z  jakarta.servlet.ServletException: Request processing failed: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack$TrackState.access$300(com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack$TrackState)" is null
2023-07-21T07:08:20.406941154Z  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1019) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.406946083Z  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:888) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.406950862Z  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar!/:6.0.0]
2023-07-21T07:08:20.406955441Z  at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.406960140Z  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.406965059Z  at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:289) ~[spring-web-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.406969828Z  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.406974607Z  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.406979296Z  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.406984396Z  at lavalink.server.io.ResponseHeaderFilter.doFilterInternal(ResponseHeaderFilter.kt:17) ~[classes!/:4.0.0-beta.1]
2023-07-21T07:08:20.406988974Z  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.406994946Z  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.406999765Z  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407004504Z  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407009212Z  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407014012Z  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407024712Z  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407029601Z  at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407034270Z  at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407039049Z  at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407043758Z  at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407050210Z  at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407054999Z  at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407060078Z  at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407064998Z  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407070037Z  at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407074876Z  at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407079725Z  at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407084464Z  at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407089233Z  at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407094243Z  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407099042Z  at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407103781Z  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407108360Z  at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407115924Z  at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407120603Z  at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407125251Z  at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407130050Z  at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407135451Z  at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407140390Z  at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101) ~[undertow-servlet-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407145119Z  at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407149738Z  at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859) ~[undertow-core-2.3.6.Final.jar!/:2.3.6.Final]
2023-07-21T07:08:20.407154346Z  at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
2023-07-21T07:08:20.407158895Z  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
2023-07-21T07:08:20.407163524Z  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538) ~[jboss-threads-3.5.0.Final.jar!/:3.5.0.Final]
2023-07-21T07:08:20.407168323Z  at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) ~[xnio-api-3.8.8.Final.jar!/:3.8.8.Final]
2023-07-21T07:08:20.407173031Z  at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
2023-07-21T07:08:20.407177670Z  Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack$TrackState.access$300(com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack$TrackState)" is null
2023-07-21T07:08:20.407183231Z  at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMpegStreamAudioTrack.getPosition(YoutubeMpegStreamAudioTrack.java:80) ~[lavaplayer-17c75f5.jar!/:na]
2023-07-21T07:08:20.407187930Z  at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.getPosition(DelegatedAudioTrack.java:61) ~[lavaplayer-17c75f5.jar!/:na]
2023-07-21T07:08:20.407192538Z  at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.encodeTrack(DefaultAudioPlayerManager.java:264) ~[lavaplayer-17c75f5.jar!/:na]
2023-07-21T07:08:20.407197167Z  at lavalink.server.util.UtilKt.encodeTrack(util.kt:138) ~[classes!/:4.0.0-beta.1]
2023-07-21T07:08:20.407201615Z  at lavalink.server.util.UtilKt.toTrack(util.kt:48) ~[classes!/:4.0.0-beta.1]
2023-07-21T07:08:20.407209049Z  at lavalink.server.util.UtilKt.toPlayer(util.kt:97) ~[classes!/:4.0.0-beta.1]
2023-07-21T07:08:20.407213909Z  at lavalink.server.player.PlayerRestHandler.patchPlayer(PlayerRestHandler.kt:212) ~[classes!/:4.0.0-beta.1]
2023-07-21T07:08:20.407218658Z  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
2023-07-21T07:08:20.407223186Z  at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
2023-07-21T07:08:20.407227564Z  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407232183Z  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407236862Z  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407241621Z  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407246450Z  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407251219Z  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407255958Z  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407260557Z  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407265135Z  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.9.jar!/:6.0.9]
2023-07-21T07:08:20.407269764Z  ... 46 common frames omitted

```

**Comment by topi314** [comment]
> when you play a YouTube livestream, destroy the player and try to play another livestream, it won't play on v4.

I can't reproduce this issue. playing multiple yt livestreams after each other works fine for me
```
2023-07-21T10:32:29.340Z  INFO 1 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=4xDzrJKXOOY"
2023-07-21T10:32:29.344Z  WARN 1 --- [ader-2-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
2023-07-21T10:32:29.647Z  INFO 1 --- [ader-2-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube visitor id (current is null).
2023-07-21T10:32:29.765Z  INFO 1 --- [ader-2-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube visitor id succeeded, new one is CgtDc3RKQy1tcnpFNCi9vemlBg%3D%3D, next update will be after 600 seconds.
2023-07-21T10:32:29.842Z  INFO 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track synthwave radio 🌌 - beats to chill/game to
2023-07-21T10:32:29.867Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D4xDzrJKXOOY, client=172.22.0.3
2023-07-21T10:32:30.236Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/aur24wultfpkl60o/players/1082302532421943407?noReplace=false, client=172.22.0.3, payload={"encodedTrack":"QAAA1QMAL3N5bnRod2F2ZSByYWRpbyDtoLztvIwgLSBiZWF0cyB0byBjaGlsbC9nYW1lIHRvAAlMb2ZpIEdpcmx//////////wALNHhEenJKS1hPT1kBAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj00eER6ckpLWE9PWQEAP2h0dHBzOi8vaS55dGltZy5jb20vdmkvNHhEenJKS1hPT1kvbWF4cmVzZGVmYXVsdC5qcGc/dj02NGEyN2NkMAAAB3lvdXR1YmUAAAAAAAAAAA=="}
2023-07-21T10:32:30.589Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/aur24wultfpkl60o/players/1082302532421943407?noReplace=false, client=172.22.0.3, payload={"voice":{"token":"aba269d316473e6d","endpoint":"rotterdam2708.discord.media:443","sessionId":"a28a74120984b98f6ed8332b15200707"}}
2023-07-21T10:32:47.386Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/aur24wultfpkl60o/players/1082302532421943407, client=172.22.0.3
2023-07-21T10:32:54.240Z  INFO 1 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=4xDzrJKXOOY"
2023-07-21T10:32:54.304Z  INFO 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track synthwave radio 🌌 - beats to chill/game to
2023-07-21T10:32:54.307Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D4xDzrJKXOOY, client=172.22.0.3
2023-07-21T10:32:54.543Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/aur24wultfpkl60o/players/1082302532421943407?noReplace=false, client=172.22.0.3, payload={"encodedTrack":"QAAA1QMAL3N5bnRod2F2ZSByYWRpbyDtoLztvIwgLSBiZWF0cyB0byBjaGlsbC9nYW1lIHRvAAlMb2ZpIEdpcmx//////////wALNHhEenJKS1hPT1kBAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj00eER6ckpLWE9PWQEAP2h0dHBzOi8vaS55dGltZy5jb20vdmkvNHhEenJKS1hPT1kvbWF4cmVzZGVmYXVsdC5qcGc/dj02NGEyN2NkMAAAB3lvdXR1YmUAAAAAAAAAAA=="}
2023-07-21T10:32:54.891Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/aur24wultfpkl60o/players/1082302532421943407?noReplace=false, client=172.22.0.3, payload={"voice":{"token":"6d998bf3f43aead0","endpoint":"rotterdam2708.discord.media:443","sessionId":"a28a74120984b98f6ed8332b15200707"}}
2023-07-21T10:33:04.368Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/aur24wultfpkl60o/players/1082302532421943407, client=172.22.0.3
2023-07-21T10:33:08.209Z  INFO 1 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=jfKfPfyJRdk"
2023-07-21T10:33:08.286Z  INFO 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track lofi hip hop radio 📚 - beats to relax/study to
2023-07-21T10:33:08.287Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DjfKfPfyJRdk, client=172.22.0.3
2023-07-21T10:33:08.539Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/aur24wultfpkl60o/players/1082302532421943407?noReplace=false, client=172.22.0.3, payload={"encodedTrack":"QAAA2QMAM2xvZmkgaGlwIGhvcCByYWRpbyDtoL3ts5ogLSBiZWF0cyB0byByZWxheC9zdHVkeSB0bwAJTG9maSBHaXJsf/////////8AC2pmS2ZQZnlKUmRrAQEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9amZLZlBmeUpSZGsBAD9odHRwczovL2kueXRpbWcuY29tL3ZpL2pmS2ZQZnlKUmRrL21heHJlc2RlZmF1bHQuanBnP3Y9NjQzNTk2NjQAAAd5b3V0dWJlAAAAAAAAAAA="}
2023-07-21T10:33:08.924Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/aur24wultfpkl60o/players/1082302532421943407?noReplace=false, client=172.22.0.3, payload={"voice":{"token":"d1c54f6ab1a46846","endpoint":"rotterdam2708.discord.media:443","sessionId":"a28a74120984b98f6ed8332b15200707"}}
```

>  I also noticed that if you play a livestream and close the bot it will continue to play it after closed (the bot won't disconnect or anything)

this has to do with how you close your bot and is not a lavalink issue, close your discord gateway connection properly and this won't happen

**Comment by Caio-Sc** [comment]
It was my host I guess, I'm sorry

**Comment by Caio-Sc** [comment]
After some testing, I noticed that, for some reason, this only happens on the host I'm using. The problem won't happen when lavalink is hosted on my pc or another host. I still don't know what the cause of it, but I've been talking to the host support, and they think it could still have something to do with lavalink. I'm using another host for lavalink for now, so this is just more info on the problem because I still don't know what cause it

**Comment by topi314** [comment]
since this is most likely an issue with lavaplayer it would prob be more appropriate to open an issue there
