### ISSUE TITLE
[v4 beta 2] Failed to collect additional information on OGG stream

### ISSUE THREAD

**Issue by PapiOphidian** [lavalink-devs/Lavalink#925]
## Description
Attempting to play an opus stream does work for a second, then I'm assuming on the next chunk, the audio fails and the track halts.

## To Reproduce
The track I used was
https://listen.moe/opus
I tested with regular opus files and those seem to work okay. Unsure if it's just limited to opus live streams or not. I don't know of many to test with

## Expected behavior
The track to continue past the first chunk

## Version info
**Client used:** Lavacord/2.1.0-v4

Output of `java -version`: 
```
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu122.04.2)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu122.04.2, mixed mode, sharing)
```

Lavalink Logs:
```
2023-07-27T05:45:51.151-04:00  INFO 28378 --- [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://listen.moe/opus"
2023-07-27T05:45:51.586-04:00  WARN 28378 --- [ader-2-thread-1] c.s.d.l.container.ogg.OggContainerProbe  : Failed to collect additional information on OGG stream.

java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "length" is null
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggMetadata.<init>(OggMetadata.java:26) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.opus.OggOpusCodecHandler.loadMetadata(OggOpusCodecHandler.java:60) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggTrackLoader.loadMetadata(OggTrackLoader.java:37) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggContainerProbe.collectStreamInformation(OggContainerProbe.java:62) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggContainerProbe.probe(OggContainerProbe.java:47) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:91) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:76) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:61) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.detectContainerWithClient(HttpAudioSourceManager.java:143) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.detectContainer(HttpAudioSourceManager.java:121) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:82) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:452) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:434) ~[lavaplayer-08cfbc0595.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-08cfbc0595.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-07-27T05:45:51.591-04:00  INFO 28378 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Delivering the best Japanese and Anime music around the globe!
2023-07-27T05:45:51.593-04:00  INFO 28378 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Flisten.moe%2Fopus, client=144.172.67.128
2023-07-27T05:45:51.608-04:00  INFO 28378 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/qtpj4yupgvdzrong/players/497159726455455754, client=144.172.67.128, payload={"encodedTrack":"QAAAngMAPkRlbGl2ZXJpbmcgdGhlIGJlc3QgSmFwYW5lc2UgYW5kIEFuaW1lIG11c2ljIGFyb3VuZCB0aGUgZ2xvYmUhAApMSVNURU4ubW9lf/////////8AF2h0dHBzOi8vbGlzdGVuLm1vZS9vcHVzAQEAF2h0dHBzOi8vbGlzdGVuLm1vZS9vcHVzAAAABGh0dHAAA29nZwAAAAAAAAAA"}
2023-07-27T05:46:58.804-04:00  INFO 28378 --- [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/qtpj4yupgvdzrong/players/497159726455455754, client=144.172.67.128
```

## Additional context
I had this issue on v4 beta 1 as well

**Comment by topi314** [comment]
please open an issue with lavaplayer instead
