### ISSUE TITLE
Unsuported new Spotify link

### ISSUE THREAD

**Issue by FabienBounoir** [lavalink-devs/Lavalink#926]
## Expected behavior
Depending on the language of our spotify client, the copy url is not the same and integrates "intl-fr" for French or "intl-pt" for Portuguese. 

## Version info
**Client used:** 3.7.5

Lavalink Logs:
```
lavalink_dev  | 2023-07-27 19:34:03.968  INFO 1 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/intl-fr/track/0z73R0XtUKDlh7vdmnZuiV?si=9f47e33de14643f6"
lavalink_dev  | 2023-07-27 19:34:04.391 ERROR 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed
lavalink_dev  | 
lavalink_dev  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
lavalink_dev  | 	at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.4.0.jar!/:na]
lavalink_dev  | 	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.4.0.jar!/:na]
lavalink_dev  | 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:449) ~[lavaplayer-1.4.0.jar!/:na]
lavalink_dev  | 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:431) ~[lavaplayer-1.4.0.jar!/:na]
lavalink_dev  | 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-1.4.0.jar!/:na]
lavalink_dev  | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
lavalink_dev  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
lavalink_dev  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
lavalink_dev  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
lavalink_dev  | 	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
lavalink_dev  |   lavaplayer.version: 1.4.0-original
lavalink_dev  |   os.arch: amd64
lavalink_dev  |   os.name: Linux
lavalink_dev  |   os.version: 5.15.49-linuxkit
lavalink_dev  |   java.vendor: Eclipse Adoptium
lavalink_dev  |   java.version: 18.0.2.1
lavalink_dev  |   java.runtime.version: 18.0.2.1+1
lavalink_dev  |   java.vm.version: 18.0.2.1+1
lavalink_dev  | 
```

**Comment by topi314** [comment]
Lavalink does not support Spotify
I assume you're taking about lavasrc, which in this case you should perhaps update
