### ISSUE TITLE
No sound from discord bot . Bot is just ending the track 

### ISSUE THREAD

**Issue by munishkhatri720** [lavalink-devs/Lavalink#928]
## Description
Getting some error on lavalink server console . On requesting some tracks .
## To Reproduce
1. Most of the time when you enter a spotify playlist 
2. I am using wavelink 2.6.2 
3. Happening randomly for some tracks

## Expected behavior
Facing this issue after updating lavalink version.

## Version info
Wavelink 2.6.2

Output of `java -version`:
 os.name: Linux
  os.version: 5.4.0-122-generic
  java.vendor: Oracle Corporation
  java.version: 13.0.2
  java.runtime.version: 13.0.2+8
  java.vm.version: 13.0.2+8

Lavalink Logs:
 os.name: Linux
  os.version: 5.4.0-122-generic
  java.vendor: Oracle Corporation
  java.version: 13.0.2
  java.runtime.version: 13.0.2+8
  java.vm.version: 13.0.2+8
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:123) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:157) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:173) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.2.jar!/:na]
        ... 4 common frames omitted

2023-08-01 04:44:35.651  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAegIAGUthYWxpIENhciAoTG9maSArIFJldmVyYikAB1JhZnRhYXIAAAAAAANACAALQV9RbTF2bGJDRTgAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1BX1FtMXZsYkNFOAAHeW91dHViZQAAAAAAAAAA, client=223.238.221.92
2023-08-01 04:44:35.771  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAegIAGUthYWxpIENhciAoTG9maSArIFJldmVyYikAB1JhZnRhYXIAAAAAAANACAALQV9RbTF2bGJDRTgAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1BX1FtMXZsYkNFOAAHeW91dHViZQAAAAAAAAAA, client=223.238.221.92
2023-08-01 04:44:38.549  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/0siqcwo3ry38t270/players/1103581564513824828?noReplace=False, client=223.238.221.92, payload={"encodedTrack": "QAAAvgIAWFBSSUNFTEVTUyB8IEJIQUxXQUFOICYgU0lHTkFUVVJFIEJZIFNCIHwgSEFQUFkgR0FSSEkgfCBGUkVRIFJFQ09SRFMgfCAoUFJJQ0VMRVNTIFRIRSBFUCkADEZyZXEgUmVjb3JkcwAAAAAAAczwAAt2OGZjQW9iUFpmRQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PXY4ZmNBb2JQWmZFAAd5b3V0dWJlAAAAAAAAAAA=", "position": 0, "volume": 50}
2023-08-01 04:44:38.894 ERROR 25 --- [back-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of v8fcAobPZfE

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.4.2-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-122-generic
  java.vendor: Oracle Corporation
  java.version: 13.0.2
  java.runtime.version: 13.0.2+8
  java.vm.version: 13.0.2+8
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:123) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:157) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:173) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.2.jar!/:na]
        ... 4 common frames omitted

2023-08-01 04:44:40.122  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAvgIAWFBSSUNFTEVTUyB8IEJIQUxXQUFOICYgU0lHTkFUVVJFIEJZIFNCIHwgSEFQUFkgR0FSSEkgfCBGUkVRIFJFQ09SRFMgfCAoUFJJQ0VMRVNTIFRIRSBFUCkADEZyZXEgUmVjb3JkcwAAAAAAAczwAAt2OGZjQW9iUFpmRQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PXY4ZmNBb2JQWmZFAAd5b3V0dWJlAAAAAAAAAAA%3D, client=223.238.221.92
2023-08-01 04:44:40.214  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAvgIAWFBSSUNFTEVTUyB8IEJIQUxXQUFOICYgU0lHTkFUVVJFIEJZIFNCIHwgSEFQUFkgR0FSSEkgfCBGUkVRIFJFQ09SRFMgfCAoUFJJQ0VMRVNTIFRIRSBFUCkADEZyZXEgUmVjb3JkcwAAAAAAAczwAAt2OGZjQW9iUFpmRQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PXY4ZmNBb2JQWmZFAAd5b3V0dWJlAAAAAAAAAAA%3D, client=223.238.221.92
2023-08-01 04:44:43.426  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAvgIAWFBSSUNFTEVTUyB8IEJIQUxXQUFOICYgU0lHTkFUVVJFIEJZIFNCIHwgSEFQUFkgR0FSSEkgfCBGUkVRIFJFQ09SRFMgfCAoUFJJQ0VMRVNTIFRIRSBFUCkADEZyZXEgUmVjb3JkcwAAAAAAAczwAAt2OGZjQW9iUFpmRQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PXY4ZmNBb2JQWmZFAAd5b3V0dWJlAAAAAAAAAAA%3D, client=223.238.221.92
2023-08-01 04:44:48.222  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/0siqcwo3ry38t270/players/1103581564513824828?noReplace=False, client=223.238.221.92, payload={"encodedTrack": "QAAAvAIAWk9GRklDSUFMOiAnSW5kaWEgV2FhbGUnIEZVTEwgVklERU8gU29uZyB8SGFwcHkgTmV3IFllYXIgfCBTaGFoIFJ1a2ggS2hhbiwgRGVlcGlrYSBQYWR1a29uZQAIVC1TZXJpZXMAAAAAAAOhsAALWC1ERGtuU3pFTEkAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1YLUREa25TekVMSQAHeW91dHViZQAAAAAAAAAA", "position": 0, "volume": 50}
2023-08-01 04:44:48.308  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAvAIAWk9GRklDSUFMOiAnSW5kaWEgV2FhbGUnIEZVTEwgVklERU8gU29uZyB8SGFwcHkgTmV3IFllYXIgfCBTaGFoIFJ1a2ggS2hhbiwgRGVlcGlrYSBQYWR1a29uZQAIVC1TZXJpZXMAAAAAAAOhsAALWC1ERGtuU3pFTEkAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1YLUREa25TekVMSQAHeW91dHViZQAAAAAAAAAA, client=223.238.221.92
2023-08-01 04:44:48.442 ERROR 25 --- [back-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of X-DDknSzELI

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.4.2-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-122-generic
  java.vendor: Oracle Corporation
  java.version: 13.0.2
  java.runtime.version: 13.0.2+8
  java.vm.version: 13.0.2+8
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:123) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:157) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:173) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.2.jar!/:na]
        ... 4 common frames omitted

2023-08-01 04:44:51.140  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAvAIAWk9GRklDSUFMOiAnSW5kaWEgV2FhbGUnIEZVTEwgVklERU8gU29uZyB8SGFwcHkgTmV3IFllYXIgfCBTaGFoIFJ1a2ggS2hhbiwgRGVlcGlrYSBQYWR1a29uZQAIVC1TZXJpZXMAAAAAAAOhsAALWC1ERGtuU3pFTEkAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1YLUREa25TekVMSQAHeW91dHViZQAAAAAAAAAA, client=223.238.221.92
2023-08-01 04:44:51.230  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAvAIAWk9GRklDSUFMOiAnSW5kaWEgV2FhbGUnIEZVTEwgVklERU8gU29uZyB8SGFwcHkgTmV3IFllYXIgfCBTaGFoIFJ1a2ggS2hhbiwgRGVlcGlrYSBQYWR1a29uZQAIVC1TZXJpZXMAAAAAAAOhsAALWC1ERGtuU3pFTEkAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1YLUREa25TekVMSQAHeW91dHViZQAAAAAAAAAA, client=223.238.221.92
2023-08-01 04:44:54.246  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/0siqcwo3ry38t270/players/1103581564513824828?noReplace=False, client=223.238.221.92, payload={"encodedTrack": "QAAAfQIAF0doYW5hIE5hc2hpbGEgUm9vcCBUZXJhAAxSYWp1IFB1bmphYmkAAAAAAANfSAALRHROVWdxcE16XzAAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1EdE5VZ3FwTXpfMAAHeW91dHViZQAAAAAAAAAA", "position": 0, "volume": 50}
2023-08-01 04:44:54.350  INFO 25 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /v3/decodetrack?encodedTrack=QAAAfQIAF0doYW5hIE5hc2hpbGEgUm9vcCBUZXJhAAxSYWp1IFB1bmphYmkAAAAAAANfSAALRHROVWdxcE16XzAAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1EdE5VZ3FwTXpfMAAHeW91dHViZQAAAAAAAAAA, client=223.238.221.92
2023-08-01 04:44:54.747 ERROR 25 --- [back-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of DtNUgqpMz_0

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.4.2-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.0-122-generic
  java.vendor: Oracle Corporation
  java.version: 13.0.2
  java.runtime.version: 13.0.2+8
  java.vm.version: 13.0.2+8
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:123) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:157) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:173) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:270) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.2.jar!/:na]
        ... 4 common frames omitted

**Comment by AADI0009** [comment]
Duplicate of #897

**Comment by munishkhatri720** [comment]
> Duplicate of #897

are you facing the same issue. I think this is lavalink 3.7.7 version problem.

**Comment by KagChi** [comment]
This is lavaplayer issue not lavalink. they are aware of this issue

**Comment by ItzRandom23** [comment]
same issue here
