### ISSUE TITLE
Issue with updating volume on any stream/track with latest Lavalink Dev build

### ISSUE THREAD

**Issue by shikhir-arora** [lavalink-devs/Lavalink#94]
When loading an OPUS stream in this case, http://janus.cdnstream.com:5397/autodj - with the new Lavalink Dev branch update (with the new Lavaplayer version 1.2.63 that gets Ogg/Opus metadata as well as icy*- metadata from streams such as this one), the following error occurs using FredBoat (so the Java LavalinkClient):

https://hastebin.com/wiqapotogi.log https://sentry.io/share/issue/6be7059e02494827b2c05f243a288bb7/

```
[2018-04-14 00:44:16,129] [ INFO ] [WebSocketWorker-18] lavalink.server.io.SocketServer: {"volume":100,"op":"play","startTime":0,"track":"QAAAhQIAA0VDRAAQRUMgRGlzY29yZCBSYWRpb3//////////ACZodHRwOi8vamFudXMuY2Ruc3RyZWFtLmNvbTo1Mzk3L2F1dG9kagEBACZodHRwOi8vamFudXMuY2Ruc3RyZWFtLmNvbTo1Mzk3L2F1dG9kagAEaHR0cAADb2dnAAAAAAAAAAA=","guildId":"249664293656592384","pause":false}

```

---

Now using Lavaplayer 1.2.63 directly doesn't have any issues on another implementation -- and using a different (here just JS) Lavalink client implementation it works fine **except/until** sending a `volume` update (for this client implementation) that is not unity/100 causes the stream to end with the same decoding error:

```
[01:12:56] [ INFO ] [SocketServer] {"op":"play","guildId":"249664293656592384","track":"QAAAhQIAA0VDRAAQRUMgRGlzY29yZCBSYWRpb3//////////ACZodHRwOi8vamFudXMuY2Ruc3RyZWFtLmNvbTo1Mzk3L2F1dG9kagEBACZodHRwOi8vamFudXMuY2Ruc3RyZWFtLmNvbTo1Mzk3L2F1dG9kagAEaHR0cAADb2dnAAAAAAAAAAA="}
[01:14:01] [ INFO ] [SocketServer] {"op":"volume","guildId":"249664293656592384","volume":1}
[01:14:02] [ ERROR] [LocalAudioTrackExecutor] Error in playback of http://janus.cdnstream.com:5397/autodj
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:260)
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.process(OggAudioTrack.java:40)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
	at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:51)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:357)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException: Encoding failed with error -1
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusEncoder.encode(OpusEncoder.java:47)
	at com.sedmelluq.discord.lavaplayer.format.transcoder.OpusChunkEncoder.encode(OpusChunkEncoder.java:30)
	at com.sedmelluq.discord.lavaplayer.filter.volume.AudioFrameVolumeChanger.rebuild(AudioFrameVolumeChanger.java:61)
	at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameBuffer.rebuild(AudioFrameBuffer.java:215)
	at com.sedmelluq.discord.lavaplayer.filter.volume.AudioFrameVolumeChanger.apply(AudioFrameVolumeChanger.java:105)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:170)
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:85)
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggOpusTrackProvider.provideFrames(OggOpusTrackProvider.java:90)
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.processTrackLoop(OggAudioTrack.java:59)
	at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.lambda$process$0(OggAudioTrack.java:42)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:248)
	... 8 common frames omitted
```

The stream here does work fine, except the `volume` update breaks it with the same encoding error.

The reasons I can see this happening are:

1) Something with `startTime` and `volume` with Lavalink/client
2) Passing the `play` op without a `startTime` or `volume` by default (as seen above) works fine; so it must be something to do with one of those (volume/startTime)
3) There aren't issues directly with Lavaplayer: using 1.2.63 with Lavaplayer directly works fine, including volume changes.

**Comment by shikhir-arora** [comment]
It's not limited to streams; changing volume for normal YouTube tracks breaks with the same `Encoding -1` error on any Lavalink implementation using the new Lavaplayer (1.2.63) -- due to changes in https://github.com/sedmelluq/lavaplayer/commit/81672b21266096c411f2093138332534c65f7aee

**Comment by freyacodes** [comment]
That sounds odd. Can you check if 33b639b works now?

**Comment by shikhir-arora** [comment]
Yes, that works fine as expected, it would have to do with the changes in AudioTrackBuilder I'd assume in 1.2.63 since it got a bit of a change.

This doesn't affect Lavaplayer clients directly, they work perfectly fine, just Lavalink, so it's something on that end. Doesn't matter the source, the volume op is broken - https://sentry.io/share/issue/9e36d12515924524967490d692c723ff/


Also if it helps, seeking works fine, so it's just a volume change. Presumably something with some buffer change since sending a 100 volume (unity) doesn't break it, only when it has to encode from volume changes.

**Comment by shikhir-arora** [comment]
One thing that may help: https://github.com/Frederikam/Lavalink/commit/d643aea7219b2b016cbb98ea3daf445cb2e4d424 -- the addition of `volume` in the `play` op for the Lavalink client here caused the player to throw the error right away (i.e. with FredBoat that uses the Java client), while using another client implementation that doesn't send the volume with the play op (as shown in the initial post) works fine, until a manual volume change op is sent.

**Comment by shikhir-arora** [comment]
Strangely enough after going back, trying it a different way and looking at the process in more detail - it seemed to be an odd user permission issue with the systemd profile I was using. It works fine now and I've tested that on two servers, so it should be fine to push back to 1.2.63 -- sorry about any hassle. Was certainly not what I was expecting. 🧐
