### ISSUE TITLE
SIGSEV on libc.so.6+0x9409d

### ISSUE THREAD

**Issue by itsfolf** [lavalink-devs/Lavalink#95]
I'm getting a java fatal error when running lavalink's latest version, the log is on pastebin, [here](http://paste.ubuntu.com/p/HBKJR3VHj7/).

**Comment by Shredder121** [comment]
Not sure what went wrong, but the current thread has a bunch of exceptions that shouldn't be thrown on a clean JRE.
![image](https://user-images.githubusercontent.com/4105066/39325783-5c741cd8-4993-11e8-9a89-623790b8488a.png)

**Comment by itsfolf** [comment]
Seems to be a issue that was fixed in java 9, since I'm still on 8 I fixed it using ` -Dsun.zip.disableMemoryMapping=true`

**Comment by itsfolf** [comment]
I am now getting `NoClassDefFoundError: com/sedmelluq/discord/lavaplayer/jdaudp/NativeAudioSendFactory` every time a song starts.
```
Uncaught exception in thread "WebSocketWorker-16":java.lang.NoClassDefFoundError: com/sedmelluq/discord/lavaplayer/jdaudp/NativeAudioSendFactory
        at lavalink.server.io.SocketContext.lambda$getAudioSendFactory$7(SocketContext.java:146)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at lavalink.server.io.SocketContext.getAudioSendFactory(SocketContext.java:141)
        at lavalink.server.io.SocketContext.lambda$getCore$3(SocketContext.java:90)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
        at lavalink.server.io.SocketContext.getCore(SocketContext.java:87)
        at lavalink.server.io.SocketServer.onMessage(SocketServer.java:192)
        at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:551)
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:888)
Caused by: java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 12 more
```

**Comment by freyacodes** [comment]
Unrelated issue. I opened an issue here instead:

https://github.com/Frederikam/Lavalink/issues/96
