### ISSUE TITLE
ERROR Invalid status code for youtube embed video id: 500

### ISSUE THREAD

**Issue by Nashiauwu** [lavalink-devs/Lavalink#977]
## Description
When i try to play audio using lavalink i get this error:

Invalid status code for youtube embed video id: 500

## To Reproduce
1. run Lavalink 3.7.9
2. try to play audio get error 500

## Expected behavior
after updating my outdated lavalink to my current version (3.7.9) I expected it to finally play music

## Version info
**Client used:** erela.js (https://github.com/wtfnotavailable/Discord-MusicBot)

Output of `java -version`:
```
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu17.46+19-CA (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.46+19-CA (build 17.0.9+8-LTS, mixed mode, sharing)



Lavalink Logs:
```
`2023-11-05 15:01:17.706  INFO 7756 --- [main] lavalink.server.Launcher                 : Starting Launcher using Java 17.0.9 on nashiasrv with PID 7756 (/home/nashia/ftp/files/wlasniak/lavalink/Lavalink.jar started by nashia in /home/nashia/ftp/files/wlasniak/lavalink)
2023-11-05 15:01:17.710  INFO 7756 --- [main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-11-05 15:01:18.466  INFO 7756 --- [main] lavalink.server.Launcher                 : Started Launcher in 1.322 seconds (JVM running for 1.697)
2023-11-05 15:01:18.468  INFO 7756 --- [main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/lavalink-devs/Lavalink/issues/295
2023-11-05 15:01:18.515  INFO 7756 --- [main] lavalink.server.Launcher                 : 

[32m       .  [31m _                  _ _       _    [32m__ _ _
[32m      /\\ [31m| | __ ___   ____ _| (_)_ __ | | __[32m\ \ \ \
[32m     ( ( )[31m| |/ _` \ \ / / _` | | | '_ \| |/ /[32m \ \ \ \
[32m      \\/ [31m| | (_| |\ V / (_| | | | | | |   < [32m  ) ) ) )
[32m       '  [31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\[32m / / / /
[0m    =========================================[32m/_/_/_/[0m

	Version:        3.7.9
	Build time:     05.11.2023 00:43:11 UTC
	Branch          HEAD
	Commit:         0206007
	Commit time:    05.11.2023 00:21:56 UTC
	JVM:            17.0.9
	Lavaplayer      1.5.1

2023-11-05 15:01:18.521  INFO 7756 --- [main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-11-05 15:01:19.239  WARN 7756 --- [main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-11-05 15:01:19.273  INFO 7756 --- [main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-11-05 15:01:19.273  INFO 7756 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 747 ms
2023-11-05 15:01:19.417  INFO 7756 --- [main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2023-11-05 15:01:19.588  INFO 7756 --- [main] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube master token (current is null).
2023-11-05 15:01:20.018  INFO 7756 --- [ForkJoinPool.commonPool-worker-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube master token succeeded, new token is deleted by me.
2023-11-05 15:01:20.116  INFO 7756 --- [main] lavalink.server.config.KoeConfiguration  : OS: LINUX, Arch: X86_64
2023-11-05 15:01:20.116  INFO 7756 --- [main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2023-11-05 15:01:20.120  INFO 7756 --- [main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2023-11-05 15:01:20.125  INFO 7756 --- [main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2023-11-05 15:01:20.177  WARN 7756 --- [main] l.server.config.SentryConfiguration      : Turning off sentry
2023-11-05 15:01:20.438  INFO 7756 --- [main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2023-11-05 15:01:20.446  INFO 7756 --- [main] org.xnio                                 : XNIO version 3.8.6.Final
2023-11-05 15:01:20.455  INFO 7756 --- [main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2023-11-05 15:01:20.529  INFO 7756 --- [main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2023-11-05 15:01:20.572  INFO 7756 --- [main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 2333 (http)
2023-11-05 15:01:20.578  INFO 7756 --- [main] lavalink.server.Launcher                 : Started Launcher in 2.105 seconds (JVM running for 3.809)
2023-11-05 15:01:20.579  INFO 7756 --- [main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2023-11-05 15:06:02.883  INFO 7756 --- [XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-11-05 15:06:02.883  INFO 7756 --- [XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-11-05 15:06:02.884  INFO 7756 --- [XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-11-05 15:06:02.901  INFO 7756 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:49080
2023-11-05 15:06:02.918  INFO 7756 --- [XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /, client=127.0.0.1
2023-11-05 15:06:03.077  INFO 7756 --- [XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from InsertNameHereBot/v5.3.2 (ID: 1170499765767782471)
2023-11-05 15:06:17.916  INFO 7756 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"889539584566890506","volume":100}
2023-11-05 15:06:17.918  WARN 7756 --- [XNIO-1 I/O-3] lavalink.server.io.WebSocketHandler      : Sending websocket commands to Lavalink has been deprecated and will be removed in API version 4. API version 3 will be removed in Lavalink 5. Please use the new REST endpoints instead.
2023-11-05 15:06:18.136  INFO 7756 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op":"voiceUpdate","guildId":"889539584566890506","sessionId":"58a9a2c4cb464a9ead458128e729f307","event":{"token":"deleted by me","guild_id":"889539584566890506","endpoint":"frankfurt487.discord.media:443"}}
2023-11-05 15:06:18.568  INFO 7756 --- [XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:xdd"
2023-11-05 15:06:19.291  INFO 7756 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: xdd
2023-11-05 15:06:19.367  INFO 7756 --- [XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /loadtracks?identifier=ytsearch%3Axdd, client=127.0.0.1
2023-11-05 15:06:19.373  INFO 7756 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op":"play","guildId":"889539584566890506","track":"QAAAcAIAA3hERAATZGogdHJpcHBpZSBmbGFtZWJveQAAAAAAAhcoAAtqRFVzUkVBZWhVNAABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PWpEVXNSRUFlaFU0AAd5b3V0dWJlAAAAAAAAAAA="}
2023-11-05 15:06:19.389  INFO 7756 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube access token (current is null).
2023-11-05 15:06:19.868  INFO 7756 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube access token succeeded, new token is deleted by me, next update will be after 74444 seconds.
2023-11-05 15:06:19.943 ERROR 7756 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of jDUsREAehU4

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[lavaplayer-1.5.1.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.1
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-88-generic
  java.vendor: Azul Systems, Inc.
  java.version: 17.0.9
  java.runtime.version: 17.0.9+8-LTS
  java.vm.version: 17.0.9+8-LTS
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for youtube embed video id: 500
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:67) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:78) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-1.5.1.jar!/:na]
	... 4 common frames omitted
Caused by: java.io.IOException: Invalid status code for youtube embed video id: 500
	at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.fetchScript(DefaultYoutubeTrackDetailsLoader.java:283) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:202) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-1.5.1.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-1.5.1.jar!/:na]
	... 7 common frames omitted

2023-11-05 15:06:19.966  INFO 7756 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"889539584566890506"}
2023-11-05 15:06:20.447  INFO 7756 --- [XNIO-1 I/O-3] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"889539584566890506"}`
```

## Additional context
On Older versions I was getting 403 error

**Comment by topi314** [comment]
duplicate of https://github.com/lavalink-devs/lavaplayer/issues/25

**Comment by Nashiauwu** [comment]
I messed up copying logs, will submit another issue
